name: 'Docker Build'
description: 'Builds `addons-server` docker image'
inputs:
  password:
    required: false
    description: "Docker registry password"
    default: "invalid"
  push:
    required: false
    description: "Build and push image to registry (cannot be used together with load)"
    default: "false"
  username:
    required: false
    description: "Docker registry username"
    default: "invalid"

outputs:
  digest:
    description: "The Docker image digest"
    value: ${{ steps.digest.outputs.digest }}
  version:
    description: "The Docker version for the image"
    value: ${{ steps.meta.outputs.version }}
  tags:
    description: "The Docker tags for the image"
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ "${{ inputs.push  }}" == "true" && "${{ github.ref }}" == "refs/heads/master" ]]; then
          echo "Cannot push to registry from master branch unless we migrate our master build job to GHA."
          exit 1
        fi
    # Setup docker to build for multiple architectures
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
        buildkitd-flags: --debug

    # Login to a registry to push the image
    - name: Login to Container Registry
      # Only login if we are pushing the image
      if: ${{ inputs.push == 'true' }}
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    # Determine the tags for the image
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # Hard coding our dockerhub imnage name
        images: mozilla/addons-server
        flavor: |
          prefix=ci-,onlatest=false
        tags: |
          type=schedule
          type=ref,event=tag
          type=ref,event=branch
          type=ref,event=pr
          # set latest tag for default branch
          # Disabled for now as we do not use this action for
          # The production build
          # type=raw,value=latest,enable={{is_default_branch}}

    - name: Define environment variables
      shell: bash
      run: |
        echo "DOCKER_VERSION=${{ steps.meta.outputs.version }}" >> $GITHUB_ENV
        echo "DOCKER_COMMIT=${{ github.sha }}" >> $GITHUB_ENV
        echo "VERSION_BUILD_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

    - name: Create .env and version.json files
      shell: bash
      run: make setup

    - name: Build Image
      id: build
      uses: docker/bake-action@v4
      with:
        targets: web
        push: ${{ inputs.push }}
        load: ${{ inputs.push == 'false' }}

    - name: Get image digest
      id: digest
      shell: bash
      run: |
        echo '${{ steps.build.outputs.metadata }}' > metadata.json
        echo "digest=$(jq -r '.web."containerimage.digest"' metadata.json )" >> $GITHUB_OUTPUT
