name: 'Docker Run Action'
description: 'Run a command in a new container'
inputs:
  version:
    description: 'The version of the image to run. '
    required: true
    default: 'local'
  digest:
    description: 'The build digest of the image to run. Overrides version.'
    required: true
    default: ''
  run:
    description: 'Run command in container'
    required: true
  compose_file:
    description: 'The docker-compose file to use'
    required: false
    default: 'docker-compose.yml:docker-compose.ci.yml'
  logs:
    description: 'Show logs'
    required: false
  data_backup_skip:
    description: 'Skip data backup'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - id: id
      shell: bash
      run: |
        echo "id=$(id -u)" >> $GITHUB_OUTPUT

    - name: Run Docker Container
      shell: bash
      env:
        DOCKER_VERSION: ${{ inputs.version }}
        DOCKER_DIGEST: ${{ inputs.digest }}
        COMPOSE_FILE: ${{ inputs.compose_file }}
        HOST_UID: ${{ steps.id.outputs.id }}
        DATA_BACKUP_SKIP: ${{ inputs.data_backup_skip }}
        # In CI, we should use the docker-compose wait flag to ensure
        # healthchecks are passing before running any commands on the containers.
        # This comes at a performance cost, but ensures containers are ready
        # to accept commands before CI continues to execute.
        DOCKER_WAIT: true
      run: |
        # Start the specified services
        make up

        # Exec the run command in the container
        # quoted 'EOF' to prevent variable expansion
        cat <<'EOF' | docker compose exec --user olympia web sh
          ${{ inputs.run }}
        EOF

    - name: Logs
      shell: bash
      if: ${{ inputs.logs }}
      run: docker compose logs
