name: 'Docker Run Action'
description: 'Run a command in a new container'
inputs:
  version:
    description: 'The version of the image to run. '
    required: true
    default: 'local'
  digest:
    description: 'The build digest of the image to run. Overrides version.'
    required: true
    default: ''
  run:
    description: 'Run command in container'
    required: true
  services:
    description: 'List of services to start'
    required: false
    default: 'web'
runs:
  using: 'composite'
  steps:
    - id: id
      shell: bash
      run: |
        echo "id=$(id -u)" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
        buildkitd-flags: --debug

    - name: Run Docker Container
      shell: bash
      env:
        DOCKER_BUILDER: ${{ steps.buildx.outputs.name}}
        DOCKER_VERSION: ${{ inputs.version }}
        DOCKER_DIGEST: ${{ inputs.digest }}
        DOCKER_SERVICES: ${{ inputs.services }}
        HOST_UID: ${{ steps.id.outputs.id }}
      run: |
        # Start the specified services
        make up

        # Exec the run command in the container
        # quoted 'EOF' to prevent variable expansion
        cat <<'EOF' | docker compose exec --user olympia web sh
          ${{ inputs.run }}
        EOF

    - name: Logs
      shell: bash
      if: failure()
      run: docker compose logs
