name: 'Docker Run Action'
description: 'Run a command in a new container'
inputs:
  version:
    description: 'The version of the image to run. '
    required: true
    default: 'local'
  digest:
    description: 'The build digest of the image to run. Overrides version.'
    required: true
    default: ''
  run:
    description: 'Run command in container'
    required: true
  logs:
    description: 'Show logs'
    required: false
  target:
    description: 'Docker target to run (development|production)'
    required: false
    default: 'production'
  deps:
    description: 'Which dependencies to install at runtime? (development|production)'
    required: false
    default: 'production'
  minimal:
    description: 'Run the command in a container with minimal services or the full environment.'
    default: false

runs:
  using: 'composite'
  steps:
    - name: Prepare Environment
      shell: bash
      env:
        version: ${{ inputs.version }}
        digest: ${{ inputs.digest }}
        target: ${{ inputs.target }}
        deps: ${{ inputs.deps }}
      run: |
        make up_pre \
          DOCKER_VERSION="${version}" \
          DOCKER_DIGEST="${digest}" \
          DOCKER_TARGET="${target}" \
          OLYMPIA_UID="$(id -u)" \
          OLYMPIA_DEPS="${deps}"
    - name: Start services
      if: inputs.minimal == 'false'
      run: make up_start DOCKER_WAIT="true"
    - name: Initialize environment
      if: inputs.minimal == 'false'
      run: make up_post SKIP_DATA_SEED="true"
    - name: Run Docker Container
      id: run
      continue-on-error: true
      shell: bash
      env:
        run: ${{ inputs.run }}
        minimal: ${{ inputs.minimal }}
      run: |
        if [[ "$minimal" == "true" ]]; then
          # Run only the specified command in a throwaway container
          docker compose -f docker-compose.yml -f docker-compose.minimal.yml run --rm web "${run}"
        else
          # Run the specified command in a full environment
          docker compose exec --user olympia web bash -c "${run}"
        fi

    - name: Post Run (logs and exit code)
      if: always()
      shell: bash
      env:
        logs: ${{ inputs.logs }}
        outcome: ${{ steps.run.outcome }}
      run: |
        if [[ "$logs" == "true" ]]; then
          docker compose logs
        fi

        # If the run command failed, exit with a non-zero exit code
        if [ "$outcome" != 'success' ]; then
          exit 1
        fi
