# Generated by Django 2.2.14 on 2020-07-16 15:50

from django.db import migrations


def remove_waffle_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    # This switch was never enabled in production, we're removing it to replace
    # it with a flag. We don't need to create it as it will be disabled for
    # everyone by default.
    Switch.objects.filter(name='2fa-for-developers').all().delete()


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(remove_waffle_switch)]
