# Generated by Django 4.2.28 on 2026-02-19 12:05

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_remove_old_2fa_waffle_switch'),
    ]

    operations = [
        CreateWaffleSwitch('enable-session-anomaly-recording')
    ]
