# Generated by Django 4.2.20 on 2025-04-17 18:58

from django.db import migrations
import olympia.core.db.migrations


def migration_task(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_remove_old_2fa_waffle_switch'),
    ]

    operations = [
        olympia.core.db.migrations.MigrationTask(
        ),
    ]
