# Generated by Django 5.2.17 on 2026-09-01 13:42

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_session_anomaly_waffle_switch'),
    ]

    operations = [
        CreateWaffleSwitch('2fa-reprompt')
    ]
