# Generated by Django 4.2.13 on 2024-06-11 09:37

import aesfield.field
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import olympia.amo.fields
import olympia.amo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('type', models.PositiveIntegerField(choices=[(1, 1)], default=0)),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('secret', aesfield.field.AESField(aes_key='api_key:secret', aes_method=settings.AES_METHOD, aes_prefix='aes:')),
            ],
            options={
                'db_table': 'api_key',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
