# Generated by Django 2.2.21 on 2021-05-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
