# Generated by Django 5.2.16 on 2026-07-24 10:36

from django.db import migrations


def update_permissions(apps, schema_editor):
    Group = apps.get_model('access', 'Group')
    # Addons:ViewDeleted -> Addons:ApiViewDeleted
    for group in Group.objects.filter(rules__like='Addons:ViewDeleted'):
        group.rules = group.rules.replace('Addons:ViewDeleted', 'Addons:ApiViewDeleted')
        group.save()

    # Give Addons:ApiView to all groups that have Addons:Review
    for group in Group.objects.all():
        rules = group.rules.split(',')
        if (
            'Addons:ReviewUnlisted' in rules
            or 'ReviewerTools:ViewUnlisted' in rules
        ) and 'Addons:ApiViewUnlisted' not in rules:
            if 'Addons:ApiView' not in rules:
                rules.append('Addons:ApiView')
            rules.append('Addons:ApiViewUnlisted')
        elif (
            'Addons:Review' in rules
            or 'ReviewerTools:View' in rules
            or 'Addons:ThemeReview' in rules
            or 'Addons:ContentReview' in rules
        ) and 'Addons:ApiView' not in rules:
            rules.append('Addons:ApiView')
        else:
            continue

        group.rules = ','.join(rules)
        group.save()

    # Give Addons:ApiViewUnlisted to all groups that have Addons:ReviewUnlisted
    for group in Group.objects.filter(rules__like='Addons:ReviewUnlisted'):
        group.rules = group.rules + ',Addons:ApiViewUnlisted'
        group.save()


def un_update_permissions(apps, schema_editor):
    Group = apps.get_model('access', 'Group')
    # Addons:ApiViewDeleted -> Addons:ViewDeleted
    for group in Group.objects.filter(rules__like='Addons:ApiViewDeleted'):
        group.rules = group.rules.replace('Addons:ApiViewDeleted', 'Addons:ViewDeleted')
        group.save()

    # Remove Addons:ApiView and Addons:ApiViewUnlisted from all groups that have them
    for group in Group.objects.all():
        rules = group.rules.split(',')
        if 'Addons:ApiView' in rules:
            rules.remove('Addons:ApiView')
        if 'Addons:ApiViewUnlisted' in rules:
            rules.remove('Addons:ApiViewUnlisted')
        group.rules = ','.join(rules)
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210511_1256'),
    ]

    operations = [
        migrations.RunPython(code=update_permissions, reverse_code=un_update_permissions)
    ]
