# Generated by Django 5.2.16 on 2026-08-03 11:18

from django.db import migrations

from src.olympia.constants.permissions import (
    ADDONS_API_VIEW, ADDONS_API_VIEW_DELETED, ADDONS_API_VIEW_UNLISTED
)

GROUP_NAME = 'Service: All API access'

def create_group(apps, schema_editor):
    Group = apps.get_model('access', 'Group')

    rules = ','.join(
        str(perm)
        for perm in (
            ADDONS_API_VIEW, ADDONS_API_VIEW_UNLISTED, ADDONS_API_VIEW_DELETED
        )
    )
    Group.objects.create(
        name=GROUP_NAME,
        rules=rules,
        notes=(
            'Used to give certain service accounts access to all add-ons via the API. '
            'Do not change the group name - it is referenced in documentation'
        ),
    )

def delete_group(apps, schema_editor):
    Group = apps.get_model('access', 'Group')

    Group.objects.filter(name=GROUP_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20260724_1036'),
    ]

    operations = [
        migrations.RunPython(create_group, delete_group)
    ]
