changelog:
  categories:
    - title: Notable things shipping
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: Dependendabots
      labels:
        - dependencies
