# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import olympia.amo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('reviewers', '0001_initial'),
        ('versions', '0001_initial'),
        ('blocklist', '0002_initial'),
        ('activity', '0001_initial'),
        ('ratings', '0002_initial'),
        ('access', '0002_initial'),
        ('abuse', '0004_initial'),
        ('addons', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericMozillaUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.userprofile',),
        ),
        migrations.AddField(
            model_name='versionlog',
            name='activity_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitylog'),
        ),
        migrations.AddField(
            model_name='versionlog',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versions.version'),
        ),
        migrations.AddField(
            model_name='reviewactionreasonlog',
            name='activity_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitylog'),
        ),
        migrations.AddField(
            model_name='reviewactionreasonlog',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewers.reviewactionreason'),
        ),
        migrations.AddField(
            model_name='ratinglog',
            name='activity_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitylog'),
        ),
        migrations.AddField(
            model_name='ratinglog',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratings.rating'),
        ),
        migrations.AddField(
            model_name='iplog',
            name='activity_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity.activitylog'),
        ),
        migrations.AddField(
            model_name='grouplog',
            name='activity_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitylog'),
        ),
        migrations.AddField(
            model_name='grouplog',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.group'),
        ),
        migrations.AddField(
            model_name='draftcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='draftcomment',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versions.version'),
        ),
        migrations.AddField(
            model_name='commentlog',
            name='activity_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitylog'),
        ),
        migrations.AddField(
            model_name='cinderpolicylog',
            name='activity_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitylog'),
        ),
        migrations.AddField(
            model_name='cinderpolicylog',
            name='cinder_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abuse.cinderpolicy'),
        ),
        migrations.AddField(
            model_name='blocklog',
            name='activity_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitylog'),
        ),
        migrations.AddField(
            model_name='blocklog',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blocklist.block'),
        ),
        migrations.AddField(
            model_name='addonlog',
            name='activity_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitylog'),
        ),
        migrations.AddField(
            model_name='addonlog',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons.addon'),
        ),
        migrations.AddField(
            model_name='activitylogtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylogtoken',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='versions.version'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='iplog',
            index=olympia.amo.models.LongNameIndex(fields=['_ip_address'], name='log_activity_ip_ip_address_ba36172a'),
        ),
        migrations.AddIndex(
            model_name='iplog',
            index=olympia.amo.models.LongNameIndex(fields=['ip_address_binary'], name='log_activity_ip_ip_address_binary_209777a9'),
        ),
        migrations.AddConstraint(
            model_name='activitylogtoken',
            constraint=models.UniqueConstraint(fields=('version', 'user'), name='version_id'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='log_activity_1bd4707b'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created'], name='log_activity_created_idx'),
        ),
    ]
