# Generated by Django 2.2.6 on 2019-11-15 11:51

from django.db import migrations, models

from olympia import amo


def set_guid_from_block(apps, schema_editor):
    BlockLog = apps.get_model('activity', 'BlockLog')
    for log in BlockLog.objects.filter(guid=''):
        log.update(guid=log.block.guid)

    ActivityLog = apps.get_model('activity', 'ActivityLog')
    ActivityLog.objects.filter(
        action=amo.LOG.BLOCKLIST_BLOCK_DELETED.id).update(_details='{}')


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20191107_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklog',
            name='guid',
            field=models.CharField(max_length=255, null=True, default=''),
        ),
        migrations.AlterField(
            model_name='blocklog',
            name='block',
            field=models.ForeignKey(
                null=True, on_delete=models.deletion.SET_NULL, to='blocklist.Block'),
        ),
        migrations.RunPython(set_guid_from_block),
    ]
