# Generated by Django 2.2.6 on 2019-11-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20191115_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklog',
            name='guid',
            field=models.CharField(max_length=255),
        ),
    ]
