# Generated by Django 2.2.10 on 2020-03-10 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20191125_1659'),
    ]

    operations = [
        migrations.RunSQL(
            "alter table log_activity_group drop foreign key log_activity_group_group_id_e03ab8c8_fk_groups_id",
            "alter table log_activity_group add foreign key (group_id) references groups(id) on DELETE CASCADE"
        )
    ]
