# Generated by Django 3.2.6 on 2021-08-13 09:41

from django.db import migrations, models

from olympia.amo.migrations import RenameIndexesOperation


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20210325_1320'),
    ]

    operations = [
        RenameIndexesOperation(
            'log_activity',
            [
                (
                    migrations.AddIndex(
                        model_name='activitylog',
                        index=models.Index(fields=['created'], name='log_activity_created_idx'),
                    ),
                    'created_idx',
                )
            ],
        ),
    ]
