# Generated by Django 3.2.6 on 2021-08-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20210325_1320'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created'], name='log_activity_created_idx'),
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='created_idx',
        ),
    ]
