# Generated by Django 3.2.6 on 2021-08-23 14:47

from django.db import migrations
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20210813_0941'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='iplog',
            index=olympia.amo.models.LongNameIndex(fields=['ip_address'], name='log_activity_ip_ip_address_ba36172a'),
        ),
    ]
