# Generated by Django 3.2.6 on 2021-08-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20210813_0941'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='iplog',
            index=models.Index(fields=['ip_address'], name='log_activity_ip_ip_ba36172a'),
        ),
    ]
