# Generated by Django 3.2.8 on 2021-11-02 13:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0016_reviewactionreason'),
        ('activity', '0011_iplog_log_activity_ip_ip_address_ba36172a'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewActionReasonLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewers.reviewactionreason')),
                ('version_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.versionlog')),
            ],
            options={
                'db_table': 'log_activity_review_action_reason',
                'ordering': ('-created',),
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
