# Generated by Django 3.2.8 on 2021-11-04 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_reviewactionreasonlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewactionreasonlog',
            name='version_log',
        ),
        migrations.AddField(
            model_name='reviewactionreasonlog',
            name='activity_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitylog'),
        ),
    ]
