# Generated by Django 3.2.15 on 2022-09-05 15:41

from django.db import migrations, models
import olympia.amo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_auto_20220826_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplog',
            name='ip_address_binary',
            field=olympia.amo.fields.IPAddressBinaryField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='iplog',
            name='ip_address',
            field=models.CharField(db_column='ip_address', max_length=45, null=True),
        ),
        migrations.RenameField(
            model_name='iplog',
            old_name='ip_address',
            new_name='_ip_address',
        ),

    ]
