# Generated by Django 3.2.16 on 2022-11-22 13:13

from django.db import migrations, models
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_auto_20220905_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlog',
            name='comments',
            field=models.TextField(max_length=100000),
        ),
    ]
