# Generated by Django 3.2.16 on 2022-12-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_auto_20221122_1313'),
        ('activity', '0018_auto_20221128_1706'),
    ]

    operations = [
    ]
