# Generated by Django 3.2.16 on 2023-01-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0020_auto_20221214_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplog',
            name='activity_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity.activitylog'),
        ),
    ]
