# Generated by Django 3.2.16 on 2023-01-26 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0021_alter_iplog_activity_log'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Avoid a database operation for this, as we just need to alter the
            # python on_delete callback. Database operations would normally be:
            # ALTER TABLE `log_activity` DROP FOREIGN KEY `log_activity_user_id_6ed3455e_fk_users_id`;
            # ALTER TABLE `log_activity` MODIFY `user_id` integer NOT NULL;
            # ALTER TABLE `log_activity` ADD CONSTRAINT `log_activity_user_id_6ed3455e_fk_users_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='activitylog',
                    name='user',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='users.userprofile',
                    ),
                )
            ],
        )
    ]
