# Generated by Django 3.2.18 on 2023-02-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0022_alter_activitylog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftcomment',
            name='canned_response',
        ),
    ]
