# Generated by Django 4.2.25 on 2025-10-29 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0029_alter_activitylog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFingerprintLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ja4', models.CharField(db_index=True, max_length=36)),
                ('signals', models.JSONField(default=list)),
                ('activity_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity.activitylog')),
            ],
            options={
                'db_table': 'log_activity_request_fingerprint',
                'ordering': ('-created',),
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
