# Generated by Django 5.2.14 on 2026-06-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0032_alter_activitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplog',
            name='asn',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
