# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _


ALL_CURRENCIES = {
    'AED': _(u'United Arab Emirates Dirham'),
    'AFN': _(u'Afghanistan Afghani'),
    'ALL': _(u'Albania Lek'),
    'AMD': _(u'Armenia Dram'),
    'ANG': _(u'Netherlands Antilles Guilder'),
    'AOA': _(u'Angola Kwanza'),
    'ARS': _(u'Argentina Peso'),
    'AUD': _(u'Australia Dollar'),
    'AWG': _(u'Aruba Guilder'),
    'AZN': _(u'Azerbaijan New Manat'),
    'BAM': _(u'Bosnia and Herzegovina Convertible Marka'),
    'BBD': _(u'Barbados Dollar'),
    'BDT': _(u'Bangladesh Taka'),
    'BGN': _(u'Bulgaria Lev'),
    'BHD': _(u'Bahrain Dinar'),
    'BIF': _(u'Burundi Franc'),
    'BMD': _(u'Bermuda Dollar'),
    'BND': _(u'Brunei Darussalam Dollar'),
    'BOB': _(u'Bolivia Boliviano'),
    'BRL': _(u'Brazil Real'),
    'BSD': _(u'Bahamas Dollar'),
    'BTN': _(u'Bhutan Ngultrum'),
    'BWP': _(u'Botswana Pula'),
    'BYR': _(u'Belarus Ruble'),
    'BZD': _(u'Belize Dollar'),
    'CAD': _(u'Canada Dollar'),
    'CDF': _(u'Congo/Kinshasa Franc'),
    'CHF': _(u'Switzerland Franc'),
    'CLP': _(u'Chile Peso'),
    'CNY': _(u'China Yuan Renminbi'),
    'COP': _(u'Colombia Peso'),
    'CRC': _(u'Costa Rica Colon'),
    'CUC': _(u'Cuba Convertible Peso'),
    'CUP': _(u'Cuba Peso'),
    'CVE': _(u'Cape Verde Escudo'),
    'CZK': _(u'Czech Republic Koruna'),
    'DJF': _(u'Djibouti Franc'),
    'DKK': _(u'Denmark Krone'),
    'DOP': _(u'Dominican Republic Peso'),
    'DZD': _(u'Algeria Dinar'),
    'EGP': _(u'Egypt Pound'),
    'ERN': _(u'Eritrea Nakfa'),
    'ETB': _(u'Ethiopia Birr'),
    'EUR': _(u'Euro Member Countries'),
    'FJD': _(u'Fiji Dollar'),
    'FKP': _(u'Falkland Islands (Malvinas) Pound'),
    'GBP': _(u'United Kingdom Pound'),
    'GEL': _(u'Georgia Lari'),
    'GGP': _(u'Guernsey Pound'),
    'GHS': _(u'Ghana Cedi'),
    'GIP': _(u'Gibraltar Pound'),
    'GMD': _(u'Gambia Dalasi'),
    'GNF': _(u'Guinea Franc'),
    'GTQ': _(u'Guatemala Quetzal'),
    'GYD': _(u'Guyana Dollar'),
    'HKD': _(u'Hong Kong Dollar'),
    'HNL': _(u'Honduras Lempira'),
    'HRK': _(u'Croatia Kuna'),
    'HTG': _(u'Haiti Gourde'),
    'HUF': _(u'Hungary Forint'),
    'IDR': _(u'Indonesia Rupiah'),
    'ILS': _(u'Israel Shekel'),
    'IMP': _(u'Isle of Man Pound'),
    'INR': _(u'India Rupee'),
    'IQD': _(u'Iraq Dinar'),
    'IRR': _(u'Iran Rial'),
    'ISK': _(u'Iceland Krona'),
    'JEP': _(u'Jersey Pound'),
    'JMD': _(u'Jamaica Dollar'),
    'JOD': _(u'Jordan Dinar'),
    'JPY': _(u'Japan Yen'),
    'KES': _(u'Kenya Shilling'),
    'KGS': _(u'Kyrgyzstan Som'),
    'KHR': _(u'Cambodia Riel'),
    'KMF': _(u'Comoros Franc'),
    'KPW': _(u'Korea (North) Won'),
    'KRW': _(u'Korea (South) Won'),
    'KWD': _(u'Kuwait Dinar'),
    'KYD': _(u'Cayman Islands Dollar'),
    'KZT': _(u'Kazakhstan Tenge'),
    'LAK': _(u'Laos Kip'),
    'LBP': _(u'Lebanon Pound'),
    'LKR': _(u'Sri Lanka Rupee'),
    'LRD': _(u'Liberia Dollar'),
    'LSL': _(u'Lesotho Loti'),
    'LTL': _(u'Lithuania Litas'),
    'LVL': _(u'Latvia Lat'),
    'LYD': _(u'Libya Dinar'),
    'MAD': _(u'Morocco Dirham'),
    'MDL': _(u'Moldova Leu'),
    'MGA': _(u'Madagascar Ariary'),
    'MKD': _(u'Macedonia Denar'),
    'MMK': _(u'Myanmar (Burma) Kyat'),
    'MNT': _(u'Mongolia Tughrik'),
    'MOP': _(u'Macau Pataca'),
    'MRO': _(u'Mauritania Ouguiya'),
    'MUR': _(u'Mauritius Rupee'),
    'MVR': _(u'Maldives (Maldive Islands) Rufiyaa'),
    'MWK': _(u'Malawi Kwacha'),
    'MXN': _(u'Mexico Peso'),
    'MYR': _(u'Malaysia Ringgit'),
    'MZN': _(u'Mozambique Metical'),
    'NAD': _(u'Namibia Dollar'),
    'NGN': _(u'Nigeria Naira'),
    'NIO': _(u'Nicaragua Cordoba'),
    'NOK': _(u'Norway Krone'),
    'NPR': _(u'Nepal Rupee'),
    'NZD': _(u'New Zealand Dollar'),
    'OMR': _(u'Oman Rial'),
    'PAB': _(u'Panama Balboa'),
    'PEN': _(u'Peru Nuevo Sol'),
    'PGK': _(u'Papua New Guinea Kina'),
    'PHP': _(u'Philippines Peso'),
    'PKR': _(u'Pakistan Rupee'),
    'PLN': _(u'Poland Zloty'),
    'PYG': _(u'Paraguay Guarani'),
    'QAR': _(u'Qatar Riyal'),
    'RON': _(u'Romania New Leu'),
    'RSD': _(u'Serbia Dinar'),
    'RUB': _(u'Russia Ruble'),
    'RWF': _(u'Rwanda Franc'),
    'SAR': _(u'Saudi Arabia Riyal'),
    'SBD': _(u'Solomon Islands Dollar'),
    'SCR': _(u'Seychelles Rupee'),
    'SDG': _(u'Sudan Pound'),
    'SEK': _(u'Sweden Krona'),
    'SGD': _(u'Singapore Dollar'),
    'SHP': _(u'Saint Helena Pound'),
    'SLL': _(u'Sierra Leone Leone'),
    'SOS': _(u'Somalia Shilling'),
    'SPL': _(u'Seborga Luigino'),
    'SRD': _(u'Suriname Dollar'),
    'STD': _(u'São Tomé and Príncipe Dobra'),
    'SVC': _(u'El Salvador Colon'),
    'SYP': _(u'Syria Pound'),
    'SZL': _(u'Swaziland Lilangeni'),
    'THB': _(u'Thailand Baht'),
    'TJS': _(u'Tajikistan Somoni'),
    'TMT': _(u'Turkmenistan Manat'),
    'TND': _(u'Tunisia Dinar'),
    'TOP': _(u'Tonga Pa\'anga'),
    'TRY': _(u'Turkey Lira'),
    'TTD': _(u'Trinidad and Tobago Dollar'),
    'TVD': _(u'Tuvalu Dollar'),
    'TWD': _(u'Taiwan New Dollar'),
    'TZS': _(u'Tanzania Shilling'),
    'UAH': _(u'Ukraine Hryvna'),
    'UGX': _(u'Uganda Shilling'),
    'USD': _(u'United States Dollar'),
    'UYU': _(u'Uruguay Peso'),
    'UZS': _(u'Uzbekistan Som'),
    'VEF': _(u'Venezuela Bolivar'),
    'VND': _(u'Viet Nam Dong'),
    'VUV': _(u'Vanuatu Vatu'),
    'WST': _(u'Samoa Tala'),
    'XAF': _(u'Communauté Financière Africaine (BEAC) CFA Franc BEAC'),
    'XCD': _(u'East Caribbean Dollar'),
    'XDR': _(u'International Monetary Fund (IMF) Special Drawing Rights'),
    'XOF': _(u'Communauté Financière Africaine (BCEAO) Franc'),
    'XPF': _(u'Comptoirs Français du Pacifique (CFP) Franc'),
    'YER': _(u'Yemen Rial'),
    'ZAR': _(u'South Africa Rand'),
    'ZMW': _(u'Zambia Kwacha'),
    'ZWD': _(u'Zimbabwe Dollar')
}
