x-olympia-mount: &olympia-mount
  /data/olympia

services:
  olympia:
    volumes:
      - *olympia-mount
  worker:
    environment:
      - HOST_UID=9500
    volumes:
      - *olympia-mount

  web:
    extends:
      service: worker

  nginx:
    volumes:
      - *olympia-mount
