services:
  worker:
    environment:
      - HOST_UID=9500
    volumes:
      - /data/olympia
      - storage:/data/olympia/storage

  web:
    extends:
      service: worker

  nginx:
    volumes:
      - storage:/srv/storage

volumes:
  storage:
