services:
  worker:
    environment:
    - CELERY_BROKER_URL=amqp://olympia:olympia@rabbitmq/olympia
    - CELERY_RESULT_BACKEND=redis://redis:6379/1
    - DATABASES_DEFAULT_URL=mysql://root:@mysqld/olympia
    - ELASTICSEARCH_LOCATION=elasticsearch:9200
    - MEMCACHE_LOCATION=memcached:11211
    - MYSQL_DATABASE=olympia
    - MYSQL_ROOT_PASSWORD=docker
    - OLYMPIA_SITE_URL=http://olympia.test
    - PYTHONDONTWRITEBYTECODE=1
    - PYTHONUNBUFFERED=1
    - PYTHONBREAKPOINT=ipdb.set_trace
    - TERM=xterm-256color
    - CIRCLECI=${CIRCLECI}
    - HISTFILE=/data/olympia/docker/artifacts/bash_history
    - HISTSIZE=50000
    - HISTIGNORE=ls:exit:"cd .."
    - HISTCONTROL=erasedups
    # Note: docker compose uses the values exported from .env for HOST_UID if
    # it exists. ./docker/entrypoint.sh uses this variable to fix
    # the uid of the olympia user to match the host user id if necessary.
    - HOST_UID=${HOST_UID:-}
    # This is the email address of the superuser created when initializing the db
    - SUPERUSER_EMAIL=${SUPERUSER_EMAIL:-admin@mozilla.com}
    - SUPERUSER_USERNAME=${SUPERUSER_USERNAME:-admin}
    image: mozilla/addons-server:${DOCKER_VERSION:-local}
    # We drop down to a different user through supervisord, but starting as
    # root allows us to fix the ownership of files generated at image build
    # time through the ./docker/entrypoint.sh script.
    user: root
    platform: linux/amd64
    entrypoint: ["/data/olympia/docker/entrypoint.sh"]
    command:
      - supervisord -n -c /data/olympia/docker/supervisor-celery.conf
    extra_hosts:
     - "olympia.test:127.0.0.1"
    restart: on-failure:5

  web:
    extends:
      service: worker
    command:
      - supervisord -n -c /data/olympia/docker/supervisor.conf
