name: test_actions

services:
  base:
    image: scratch
    working_dir: /workdir
    volumes:
      - .:/workdir

  actionlint:
    extends: base
    image: rhysd/actionlint:1.7.12@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667

  zizmor:
    extends: base
    image: ghcr.io/zizmorcore/zizmor:1.18.0@sha256:c5bbdb28b75702f181695d7a878e562ccb5c0a01847db87edda7476908d73dd6
    environment:
      - GH_TOKEN
