# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.fields
import olympia.amo.models
import olympia.files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(db_column='filename', default='', max_length=255, storage=olympia.files.models.files_storage, upload_to=olympia.files.models.files_upload_to_callback)),
                ('size', models.PositiveIntegerField(default=0)),
                ('hash', models.CharField(default='', max_length=255)),
                ('original_hash', models.CharField(default='', max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Awaiting Review'), (4, 'Approved'), (5, 'Disabled by Mozilla')], default=1)),
                ('datestatuschanged', models.DateTimeField(auto_now_add=True, null=True)),
                ('strict_compatibility', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(null=True)),
                ('cert_serial_num', models.TextField(blank=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('is_experiment', models.BooleanField(default=False)),
                ('is_mozilla_signed_extension', models.BooleanField(default=False)),
                ('original_status', models.PositiveSmallIntegerField(default=0)),
                ('status_disabled_reason', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Developer disabled'), (2, 'Add-on disabled'), (3, 'Add-on deleted'), (4, 'Version deleted')], default=0)),
                ('manifest_version', models.SmallIntegerField(choices=[(2, 'Manifest V2'), (3, 'Manifest V3')])),
            ],
            options={
                'db_table': 'files',
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.OnChangeMixin, olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WebextPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('permissions', models.JSONField(default=dict)),
                ('optional_permissions', models.JSONField(default=dict)),
                ('host_permissions', models.JSONField(default=dict)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_webext_permissions', to='files.file')),
            ],
            options={
                'db_table': 'webext_permissions',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FileValidation',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('valid', models.BooleanField(default=False)),
                ('errors', models.IntegerField(default=0)),
                ('warnings', models.IntegerField(default=0)),
                ('notices', models.IntegerField(default=0)),
                ('validation', models.TextField()),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='files.file')),
            ],
            options={
                'db_table': 'file_validation',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('path', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', help_text="The user's original filename", max_length=255)),
                ('hash', models.CharField(default='', max_length=255)),
                ('valid', models.BooleanField(default=False)),
                ('validation', models.TextField(null=True)),
                ('channel', models.PositiveSmallIntegerField(choices=[(1, 'Unlisted'), (2, 'Listed')])),
                ('version', models.CharField(max_length=255, null=True)),
                ('access_token', models.CharField(max_length=40, null=True)),
                ('ip_address', models.CharField(max_length=45)),
                ('source', models.PositiveSmallIntegerField(choices=[(1, 'Developer Hub'), (2, 'Signing API'), (3, 'Add-on API'), (4, 'Automatically generated by AMO')])),
                ('addon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addons.addon')),
            ],
            options={
                'db_table': 'file_uploads',
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
