# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('versions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='versions.version'),
        ),
        migrations.AddConstraint(
            model_name='fileupload',
            constraint=models.UniqueConstraint(fields=('uuid',), name='uuid'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['created', 'version'], name='created_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['datestatuschanged', 'version'], name='statuschanged_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['status'], name='status'),
        ),
    ]
