# Generated by Django 2.2.12 on 2020-04-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='ip_address',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Developer Hub'), (2, 'API')], default=None, null=True),
        ),
    ]
