# Generated by Django 2.2.14 on 2020-07-23 13:55

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_add_remote_addr_and_source_to_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='webextpermission',
            name='optional_permissions',
            field=django_extensions.db.fields.json.JSONField(default={}),
        ),
    ]
