# Generated by Django 2.2.16 on 2020-09-23 18:08

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_webextpermission_optional_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webextpermission',
            name='optional_permissions',
            field=django_jsonfield_backport.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='webextpermission',
            name='permissions',
            field=django_jsonfield_backport.models.JSONField(default=dict),
        ),
    ]
