# Generated by Django 2.2.17 on 2020-11-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20200923_1808'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fileupload',
            name='file_uploads_afe99c5e',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='compat_with_app',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='compat_with_appver',
        ),
    ]
