# Generated by Django 2.2.19 on 2021-04-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20210315_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='platform',
        ),
    ]
