# Generated by Django 2.2.23 on 2021-06-08 15:40

from django.db import migrations


def create_waffle_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.create(
        name='enable-manifest-normalization',
        active=False,
        note='Rewrite manifest.json file during repack',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_remove_file_platform'),
    ]

    operations = [migrations.RunPython(create_waffle_switch)]
