# Generated by Django 3.2.4 on 2021-07-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_enable_mv3_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='manifest_version',
            field=models.SmallIntegerField(default=2),
        ),
    ]
