# Generated by Django 3.2.4 on 2021-08-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_file_manifest_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='is_restart_required',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
