# Generated by Django 3.2.6 on 2021-08-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_alter_file_is_restart_required'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='files_cedd2560',
        ),
        migrations.AlterField(
            model_name='file',
            name='binary',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='binary_components',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
