# Generated by Django 3.2.6 on 2021-08-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0016_auto_20210325_1320'),
        ('files', '0013_auto_20210830_1424'),
    ]

    operations = [
        migrations.RunSQL(
            # We're changing a ForeignKey to OneToOneField but django doesn't know how
            # to do that efficiently.
            "ALTER TABLE `files` ADD CONSTRAINT `files_version_id_44ed234d_uniq` UNIQUE (`version_id`);",
            state_operations=[
                migrations.AlterField(
                    model_name='file',
                    name='version',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='versions.version'),
                ),
            ],
        ),
    ]
