# Generated by Django 3.2.6 on 2021-09-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_auto_20210906_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='is_webextension',
            field=models.BooleanField(null=True),
        ),
    ]
