# Generated by Django 3.2.11 on 2022-01-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0019_alter_fileupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='ip_address',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Developer Hub'), (2, 'Signing API'), (3, 'Addon API'), (4, 'Automatically generated by AMO')]),
        ),
    ]
