# Generated by Django 3.2.13 on 2022-05-03 18:55

from django.db import migrations
import olympia.files.fields
import olympia.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0020_auto_20220124_1457'),
    ]

    operations = [
        migrations.RunSQL(
            # This migration is purely for Django migrations to catch up with
            # what we're doing. We're not changing the schema at all, it's
            # still a varchar underneath.
            migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.RemoveField(
                    model_name='file',
                    name='filename',
                ),
                migrations.AddField(
                    model_name='file',
                    name='file',
                    field=olympia.files.fields.FilenameFileField(
                        db_column='filename',
                        default='',
                        max_length=255,
                        storage=olympia.files.models.files_storage,
                        upload_to=olympia.files.models.files_upload_to_callback,
                    ),
                ),
            ],
        )
    ]
