# Generated by Django 3.2.14 on 2022-08-03 12:40

from django.db import migrations, models

from olympia import amo


def set_channel(apps, schema):
    FileUpload = apps.get_model('files', 'FileUpload')
    # Channel was given a default of CHANNEL_UNLISTED in the AddField, so we just need to
    # correct the value for listed (automated_signing=False)
    FileUpload.objects.filter(automated_signing=False).update(channel=amo.CHANNEL_LISTED)

class Migration(migrations.Migration):

    dependencies = [
        ('files', '0022_alter_fileupload_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='channel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unlisted'), (2, 'Listed')], default=amo.CHANNEL_UNLISTED),
            preserve_default=False,
        ),
        migrations.RunPython(set_channel),
        migrations.AlterField(
            model_name='fileupload',
            name='automated_signing',
            field=models.BooleanField(null=True),
        ),
    ]
