# Generated by Django 3.2.16 on 2022-11-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0024_auto_20220819_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='automated_signing',
        ),
        migrations.DeleteModel(
            name='FileSitePermission',
        ),
    ]
