# Generated by Django 3.2.16 on 2022-11-04 13:12

from django.db import migrations


def blank_file_for_files_with_old_path(apps, schema_editor):
    File = apps.get_model('files', 'File')

    # Rows that do not contain a "/" in their paths were not migrated to the
    # new directory structure, which means the file they are pointing to no
    # longer exists, so remove it to avoid confusion.
    File.objects.exclude(file__contains='/').update(file='')


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0025_auto_20221104_1311'),
    ]

    operations = [migrations.RunPython(blank_file_for_files_with_old_path)]
