# Generated by Django 3.2.16 on 2023-01-07 00:48
from django.db import migrations

from olympia import amo


def set_approval_date_from_reviewed(apps, schema_editor):
    File = apps.get_model('files', 'File')
    file_qs = File.objects.filter(
        status=amo.STATUS_APPROVED, reviewed__isnull=False)
    for file in file_qs:
        file.approval_date = file.reviewed
        file.save(update_fields=['approval_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0027_auto_20230131_1818'),
    ]

    operations = [migrations.RunPython(set_approval_date_from_reviewed)]
