# Generated by Django 3.2.18 on 2023-03-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0028_set_approval_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='webextpermission',
            name='host_permissions',
            field=models.JSONField(default=dict),
        ),
    ]
