# Generated by Django 4.2.2 on 2023-06-29 12:50

from django.db import migrations
from olympia.core.db.migrations import DeleteWaffleSwitch


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0029_auto_20230301_1843'),
    ]

    operations = [DeleteWaffleSwitch('add-guid-to-manifest')]
