# Generated by Django 4.2.7 on 2023-11-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0030_remove-add-guid-to-manifest-waffle-switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status_disabled_reason',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Developer disabled'), (2, 'Add-on disabled'), (3, 'Add-on deleted'), (4, 'Version deleted')], default=0),
        ),
    ]
