# Generated by Django 4.2.7 on 2023-11-07 15:46

from django.db import migrations

from olympia import amo
from olympia.files.models import File as FileModel


def set_status_disabled_reason(apps, schema_editor):
    File = apps.get_model('files', 'File')
    (
        File.objects.filter(status=amo.STATUS_DISABLED)
        .exclude(original_status=amo.STATUS_NULL)
        .update(status_disabled_reason=FileModel.STATUS_DISABLED_REASONS.DEVELOPER)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0031_file_status_disabled_reason'),
    ]

    operations = [
        migrations.RunPython(set_status_disabled_reason)
    ]
