# Generated by Django 4.2.13 on 2024-08-05 13:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0032_auto_20231107_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManifest',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='file_manifest', serialize=False, to='files.file')),
                ('manifest_data', models.JSONField(default=dict)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
