# Generated by Django 4.2.21 on 2025-05-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0033_filemanifest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='reviewed',
        ),
    ]
