# Generated by Django 4.2.21 on 2025-06-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0033_filemanifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='webextpermission',
            name='data_collection_permissions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='webextpermission',
            name='optional_data_collection_permissions',
            field=models.JSONField(default=dict),
        ),
    ]
