# Generated by Django 4.2.24 on 2025-10-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0034_add_data_collection_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='reviewed',
        ),
    ]
