# Generated by Django 4.2.24 on 2025-10-03 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0035_remove_file_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='datestatuschanged',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
