# Generated by Django 4.2.25 on 2025-10-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0036_alter_file_datestatuschanged'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='request_metadata',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
