# Generated by Django 4.2.28 on 2026-02-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0037_fileupload_request_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='original_hash',
            field=models.CharField(default='', max_length=255),
        ),
    ]
