# Generated by Django 4.2.17 on 2025-01-21 11:37

from django.db import migrations


def forwards_func(apps, schema_editor):
    Translation = apps.get_model('translations', 'Translation')
    Translation.objects.filter(locale='es').update(locale='es-es')


def backwards_func(apps, schema_editor):
    Translation = apps.get_model('translations', 'Translation')
    Translation.objects.filter(locale='es-es').update(locale='es')


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
