# Generated by Django 4.2.21 on 2025-05-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_update_all_es_translations_to_es-es'),
    ]

    operations = [
        migrations.CreateModel(
            name='PureTranslation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('translations.translation',),
        ),
        migrations.CreateModel(
            name='PurifiedMarkdownTranslation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('translations.purifiedtranslation',),
        ),
    ]
