# Generated by Django 5.2.13 on 2026-04-28 21:26

from django.db import migrations, router


def remove_legacy_translations_constraints(apps, schema_editor):
    """
    Remove Foreign Key constraints to Translations.id - TranslatedField should
    now be using db_constraint: False as there can be multiple translation rows
    sharing the same id, one per locale per translated string.
    """
    Translation = apps.get_model('translations', 'Translation')
    models_related_to_translations = {
        f.related_model
        for f in Translation._meta.get_fields(include_hidden=True)
        if f.auto_created and not f.concrete and (f.one_to_one or f.one_to_many)
    }
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        for model in models_related_to_translations:
            constraints = connection.introspection.get_constraints(
                cursor, model._meta.db_table
            )
            for name, info in constraints.items():
                if info['foreign_key'] == (Translation._meta.db_table, 'id'):
                    schema_editor.execute(
                        schema_editor._delete_fk_sql(model, name), params=None
                    )


class Migration(migrations.Migration):
    # We're going to execute ALTER TABLE statements that are not supported
    # inside a transaction, so disable transaction management to avoid
    # "Executing DDL statements while in a transaction on databases that can't
    # perform a rollback is prohibited" error.
    atomic = False

    dependencies = [
        ('translations', '0003_puretranslation_purifiedmarkdowntranslation'),
        # Depend on these apps as they use TranslatedField
        ('addons', '0060_backfill_last_content_review_status'),
        ('versions', '0052_delete_enable_source_builder_waffle_switch'),
        ('bandwagon', '0010_fix_default_locale_spanish'),
    ]

    operations = [
        migrations.RunPython(remove_legacy_translations_constraints, lambda *args: None)
    ]
