# Generated by Django 2.2.5 on 2019-10-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akismet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AkismetReport',
        ),
    ]
