ALTER TABLE `files`
    MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    MODIFY `version_id` int(10) unsigned NOT NULL,
    MODIFY `platform_id` int(10) unsigned NOT NULL,
    MODIFY `filename` varchar(255) NOT NULL,
    MODIFY `size` int(10) unsigned NOT NULL,
    MODIFY `hash` varchar(255) NOT NULL,
    MODIFY `status` smallint(5) unsigned NOT NULL,
    MODIFY `datestatuschanged` datetime(6) DEFAULT NULL,
    MODIFY `created` datetime(6) NOT NULL,
    MODIFY `modified` datetime(6) NOT NULL,
    MODIFY `reviewed` datetime(6) DEFAULT NULL,
    MODIFY `strict_compatibility` tinyint(1) NOT NULL,
    MODIFY `binary` tinyint(1) NOT NULL,
    MODIFY `binary_components` tinyint(1) NOT NULL,
    MODIFY `cert_serial_num` longtext NOT NULL,
    MODIFY `is_signed` tinyint(1) NOT NULL,
    MODIFY `original_hash` varchar(255) NOT NULL,
    MODIFY `is_experiment` tinyint(1) NOT NULL,
    MODIFY `is_webextension` tinyint(1) NOT NULL,
    MODIFY `original_status` smallint(5) unsigned NOT NULL,
    MODIFY `is_mozilla_signed_extension` tinyint(1) NOT NULL,
    DROP KEY `version_id`,
    DROP FOREIGN KEY `files_ibfk_1`,  /* (`version_id`) REFERENCES `versions` (`id`) ON DELETE CASCADE*/
    ADD KEY `files_version_id_44ed234d` (`version_id`),
    ADD CONSTRAINT `files_version_id_44ed234d_fk_versions_id` FOREIGN KEY (`version_id`) REFERENCES `versions` (`id`);
