ALTER TABLE `versions`
    CHANGE COLUMN `addon_id` `addon_id` INT (10) UNSIGNED NOT NULL,
    CHANGE COLUMN `approvalnotes` `approvalnotes` LONGTEXT,
    CHANGE COLUMN `channel` `channel` INT (11) NOT NULL,
    CHANGE COLUMN `created` `created` DATETIME (6) NOT NULL,
    CHANGE COLUMN `deleted` `deleted` TINYINT (1) NOT NULL,
    CHANGE COLUMN `git_hash` `git_hash` VARCHAR (40) NOT NULL,
    CHANGE COLUMN `id` `id` INT (10) UNSIGNED NOT NULL AUTO_INCREMENT,
    CHANGE COLUMN `license_id` `license_id` INT (10) UNSIGNED DEFAULT NULL,
    CHANGE COLUMN `modified` `modified` DATETIME (6) NOT NULL,
    CHANGE COLUMN `nomination` `nomination` DATETIME (6) DEFAULT NULL,
    CHANGE COLUMN `recommendation_approved` `recommendation_approved` TINYINT (1) NOT NULL,
    CHANGE COLUMN `releasenotes` `releasenotes` INT (10) UNSIGNED DEFAULT NULL,
    CHANGE COLUMN `reviewed` `reviewed` DATETIME (6) DEFAULT NULL,
    CHANGE COLUMN `source_git_hash` `source_git_hash` VARCHAR (40) NOT NULL,
    CHANGE COLUMN `version` `version` VARCHAR (255) NOT NULL,
    DROP FOREIGN KEY `versions_ibfk_1`,
    DROP FOREIGN KEY `versions_ibfk_2`,
    DROP FOREIGN KEY `versions_ibfk_3`,
    DROP INDEX `versions_ibfk_2`,
    ADD CONSTRAINT `versions_addon_id_dddd8677_fk_addons_id` FOREIGN KEY (`addon_id`) REFERENCES `addons` (`id`),
    ADD CONSTRAINT `versions_license_id_29419889_fk_licenses_id` FOREIGN KEY (`license_id`) REFERENCES `licenses` (`id`),
    ADD CONSTRAINT `versions_releasenotes_514848aa_fk_translations_id` FOREIGN KEY (`releasenotes`) REFERENCES `translations` (`id`),
    ADD UNIQUE INDEX `releasenotes` (`releasenotes`);
