ALTER TABLE `users`
    CHANGE COLUMN `banned` `banned` DATETIME (6) DEFAULT NULL,
    CHANGE COLUMN `basket_token` `basket_token` VARCHAR (128) NOT NULL,
    CHANGE COLUMN `bypass_upload_restrictions` `bypass_upload_restrictions` TINYINT (1) NOT NULL,
    CHANGE COLUMN `created` `created` DATETIME (6) NOT NULL,
    CHANGE COLUMN `deleted` `deleted` TINYINT (1) NOT NULL,
    CHANGE COLUMN `display_collections` `display_collections` TINYINT (1) NOT NULL,
    CHANGE COLUMN `display_name` `display_name` VARCHAR (50) DEFAULT NULL,
    CHANGE COLUMN `email_changed` `email_changed` DATETIME (6) DEFAULT NULL,
    CHANGE COLUMN `email` `email` VARCHAR (75) DEFAULT NULL,
    CHANGE COLUMN `homepage` `homepage` VARCHAR (255) NOT NULL,
    CHANGE COLUMN `last_login_ip` `last_login_ip` VARCHAR (45) NOT NULL,
    CHANGE COLUMN `last_login` `last_login` DATETIME (6) DEFAULT NULL,
    CHANGE COLUMN `location` `location` VARCHAR (255) NOT NULL,
    CHANGE COLUMN `modified` `modified` DATETIME (6) NOT NULL,
    CHANGE COLUMN `notes` `notes` LONGTEXT,
    CHANGE COLUMN `occupation` `occupation` VARCHAR (255) NOT NULL,
    CHANGE COLUMN `password` `password` VARCHAR (128) NOT NULL,
    CHANGE COLUMN `public` `public` TINYINT (1) NOT NULL,
    CHANGE COLUMN `read_dev_agreement` `read_dev_agreement` DATETIME (6) DEFAULT NULL;
    /*CHANGE COLUMN `username` `username` VARCHAR (255) NOT NULL;*/
