CREATE TABLE `users_blacklistedemaildomain` (
  `id` int(11) NOT NULL auto_increment,
  `domain` varchar(255) NOT NULL default '',
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `domain` (`domain`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO
    `users_blacklistedemaildomain` (`domain`, `created`, `modified`)
VALUES
    ('mailinator.com',NOW(),NOW()),
    ('mailinator2.com',NOW(),NOW()),
    ('fuckingduh.com',NOW(),NOW()),
    ('sogetthis.com',NOW(),NOW()),
    ('mailin8r.com',NOW(),NOW()),
    ('mailinator.net',NOW(),NOW()),
    ('klassmaster.com',NOW(),NOW()),
    ('putthisinyourspamdatabase.com',NOW(),NOW()),
    ('thisisnotmyrealemail.com',NOW(),NOW()),
    ('binkmail.com',NOW(),NOW()),
    ('spamhereplease.com',NOW(),NOW()),
    ('spamherelots.com',NOW(),NOW()),
    ('sendspamhere.com',NOW(),NOW()),
    ('chogmail.com',NOW(),NOW()),
    ('spamthisplease.com',NOW(),NOW()),
    ('frapmail.com',NOW(),NOW()),
    ('obobbo.com',NOW(),NOW()),
    ('devnullmail.com',NOW(),NOW()),
    ('bumpymail.com',NOW(),NOW()),
    ('centermail.com',NOW(),NOW()),
    ('centermail.net',NOW(),NOW()),
    ('discardmail.com',NOW(),NOW()),
    ('dodgeit.com',NOW(),NOW()),
    ('e4ward.com',NOW(),NOW()),
    ('emailias.com',NOW(),NOW()),
    ('fakeinformation.com',NOW(),NOW()),
    ('front14.org',NOW(),NOW()),
    ('ghosttexter.de',NOW(),NOW()),
    ('jetable.net',NOW(),NOW()),
    ('kasmail.com',NOW(),NOW()),
    ('link2mail.net',NOW(),NOW()),
    ('mailexpire.com',NOW(),NOW()),
    ('mailmoat.com',NOW(),NOW()),
    ('messagebeamer.de',NOW(),NOW()),
    ('mytrashmail.com',NOW(),NOW()),
    ('nervmich.net',NOW(),NOW()),
    ('netmails.net',NOW(),NOW()),
    ('netzidiot.de',NOW(),NOW()),
    ('nurfuerspam.de',NOW(),NOW()),
    ('oneoffemail.com',NOW(),NOW()),
    ('pookmail.com',NOW(),NOW()),
    ('privacy.net',NOW(),NOW()),
    ('punkass.com',NOW(),NOW()),
    ('sneakemail.com',NOW(),NOW()),
    ('sofort-mail.de',NOW(),NOW()),
    ('spam.la',NOW(),NOW()),
    ('spambob.com',NOW(),NOW()),
    ('spambob.net',NOW(),NOW()),
    ('spambob.org',NOW(),NOW()),
    ('spamex.com',NOW(),NOW()),
    ('spamgourmet.com',NOW(),NOW()),
    ('spamhole.com',NOW(),NOW()),
    ('spaminator.de',NOW(),NOW()),
    ('spammotel.com',NOW(),NOW()),
    ('spamtrail.com',NOW(),NOW()),
    ('trash-mail.de',NOW(),NOW()),
    ('trashmail.net',NOW(),NOW()),
    ('wuzup.net',NOW(),NOW()),
    ('suremail.info',NOW(),NOW()),
    ('spammote.com',NOW(),NOW());
