name: 'Docker Build'
description: 'Builds `addons-server` docker image'
inputs:
  update_deps_command:
    required: true
    description: "The command to run to update dependencies"
  python_version:
    required: false
    description: "Python version"
    default: "3.10"

runs:
  using: "composite"
  steps:
    # Make sure pip cahce directory exists on the host
    - run: |
        mkdir -p -- "$(pip cache dir)"
      shell: bash

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'pip'

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - run: ${{ inputs.update_deps_command }}
      shell: bash
