# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import olympia.amo.fields
import olympia.amo.models
import olympia.translations.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addons', '0001_initial'),
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('slug', models.CharField(blank=True, max_length=30, null=True)),
                ('default_locale', models.CharField(db_column='defaultlocale', default='en-US', max_length=10)),
                ('listed', models.BooleanField(default=True, help_text='Collections are either listed or private.')),
                ('addon_count', models.PositiveIntegerField(db_column='addonCount', default=0)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'collections',
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'unfiltered',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
            managers=[
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CollectionAddon',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Add-ons are displayed in ascending order based on this field.')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons.addon')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandwagon.collection')),
                ('comments', olympia.translations.fields.LinkifiedField(blank=True, db_column='comments', max_length=280, null=True, on_delete=django.db.models.deletion.SET_NULL, require_locale=True, short=True, to='translations.LinkifiedTranslation', to_field='id', unique=True)),
            ],
            options={
                'db_table': 'addons_collections',
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
