# Generated by Django 2.2.6 on 2019-11-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandwagon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedCollection',
        ),
    ]
