# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import olympia.translations.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bandwagon', '0001_initial'),
        ('translations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addons', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionaddon',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='addons',
            field=models.ManyToManyField(related_name='collections', through='bandwagon.CollectionAddon', to='addons.addon'),
        ),
        migrations.AddField(
            model_name='collection',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=olympia.translations.fields.NoURLsField(blank=True, db_column='description', max_length=280, null=True, on_delete=django.db.models.deletion.SET_NULL, require_locale=False, short=True, to='translations.NoURLsTranslation', to_field='id', unique=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='name',
            field=olympia.translations.fields.TranslatedField(blank=True, db_column='name', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, require_locale=False, short=True, to='translations.Translation', to_field='id', unique=True),
        ),
        migrations.AddIndex(
            model_name='collectionaddon',
            index=models.Index(fields=['collection', 'created'], name='addons_collections_created_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionaddon',
            index=models.Index(fields=['addon'], name='addons_collections_addon_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionaddon',
            index=models.Index(fields=['collection'], name='collection_id'),
        ),
        migrations.AddIndex(
            model_name='collectionaddon',
            index=models.Index(fields=['user'], name='addons_collections_user_id'),
        ),
        migrations.AddConstraint(
            model_name='collectionaddon',
            constraint=models.UniqueConstraint(fields=('addon', 'collection'), name='addon_id_2'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['created'], name='collections_created_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['listed'], name='collections_listed_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['slug'], name='collections_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('author', 'slug'), name='author_id'),
        ),
    ]
