# Generated by Django 2.2.13 on 2020-06-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandwagon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedCollection',
        ),
    ]
