# Generated by Django 2.2.20 on 2021-04-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwagon', '0002_delete_featuredcollection'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collection',
            name='application_id',
        ),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.PositiveIntegerField(db_column='collection_type', default=0, null=True),
        ),
    ]
