# Generated by Django 3.2.6 on 2021-08-13 09:41

from django.db import migrations, models

from olympia.amo.migrations import RenameIndexesOperation


class Migration(migrations.Migration):

    dependencies = [
        ('bandwagon', '0004_auto_20210511_1256'),
    ]

    operations = [
        RenameIndexesOperation(
            'collections',
            [
                (
                    migrations.AddIndex(
                        model_name='collection',
                        index=models.Index(fields=['created'], name='collections_created_idx'),
                    ),
                    'created_idx',
                ),
                (
                    migrations.AddIndex(
                        model_name='collection',
                        index=models.Index(fields=['listed'], name='collections_listed_idx'),
                    ),
                    'listed',
                ),
                (
                    migrations.AddIndex(
                        model_name='collection',
                        index=models.Index(fields=['slug'], name='collections_slug_idx'),
                    ),
                    'slug_idx',
                ),
            ],
        ),
        RenameIndexesOperation(
            'addons_collections',
            [
                (
                    migrations.AddIndex(
                        model_name='collectionaddon',
                        index=models.Index(fields=['collection', 'created'], name='addons_collections_created_idx'),
                    ),
                    'created_idx',
                ),
                (
                    migrations.AddIndex(
                        model_name='collectionaddon',
                        index=models.Index(fields=['addon'], name='addons_collections_addon_idx'),
                    ),
                    'addon_id',
                ),
                (
                    migrations.AddIndex(
                        model_name='collectionaddon',
                        index=models.Index(fields=['user'], name='addons_collections_user_id'),
                    ),
                    'user_id',
                ),
            ],
        ),
    ]
