# Generated by Django 3.2.6 on 2021-08-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwagon', '0004_auto_20210511_1256'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['created'], name='collections_created_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['listed'], name='collections_listed_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['slug'], name='collections_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionaddon',
            index=models.Index(fields=['collection', 'created'], name='addons_collections_created_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionaddon',
            index=models.Index(fields=['addon'], name='addons_collections_addon_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionaddon',
            index=models.Index(fields=['user'], name='addons_collections_user_id'),
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='created_idx',
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='listed',
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='collectionaddon',
            name='created_idx',
        ),
        migrations.RemoveIndex(
            model_name='collectionaddon',
            name='addon_id',
        ),
        migrations.RemoveIndex(
            model_name='collectionaddon',
            name='user_id',
        ),
    ]
