# Generated by Django 3.2.16 on 2022-11-22 13:12

from django.db import migrations
import django.db.models.deletion
import olympia.translations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('bandwagon', '0005_auto_20210813_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=olympia.translations.fields.NoURLsField(blank=True, db_column='description', max_length=280, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Collection_description_set+', require_locale=False, short=True, to='translations.NoURLsTranslation', to_field='id', unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=olympia.translations.fields.TranslatedField(blank=True, db_column='name', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Collection_name_set+', require_locale=False, short=True, to='translations.Translation', to_field='id', unique=True),
        ),
        migrations.AlterField(
            model_name='collectionaddon',
            name='comments',
            field=olympia.translations.fields.LinkifiedField(blank=True, db_column='comments', max_length=280, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CollectionAddon_comments_set+', require_locale=True, short=True, to='translations.LinkifiedTranslation', to_field='id', unique=True),
        ),
    ]
