# Generated by Django 4.2.1 on 2023-05-24 08:34

from django.db import migrations
import django.db.models.deletion
import olympia.translations.fields


class Migration(migrations.Migration):
    dependencies = [
        ('translations', '0001_initial'),
        ('bandwagon', '0006_auto_20221122_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=olympia.translations.fields.NoURLsField(
                blank=True,
                db_column='description',
                max_length=280,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                require_locale=False,
                short=True,
                to='translations.NoURLsTranslation',
                to_field='id',
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=olympia.translations.fields.TranslatedField(
                blank=True,
                db_column='name',
                max_length=50,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                require_locale=False,
                short=True,
                to='translations.Translation',
                to_field='id',
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='collectionaddon',
            name='comments',
            field=olympia.translations.fields.LinkifiedField(
                blank=True,
                db_column='comments',
                max_length=280,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                require_locale=True,
                short=True,
                to='translations.LinkifiedTranslation',
                to_field='id',
                unique=True,
            ),
        ),
    ]
