# Generated by Django 4.2.7 on 2023-11-13 12:19

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bandwagon', '0007_alter_collection_description_alter_collection_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'base_manager_name': 'unfiltered', 'get_latest_by': 'created'},
        ),
        migrations.AlterModelManagers(
            name='collection',
            managers=[
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
