# Generated by Django 4.2.17 on 2025-01-21 11:41

from django.db import migrations


def forwards_func(apps, schema_editor):
    Collection = apps.get_model('bandwagon', 'Collection')
    Collection.unfiltered.filter(default_locale='es').update(default_locale='es-es')


def backwards_func(apps, schema_editor):
    Collection = apps.get_model('bandwagon', 'Collection')
    Collection.unfiltered.filter(default_locale='es-es').update(default_locale='es')


class Migration(migrations.Migration):

    dependencies = [
        ('bandwagon', '0008_alter_collection_options_alter_collection_managers_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
