# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('average_daily_users_snapshot', models.IntegerField(null=True)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlocklistSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('action', models.SmallIntegerField(choices=[(0, 'Add/Change'), (1, 'Delete')], default=0)),
                ('input_guids', models.TextField()),
                ('changed_version_ids', models.JSONField(default=list)),
                ('to_block', models.JSONField(default=list)),
                ('url', models.CharField(blank=True, help_text='The URL related to this block, i.e. the bug filed.', max_length=255, null=True)),
                ('reason', models.TextField(blank=True, help_text='Note this reason will be displayed publicly on the block-addon pages.', null=True)),
                ('signoff_state', models.SmallIntegerField(choices=[(0, 'Pending Sign-off'), (1, 'Approved'), (2, 'Rejected'), (3, 'Auto Sign-off'), (4, 'Published')], default=0)),
                ('delayed_until', models.DateTimeField(blank=True, help_text='The submission will not be published into blocks before this time.', null=True)),
                ('disable_addon', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'blocklist_blocklistsubmission',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlockVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocklist.block')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
