# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('versions', '0001_initial'),
        ('blocklist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockversion',
            name='version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='versions.version'),
        ),
        migrations.AddField(
            model_name='blocklistsubmission',
            name='signoff_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blocklistsubmission',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block',
            name='submission',
            field=models.ManyToManyField(to='blocklist.blocklistsubmission'),
        ),
        migrations.AddField(
            model_name='block',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
