# Generated by Django 2.2.6 on 2019-12-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0004_multiblocksubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='kinto_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
