# Generated by Django 2.2.6 on 2019-11-28 10:10

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0004_multiblocksubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiblocksubmit',
            name='processed_guids',
            field=django_extensions.db.fields.json.JSONField(default={}),
        ),
    ]
