# Generated by Django 2.2.6 on 2019-12-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0005_multiblocksubmit_processed_guids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiblocksubmit',
            name='max_version',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AlterField(
            model_name='multiblocksubmit',
            name='min_version',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
