# Generated by Django 2.2.9 on 2020-01-15 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blocklist', '0007_block_kinto_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiBlockSubmit',
            new_name='BlockSubmission',
        ),
        migrations.AddField(
            model_name='blocksubmission',
            name='signoff_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blocksubmission',
            name='signoff_state',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (
                2, 'Rejected'), (3, 'No Sign-off'), (4, 'Published to Blocks')], default=0),
        ),
    ]
