# Generated by Django 2.2.9 on 2020-01-17 06:09

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0008_blocksubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocksubmission',
            name='processed_guids',
        ),
        migrations.AddField(
            model_name='block',
            name='submission',
            field=models.ManyToManyField(null=True, to='blocklist.BlockSubmission'),
        ),
        migrations.AddField(
            model_name='blocksubmission',
            name='to_block_guids',
            field=django_extensions.db.fields.json.JSONField(default=[]),
        ),
    ]
