# Generated by Django 2.2.9 on 2020-01-17 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0008_kintoimport'),
        ('blocklist', '0008_blocksubmission'),
    ]

    operations = [
    ]
