# Generated by Django 2.2.9 on 2020-01-12 03:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blocklist', '0008_multiblocksubmit_signoff_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiBlockSubmit',
            new_name='BlockSubmission',
        ),
    ]
