# Generated by Django 2.2.9 on 2020-01-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0009_auto_20200112_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocksubmission',
            name='signoff',
            field=models.BooleanField(null=True),
        ),
    ]
