# Generated by Django 2.2.9 on 2020-01-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0009_blocksumission_rm_processed_guids'),
        ('blocklist', '0009_merge_20200117_0302'),
    ]

    operations = [
    ]
