# Generated by Django 2.2.9 on 2020-01-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0009_auto_20200117_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocksubmission',
            old_name='to_block_guids',
            new_name='to_block',
        ),
        migrations.AlterField(
            model_name='block',
            name='submission',
            field=models.ManyToManyField(to='blocklist.BlockSubmission'),
        ),
    ]
