# Generated by Django 2.2.9 on 2020-01-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0010_blocksubmit_signoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocksubmission',
            name='signoff',
        ),
        migrations.AddField(
            model_name='blocksubmission',
            name='signoff_state',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'No Sign-off')], default=0),
        ),
    ]
