# Generated by Django 2.2.9 on 2020-03-18 04:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blocklist', '0011_blocksubmission_submission_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockSubmission',
            new_name='BlocklistSubmission',
        ),
        migrations.AlterModelOptions(
            name='blocklistsubmission',
            options={},
        ),
        migrations.AlterModelTable(
            name='blocklistsubmission',
            table='blocklist_blocklistsubmission',
        ),
    ]
