# Generated by Django 2.2.12 on 2020-05-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0012_auto_20200318_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='kintoimport',
            name='timestamp',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
