# Generated by Django 2.2.12 on 2020-05-20 17:25

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields.json
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0014_auto_20200513_1212'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='KintoImport',
            table='blocklist_kintoimport'),
        migrations.RenameModel(
            old_name='KintoImport',
            new_name='LegacyImport'),
        migrations.AlterField(
            model_name='block',
            name='kinto_id',
            field=models.CharField(
                db_column='kinto_id',
                db_index=True,
                default='',
                max_length=255),
        ),migrations.RenameField(
            model_name='block',
            old_name='kinto_id',
            new_name='legacy_id',
        ),

    ]
