# Generated by Django 2.2.12 on 2020-05-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0015_auto_20200520_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legacyimport',
            options={},
        ),
        migrations.AlterField(
            model_name='legacyimport',
            name='kinto_id',
            field=models.CharField(db_column='kinto_id', default='', max_length=255, unique=True),
        ),
        migrations.RenameField(
            model_name='legacyimport',
            old_name='kinto_id',
            new_name='legacy_id',
        ),
    ]
