# Generated by Django 2.2.14 on 2020-07-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0016_auto_20200521_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocklistsubmission',
            old_name='include_in_legacy',
            new_name='legacy_id',
        ),
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='legacy_id',
            field=models.BooleanField(db_column='include_in_legacy', default=False, help_text='Include in legacy xml blocklist too, as well as new v3'),
        ),
        migrations.AlterField(
            model_name='block',
            name='include_in_legacy',
            field=models.NullBooleanField(default=None, help_text='Include in legacy xml blocklist too, as well as new v3'),
        ),
    ]
