# Generated by Django 2.2.14 on 2020-07-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0017_auto_20200723_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='include_in_legacy',
        ),
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='legacy_id',
            field=models.BooleanField(db_column='include_in_legacy', default=False, help_text='Include in legacy xml blocklist too, as well as new v3', verbose_name='In legacy blocklist'),
        ),
    ]
