# Generated by Django 2.2.14 on 2020-08-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0018_auto_20200731_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='average_daily_users_snapshot',
            field=models.IntegerField(null=True),
        ),
    ]
