# Generated by Django 2.2.16 on 2020-11-03 11:07

from django.db import migrations
import olympia.blocklist.models
import olympia.versions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0021_auto_20201028_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='min_version',
            field=olympia.versions.fields.VersionStringField(default='0', max_length=255, validators=[olympia.blocklist.models.no_asterisk]),
        ),
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='min_version',
            field=olympia.versions.fields.VersionStringField(default='0', max_length=255, validators=[olympia.blocklist.models.no_asterisk]),
        ),
    ]
