# Generated by Django 2.2.16 on 2020-11-03 11:08

from django.db import migrations


def replace_asterisk_in_min_version(apps, schema_editor):
    Block = apps.get_model('blocklist', 'Block')
    for block in Block.objects.filter(min_version__contains='*'):
        block.min_version = block.min_version.replace('*', '0')
        block.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0022_auto_20201103_1107'),
    ]

    operations = [
        migrations.RunPython(replace_asterisk_in_min_version)
    ]
