# Generated by Django 3.2.6 on 2021-09-03 08:50

from django.db import migrations

def rm_import_waffle_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    # drop the waffle switch blocklist_auto_import to avoid confusion
    Switch.objects.filter(name='blocklist_auto_import').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0023_auto_20201103_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegacyImport',
        ),
        migrations.RunPython(rm_import_waffle_switch),
    ]
