# Generated by Django 3.2.6 on 2021-09-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0024_delete_legacyimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='legacy_id',
            field=models.CharField(
                db_column='kinto_id',
                db_index=True,
                default='',
                max_length=255,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='legacy_id',
            field=models.BooleanField(
                db_column='include_in_legacy',
                default=False,
                null=True
            ),
        ),
    ]
