# Generated by Django 3.2.9 on 2021-12-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0025_alter_block_legacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='reason',
            field=models.TextField(blank=True, help_text='Note this reason will be displayed publicly on the block-addon pages.'),
        ),
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='url',
            field=models.CharField(blank=True, help_text='The URL related to this block, i.e. the bug filed.', max_length=255),
        ),
    ]
