# Generated by Django 3.2.13 on 2022-05-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0026_auto_20211214_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='blocklistsubmission',
            name='legacy_id',
        ),
    ]
