# Generated by Django 3.2.15 on 2023-03-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0027_auto_20220530_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklistsubmission',
            name='delayed_until',
            field=models.DateTimeField(help_text='The submission will not be published into blocks before this time.', null=True),
        ),
    ]
