# Generated by Django 4.2.1 on 2023-05-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blocklist', '0028_auto_20230316_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='delayed_until',
            field=models.DateTimeField(
                blank=True,
                help_text='The submission will not be published into blocks before this time.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='signoff_state',
            field=models.SmallIntegerField(
                choices=[
                    (0, 'Pending Sign-off'),
                    (1, 'Approved'),
                    (2, 'Rejected'),
                    (3, 'Auto Sign-off'),
                    (4, 'Published to Blocks'),
                ],
                default=0,
            ),
        ),
    ]
