# Generated by Django 4.2.1 on 2023-06-05 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):
    dependencies = [
        ('blocklist', '0030_alter_blocklistsubmission_signoff_state_blockversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklistsubmission',
            name='disable_addon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blocklistsubmission',
            name='changed_version_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='block',
            name='max_version',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='min_version',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='max_version',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='min_version',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
