# Generated by Django 4.2.1 on 2023-06-12 14:47

from django.db import migrations


def convert_min_max_to_block_version(apps, schema_editor):
    Block = apps.get_model('blocklist', 'Block')
    BlockVersion = apps.get_model('blocklist', 'BlockVersion')
    File = apps.get_model('files', 'File')

    for block in Block.objects.all():
        block_versions = [
            BlockVersion(version_id=version_id, block=block)
            for version_str, version_id in File.objects.filter(
                version__addon__addonguid__guid=block.guid
            ).values_list('version__version', 'version_id')
            if (block.min_version == '0' and block.max_version == '*')
            or (block.min_version <= version_str and block.max_version >= version_str)
        ]
        BlockVersion.objects.bulk_create(block_versions)


class Migration(migrations.Migration):
    dependencies = [
        ('blocklist', '0030_block_complete_blocklistsubmission_complete_and_more'),
    ]

    operations = [migrations.RunPython(convert_min_max_to_block_version)]
