# Generated by Django 4.2.2 on 2023-06-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blocklist', '0031_alter_blocklistsubmission_block_add_changed_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='reason',
            field=models.TextField(
                blank=True,
                help_text='Note this reason will be displayed publicly on the block-addon pages.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='url',
            field=models.CharField(
                blank=True,
                help_text='The URL related to this block, i.e. the bug filed.',
                max_length=255,
                null=True,
            ),
        ),
    ]
