# Generated by Django 4.2.2 on 2023-06-26 10:56

from django.db import migrations, models

def create_waffle_switch_if_it_doesnt_already_exist(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.get_or_create(
        name='reviewer-block-integration',
        defaults={
            'active': False,
            'note': 'Enable block after reject integration in review tools',
        },
    )

class Migration(migrations.Migration):
    dependencies = [
        ('blocklist', '0031_alter_blocklistsubmission_block_add_changed_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklistsubmission',
            name='from_reviewer_tools',
            field=models.BooleanField(
                default=False,
                help_text='When enabled, this submission was created via a reviewer tools '
                'rejection. If this is a delayed submission it will be wait to be published '
                'until after all changed versions are rejected. If the delayed rejection is '
                'cancelled the affected versions will not be blocked.',
            ),
        ),
        migrations.RunPython(create_waffle_switch_if_it_doesnt_already_exist),
    ]
