# Generated by Django 4.2.3 on 2023-07-07 11:45

from django.db import migrations, models
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):
    dependencies = [
        ('blocklist', '0032_alter_blocklistsubmission_reason_url_null_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocklistCannedReason',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('canned_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
