# Generated by Django 4.2.16 on 2024-09-27 08:29

from django.db import migrations, models


def populate_soft_field(apps, schema_editor):
    BlockVersion = apps.get_model('blocklist', 'BlockVersion')
    BlockVersion.objects.filter(hard=False).update(soft=True)


def reverse_populate_soft_field(apps, schema_editor):
    BlockVersion = apps.get_model('blocklist', 'BlockVersion')
    BlockVersion.objects.filter(soft=True).update(hard=False)
    BlockVersion.objects.filter(soft=False).update(hard=True)


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0033_remove_block_max_version_remove_block_min_version_and_more'),
    ]

    operations = [
        # Forward migration operations
        migrations.AddField(
            model_name='blockversion',
            name='soft',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_soft_field, reverse_populate_soft_field),
        migrations.RemoveField(
            model_name='blockversion',
            name='hard',
        ),
    ]
