# Generated by Django 4.2.16 on 2024-10-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0034_remove_blockversion_hard_blockversion_soft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockversion',
            name='soft',
            field=models.BooleanField(choices=[(0, 'Blocked'), (1, 'Soft-Blocked')], default=False),
        ),
    ]
