# Generated by Django 4.2.16 on 2024-10-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0035_alter_blockversion_soft'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklistsubmission',
            name='block_type',
            field=models.IntegerField(choices=[(0, 'Hard-Blocked'), (1, 'Soft-Blocked')], default=0),
        ),
        migrations.AlterField(
            model_name='blockversion',
            name='soft',
            field=models.BooleanField(choices=[(0, 'Hard-Blocked'), (1, 'Soft-Blocked')], default=False),
        ),
    ]
