# Generated by Django 4.2.16 on 2024-10-31 09:55

from django.db import migrations
import olympia.amo.fields

def convert_soft_to_block_type(apps, schema_editor):
    BlockVersion = apps.get_model('blocklist', 'BlockVersion')
    # Update all existing records
    # soft=True -> block_type=1 (Restricted)
    # soft=False -> block_type=0 (Blocked)
    BlockVersion.objects.filter(soft=True).update(block_type=1)
    BlockVersion.objects.filter(soft=False).update(block_type=0)

def convert_block_type_to_soft(apps, schema_editor):
    BlockVersion = apps.get_model('blocklist', 'BlockVersion')
    # Reverse the conversion
    # block_type=1 -> soft=True
    # block_type=0 -> soft=False
    BlockVersion.objects.filter(block_type=1).update(soft=True)
    BlockVersion.objects.filter(block_type=0).update(soft=False)



class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0036_blocklistsubmission_block_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='block_type',
            field=olympia.amo.fields.TinyIntegerField(choices=[(0, 'Blocked'), (1, 'Restricted')], default=0),
        ),
        migrations.AddField(
            model_name='blockversion',
            name='block_type',
            field=olympia.amo.fields.TinyIntegerField(choices=[(0, 'Blocked'), (1, 'Restricted')], default=0),
        ),
        migrations.RunPython(
            convert_soft_to_block_type,
            convert_block_type_to_soft,
        ),
        migrations.RemoveField(
            model_name='blockversion',
            name='soft',
        ),
    ]
