# Generated by Django 4.2.16 on 2024-10-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0036_blocklistsubmission_block_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockversion',
            name='soft',
            field=models.BooleanField(choices=[(0, '🛑 Hard-Blocked'), (1, '⚠️ Soft-Blocked')], default=False),
        ),
    ]
