# Generated by Django 4.2.16 on 2024-11-12 11:24

from django.db import migrations, models
import olympia.amo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0037_alter_blockversion_block_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='action',
            field=models.SmallIntegerField(choices=[(0, 'Add/Change Block'), (1, 'Delete Block'), (2, 'Harden Block'), (3, 'Soften Block')], default=0),
        ),
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='block_type',
            field=olympia.amo.fields.PositiveTinyIntegerField(choices=[(0, '🛑 Hard-Blocked'), (1, '⚠️ Soft-Blocked')], default=0),
        ),
        migrations.AlterField(
            model_name='blockversion',
            name='block_type',
            field=olympia.amo.fields.PositiveTinyIntegerField(choices=[(0, '🛑 Hard-Blocked'), (1, '⚠️ Soft-Blocked')], default=0, null=True),
        ),
    ]
