# Generated by Django 4.2.16 on 2024-11-12 16:06

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0038_tweak_blocksubmission_choices'),
    ]

    operations = [
        CreateWaffleSwitch('enable-soft-blocking'),
    ]
