# Generated by Django 4.2.18 on 2025-01-30 18:51

from django.db import migrations

from olympia.core.db.migrations import DeleteWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0040_remove_blockversion_soft'),
    ]

    operations = [
        DeleteWaffleSwitch('enable-soft-blocking'),
    ]
