# Generated by Django 4.2.24 on 2025-10-01 09:14

from django.db import migrations
import olympia.amo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0041_auto_20250130_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockversion',
            name='block_type',
            field=olympia.amo.fields.PositiveTinyIntegerField(choices=[(0, '🛑 Hard-Blocked'), (1, '⚠️ Soft-Blocked')], default=0),
        ),
    ]
