# Generated by Django 5.2.12 on 2026-04-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0042_alter_blockversion_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklistsubmission',
            name='disable_versions',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='blocklistsubmission',
            name='preserve_block_metadata',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
