# Generated by Django 5.2.13 on 2026-05-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0043_blocklistsubmission_disable_versions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklistsubmission',
            name='auto_block_reason',
            field=models.SmallIntegerField(choices=[(0, 'Addon deleted'), (1, 'Version deleted'), (2, 'This add-on has been blocked because its author has been banned.'), (3, "This add-on violates Mozilla's add-on policies by including or using deceptive, misleading, or fraudulent activity or functionality")], null=True),
        ),
        migrations.AddField(
            model_name='blockversion',
            name='auto_block_reason',
            field=models.SmallIntegerField(choices=[(0, 'Addon deleted'), (1, 'Version deleted'), (2, 'This add-on has been blocked because its author has been banned.'), (3, "This add-on violates Mozilla's add-on policies by including or using deceptive, misleading, or fraudulent activity or functionality")], null=True),
        ),
    ]
