# Generated by Django 5.2.14 on 2026-06-04 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0068_alter_cinderpolicy_status_in_cinder'),
        ('blocklist', '0044_blocklistsubmission_auto_block_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklistsubmission',
            name='from_followup',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abuse.contentdecisionfollowupaction'),
        ),
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='auto_block_reason',
            field=models.SmallIntegerField(choices=[(0, "This add-on violates Mozilla's add-on policies by including or using deceptive, misleading, or fraudulent activity or functionality"), (1, 'This add-on has been blocked because its author has been banned.'), (2, 'Addon deleted'), (3, 'Version deleted')], null=True),
        ),
        migrations.AlterField(
            model_name='blockversion',
            name='auto_block_reason',
            field=models.SmallIntegerField(choices=[(0, "This add-on violates Mozilla's add-on policies by including or using deceptive, misleading, or fraudulent activity or functionality"), (1, 'This add-on has been blocked because its author has been banned.'), (2, 'Addon deleted'), (3, 'Version deleted')], null=True),
        ),
    ]
