# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models
import olympia.hero.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('gradient_color', olympia.hero.models.WidgetCharField(blank=True, choices=[('#054096', 'color-blue-70'), ('#008787', 'color-green-70'), ('#C60084', 'color-pink-70'), ('#722291', 'color-purple-70'), ('#592ACB', 'color-violet-70')], max_length=7)),
                ('description', models.TextField(blank=True, help_text='Text used to describe an add-on. Should not contain any HTML or special tags. Will be translated.')),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('is_external', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrimaryHeroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('custom_image', models.ImageField(storage=olympia.hero.models.hero_image_storage, upload_to=olympia.hero.models.hero_image_directory, verbose_name='custom image path')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SecondaryHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('cta_text', models.CharField(blank=True, max_length=20)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.hero.models.CTACheckMixin, olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SecondaryHeroModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('icon', olympia.hero.models.WidgetCharField(choices=[('Search.svg', 'Search.svg'), ('Tab new.svg', 'Tab new.svg'), ('Video Recorder.svg', 'Video Recorder.svg'), ('Tracking Protection.svg', 'Tracking Protection.svg'), ('Secure.svg', 'Secure.svg'), ('Themes.svg', 'Themes.svg'), ('Subscribe.svg', 'Subscribe.svg'), ('Mail.svg', 'Mail.svg'), ('Download.svg', 'Download.svg'), ('Pin.svg', 'Pin.svg'), ('Store Data.svg', 'Store Data.svg'), ('Login.svg', 'Login.svg'), ('Reader Mode.svg', 'Reader Mode.svg'), ('Private browsing.svg', 'Private browsing.svg'), ('Popular.svg', 'Popular.svg'), ('Save.svg', 'Save.svg'), ('Extensions.svg', 'Extensions.svg'), ('Midi.svg', 'Midi.svg'), ('Play.svg', 'Play.svg'), ('Notification.svg', 'Notification.svg'), ('Device Mobile.svg', 'Device Mobile.svg'), ('Window New.svg', 'Window New.svg'), ('Highlights.svg', 'Highlights.svg'), ('Performance.svg', 'Performance.svg'), ('Dictionaries.svg', 'Dictionaries.svg'), ('Audio.svg', 'Audio.svg'), ('Sync.svg', 'Sync.svg'), ('Trackers Disabled.svg', 'Trackers Disabled.svg'), ('Customize.svg', 'Customize.svg'), ('Globe.svg', 'Globe.svg'), ('Bookmark.svg', 'Bookmark.svg'), ('Help.svg', 'Help.svg'), ('History.svg', 'History.svg'), ('Folder.svg', 'Folder.svg'), ('Bookmark Outline.svg', 'Bookmark Outline.svg'), ('Developer.svg', 'Developer.svg'), ('Accessibility.svg', 'Accessibility.svg')], max_length=255)),
                ('description', models.CharField(max_length=50)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('cta_text', models.CharField(blank=True, max_length=20)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='hero.secondaryhero')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.hero.models.CTACheckMixin, olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='secondaryhero',
            index=olympia.amo.models.LongNameIndex(fields=['enabled'], name='hero_secondaryhero_enabled_1a9ea03c'),
        ),
    ]
