# Generated by Django 2.2.5 on 2019-09-30 15:57

from django.db import migrations
import olympia.hero.models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryhero',
            name='gradient_color',
            field=olympia.hero.models.WidgetCharField(blank=True, choices=[('#054096', 'color-blue-70'), ('#008787', 'color-green-70'), (
                '#C60084', 'color-pink-70'), ('#722291', 'color-purple-70'), ('#592ACB', 'color-violet-70')], max_length=7),
        ),
    ]
