# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hero', '0001_initial'),
        ('promoted', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryhero',
            name='promoted_addon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='promoted.promotedaddon'),
        ),
        migrations.AddField(
            model_name='primaryhero',
            name='select_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hero.primaryheroimage'),
        ),
    ]
