# Generated by Django 2.2.5 on 2019-10-01 07:56

from django.db import migrations
import olympia.hero.models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_auto_20190930_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryheromodule',
            name='icon',
            field=olympia.hero.models.WidgetCharField(choices=[('Accessibility.svg', 'Accessibility.svg'), ('Audio.svg', 'Audio.svg'), ('Bookmark Outline.svg', 'Bookmark Outline.svg'), ('Bookmark.svg', 'Bookmark.svg'), ('Customize.svg', 'Customize.svg'), ('Developer.svg', 'Developer.svg'), ('Device Mobile.svg', 'Device Mobile.svg'), ('Dictionaries.svg', 'Dictionaries.svg'), ('Download.svg', 'Download.svg'), ('Extensions.svg', 'Extensions.svg'), ('Folder.svg', 'Folder.svg'), ('Globe.svg', 'Globe.svg'), ('Help.svg', 'Help.svg'), ('Highlights.svg', 'Highlights.svg'), ('History.svg', 'History.svg'), ('Login.svg', 'Login.svg'), ('Mail.svg', 'Mail.svg'), ('Midi.svg', 'Midi.svg'), (
                'Notification.svg', 'Notification.svg'), ('Performance.svg', 'Performance.svg'), ('Pin.svg', 'Pin.svg'), ('Play.svg', 'Play.svg'), ('Popular.svg', 'Popular.svg'), ('Private browsing.svg', 'Private browsing.svg'), ('Reader Mode.svg', 'Reader Mode.svg'), ('Save.svg', 'Save.svg'), ('Search.svg', 'Search.svg'), ('Secure.svg', 'Secure.svg'), ('Store Data.svg', 'Store Data.svg'), ('Subscribe.svg', 'Subscribe.svg'), ('Sync.svg', 'Sync.svg'), ('Tab new.svg', 'Tab new.svg'), ('Themes.svg', 'Themes.svg'), ('Trackers Disabled.svg', 'Trackers Disabled.svg'), ('Tracking Protection.svg', 'Tracking Protection.svg'), ('Video Recorder.svg', 'Video Recorder.svg'), ('Window New.svg', 'Window New.svg')], max_length=255),
        ),
    ]
