# Generated by Django 2.2.5 on 2019-10-21 08:31

from django.db import migrations
import olympia.hero.models


def blank_removed_featured_images(apps, schema_editor):
    PrimaryHero = apps.get_model('hero', 'PrimaryHero')
    for shelf in PrimaryHero.objects.all():
        if shelf.image:
            shelf.image = ''
            shelf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_auto_20191001_0756'),
    ]

    operations = [
        migrations.RunPython(blank_removed_featured_images),
        migrations.AlterField(
            model_name='primaryhero',
            name='image',
            field=olympia.hero.models.WidgetCharField(blank=True, choices=[('placeholder_a.jpg', 'placeholder_a.jpg'), ('placeholder_b.jpg', 'placeholder_b.jpg')], max_length=255),
        ),
    ]
