# Generated by Django 2.2.6 on 2019-11-27 12:46
from os.path import splitext

from django.db import migrations

import olympia.hero.models


def featured_images_png_to_jpg(apps, schema_editor):
    PrimaryHero = apps.get_model('hero', 'PrimaryHero')
    for shelf in PrimaryHero.objects.filter(image__endswith='.png'):
        new_name = splitext(shelf.image)[0] + '.jpg'
        shelf.update(image=new_name)


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_auto_20191115_1123'),
    ]

    operations = [
        migrations.RunPython(featured_images_png_to_jpg),
        migrations.AlterField(
            model_name='primaryhero',
            name='image',
            field=olympia.hero.models.WidgetCharField(blank=True, choices=[('Adnauseum@2x.jpg', 'Adnauseum@2x.jpg'), ('Dark Reader 2@2x.jpg', 'Dark Reader 2@2x.jpg'), ('Enhancer@2x.jpg', 'Enhancer@2x.jpg'), ('Facetainer@2x.jpg', 'Facetainer@2x.jpg'), ('Gesturefy@2x.jpg', 'Gesturefy@2x.jpg'), ('Ghostery@2x.jpg', 'Ghostery@2x.jpg'), (
                'Google Translate@2x.jpg', 'Google Translate@2x.jpg'), ('Privacy Badger@2x.jpg', 'Privacy Badger@2x.jpg'), ('Search By Image@2x.jpg', 'Search By Image@2x.jpg'), ('Sunset Window.jpg', 'Sunset Window.jpg'), ('Tst1@2x.jpg', 'Tst1@2x.jpg'), ('Typing Laptop@2x.jpg', 'Typing Laptop@2x.jpg'), ('Ubo@2x.jpg', 'Ubo@2x.jpg')], max_length=255),
        ),
    ]
