# Generated by Django 2.2.12 on 2020-06-15 18:04

from django.db import migrations, models
import django.db.models.deletion
import olympia.hero.models


class Migration(migrations.Migration):

    replaces = [('hero', '0007_auto_20200603_0207'), ('hero', '0008_remove_primaryhero_custom_image'), ('hero', '0009_primaryheroimage'), ('hero', '0010_primaryhero_select_image')]

    dependencies = [
        ('hero', '0006_auto_20191127_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryhero',
            name='image',
            field=olympia.hero.models.WidgetCharField(blank=True, choices=[('meagan-carsience-SYJXgaj-jM4-unsplash.jpg', 'meagan-carsience-SYJXgaj-jM4-unsplash.jpg'), ('clarisse-croset--tikpxRBcsA-unsplash.jpg', 'clarisse-croset--tikpxRBcsA-unsplash.jpg'), ('Google Translate@2x.jpg', 'Google Translate@2x.jpg'), ('robynne-hu-HOrhCnQsxnQ-unsplash.jpg', 'robynne-hu-HOrhCnQsxnQ-unsplash.jpg'), ('annie-spratt-dWYU3i-mqEo-unsplash.jpg', 'annie-spratt-dWYU3i-mqEo-unsplash.jpg'), ('Ghostery@2x.jpg', 'Ghostery@2x.jpg'), ('tong-nguyen-van-Ja7Lzg3FckU-unsplash.jpg', 'tong-nguyen-van-Ja7Lzg3FckU-unsplash.jpg'), ('rishi-deep-WiCvC9u7OpE-unsplash.jpg', 'rishi-deep-WiCvC9u7OpE-unsplash.jpg'), ('Gesturefy@2x.jpg', 'Gesturefy@2x.jpg'), ('jonas-denil-VTDm03aGzl4-unsplash.jpg', 'jonas-denil-VTDm03aGzl4-unsplash.jpg'), ('tobias-fischer-PkbZahEG2Ng-unsplash.jpg', 'tobias-fischer-PkbZahEG2Ng-unsplash.jpg'), ('bit-cloud-J5-Kqu_fxyo-unsplash.jpg', 'bit-cloud-J5-Kqu_fxyo-unsplash.jpg'), ('Sunset Window.jpg', 'Sunset Window.jpg'), ('Privacy Badger@2x.jpg', 'Privacy Badger@2x.jpg'), ('david-werbrouck-5GwLlb-_UYk-unsplash.jpg', 'david-werbrouck-5GwLlb-_UYk-unsplash.jpg'), ('kylie-haulk-o9O-wBHfIbs-unsplash.jpg', 'kylie-haulk-o9O-wBHfIbs-unsplash.jpg'), ('rafzin-p-_noVCV8ECj8-unsplash.jpg', 'rafzin-p-_noVCV8ECj8-unsplash.jpg'), ('joshua-sortino-LqKhnDzSF-8-unsplash.jpg', 'joshua-sortino-LqKhnDzSF-8-unsplash.jpg'), ('Facetainer@2x.jpg', 'Facetainer@2x.jpg'), ('heather-barnes-WbZesfqwR-A-unsplash.jpg', 'heather-barnes-WbZesfqwR-A-unsplash.jpg'), ('Ubo@2x.jpg', 'Ubo@2x.jpg'), ('joshua-sortino-R5cIKEopHWI-unsplash.jpg', 'joshua-sortino-R5cIKEopHWI-unsplash.jpg'), ('collins-lesulie-0VEDrQXxrQo-unsplash.jpg', 'collins-lesulie-0VEDrQXxrQo-unsplash.jpg'), ('joshua-coleman-fXls-tVemno-unsplash.jpg', 'joshua-coleman-fXls-tVemno-unsplash.jpg'), ('chuttersnap-aT5-sSYP6e4-unsplash.jpg', 'chuttersnap-aT5-sSYP6e4-unsplash.jpg'), ('drew-graham-53d-jja8Owo-unsplash.jpg', 'drew-graham-53d-jja8Owo-unsplash.jpg'), ('su-san-lee-VFT8W5VfHw8-unsplash.jpg', 'su-san-lee-VFT8W5VfHw8-unsplash.jpg'), ('patrick-perkins-JpStfoIb1wk-unsplash.jpg', 'patrick-perkins-JpStfoIb1wk-unsplash.jpg'), ('yeo-khee-x5JU6lc82EA-unsplash.jpg', 'yeo-khee-x5JU6lc82EA-unsplash.jpg'), ('kobu-agency-7okkFhxrxNw-unsplash.jpg', 'kobu-agency-7okkFhxrxNw-unsplash.jpg'), ('eric-karim-cornelis-UNRpZWL2rSw-unsplash.jpg', 'eric-karim-cornelis-UNRpZWL2rSw-unsplash.jpg'), ('edgar-chaparro-r6mBXuHnxBk-unsplash.jpg', 'edgar-chaparro-r6mBXuHnxBk-unsplash.jpg'), ('rhondak-native-florida-folk-artist-_Yc7OtfFn-0-unsplash.jpg', 'rhondak-native-florida-folk-artist-_Yc7OtfFn-0-unsplash.jpg'), ('Tst1@2x.jpg', 'Tst1@2x.jpg'), ('brooke-cagle-tLG2hcpITZE-unsplash.jpg', 'brooke-cagle-tLG2hcpITZE-unsplash.jpg'), ('Typing Laptop@2x.jpg', 'Typing Laptop@2x.jpg'), ('andre-hunter-Eah5_lljSyg-unsplash.jpg', 'andre-hunter-Eah5_lljSyg-unsplash.jpg'), ('jesus-rocha-ZNOtwtFUvhk-unsplash.jpg', 'jesus-rocha-ZNOtwtFUvhk-unsplash.jpg'), ('carol-magalhaes-eLdK9y0sduI-unsplash.jpg', 'carol-magalhaes-eLdK9y0sduI-unsplash.jpg'), ('Adnauseum@2x.jpg', 'Adnauseum@2x.jpg'), ('massimo-adami-JnqwC6dDL8c-unsplash.jpg', 'massimo-adami-JnqwC6dDL8c-unsplash.jpg'), ('kon-karampelas-peLs78VbU50-unsplash.jpg', 'kon-karampelas-peLs78VbU50-unsplash.jpg'), ('joshua-coleman-FYev7eaTcRE-unsplash.jpg', 'joshua-coleman-FYev7eaTcRE-unsplash.jpg'), ('john-schnobrich-2FPjlAyMQTA-unsplash.jpg', 'john-schnobrich-2FPjlAyMQTA-unsplash.jpg'), ('rod-long-eWc6BKWduMQ-unsplash.jpg', 'rod-long-eWc6BKWduMQ-unsplash.jpg'), ('benjamin-dada-EDZTb2SQ6j0-unsplash.jpg', 'benjamin-dada-EDZTb2SQ6j0-unsplash.jpg'), ('Search By Image@2x.jpg', 'Search By Image@2x.jpg'), ('ev-gpjvRZyavZc-unsplash(1).jpg', 'ev-gpjvRZyavZc-unsplash(1).jpg'), ('sharon-mccutcheon-TZZwC_xsClY-unsplash.jpg', 'sharon-mccutcheon-TZZwC_xsClY-unsplash.jpg'), ('markus-spiske-TaKB-4F58ek-unsplash.jpg', 'markus-spiske-TaKB-4F58ek-unsplash.jpg'), ('Dark Reader 2@2x.jpg', 'Dark Reader 2@2x.jpg'), ('motoki-tonn-GuCdEgE3Gcw-unsplash.jpg', 'motoki-tonn-GuCdEgE3Gcw-unsplash.jpg'), ('nesa-by-makers-IgUR1iX0mqM-unsplash.jpg', 'nesa-by-makers-IgUR1iX0mqM-unsplash.jpg'), ('Enhancer@2x.jpg', 'Enhancer@2x.jpg')], max_length=255),
        ),
        migrations.AlterField(
            model_name='secondaryheromodule',
            name='icon',
            field=olympia.hero.models.WidgetCharField(choices=[('Search.svg', 'Search.svg'), ('Tab new.svg', 'Tab new.svg'), ('Video Recorder.svg', 'Video Recorder.svg'), ('Tracking Protection.svg', 'Tracking Protection.svg'), ('Secure.svg', 'Secure.svg'), ('Themes.svg', 'Themes.svg'), ('Subscribe.svg', 'Subscribe.svg'), ('Mail.svg', 'Mail.svg'), ('Download.svg', 'Download.svg'), ('Pin.svg', 'Pin.svg'), ('Store Data.svg', 'Store Data.svg'), ('Login.svg', 'Login.svg'), ('Reader Mode.svg', 'Reader Mode.svg'), ('Private browsing.svg', 'Private browsing.svg'), ('Popular.svg', 'Popular.svg'), ('Save.svg', 'Save.svg'), ('Extensions.svg', 'Extensions.svg'), ('Midi.svg', 'Midi.svg'), ('Play.svg', 'Play.svg'), ('Notification.svg', 'Notification.svg'), ('Device Mobile.svg', 'Device Mobile.svg'), ('Window New.svg', 'Window New.svg'), ('Highlights.svg', 'Highlights.svg'), ('Performance.svg', 'Performance.svg'), ('Dictionaries.svg', 'Dictionaries.svg'), ('Audio.svg', 'Audio.svg'), ('Sync.svg', 'Sync.svg'), ('Trackers Disabled.svg', 'Trackers Disabled.svg'), ('Customize.svg', 'Customize.svg'), ('Globe.svg', 'Globe.svg'), ('Bookmark.svg', 'Bookmark.svg'), ('Help.svg', 'Help.svg'), ('History.svg', 'History.svg'), ('Folder.svg', 'Folder.svg'), ('Bookmark Outline.svg', 'Bookmark Outline.svg'), ('Developer.svg', 'Developer.svg'), ('Accessibility.svg', 'Accessibility.svg')], max_length=255),
        ),
        migrations.CreateModel(
            name='PrimaryHeroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_image', models.ImageField(blank=True, upload_to='static/img/hero/featured')),
            ],
        ),
        migrations.AddField(
            model_name='primaryhero',
            name='select_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hero.PrimaryHeroImage'),
        ),
    ]
