# Generated by Django 2.2.12 on 2020-06-15 18:04

from django.db import migrations, models
import django.db.models.deletion
import olympia.hero.models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0006_auto_20191127_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryHeroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_image', models.ImageField(blank=True, upload_to='static/img/hero/featured')),
            ],
        ),
        migrations.AddField(
            model_name='primaryhero',
            name='select_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hero.PrimaryHeroImage'),
        ),
    ]
