# Generated by Django 2.2.12 on 2020-06-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_auto_20200603_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryhero',
            name='custom_image',
        ),
    ]
