# Generated by Django 2.2.12 on 2020-06-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0008_remove_primaryhero_custom_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryHeroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_image', models.ImageField(blank=True, upload_to='static/img/hero/featured')),
            ],
        ),
    ]
