# Generated by Django 2.2.12 on 2020-06-12 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0009_primaryheroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryhero',
            name='select_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hero.PrimaryHeroImage'),
        ),
    ]
