# Generated by Django 2.2.14 on 2020-07-27 13:33

from django.db import migrations
import olympia.hero.models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0013_auto_20200715_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryhero',
            name='image',
            field=olympia.hero.models.WidgetCharField(blank=True, max_length=255, null=True),
        ),
    ]
