# Generated by Django 2.2.14 on 2020-07-28 01:54

from django.db import migrations
import olympia.hero.models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0014_auto_20200717_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryhero',
            name='image',
            field=olympia.hero.models.WidgetCharField(blank=True, max_length=255, null=True),
        ),
    ]
