# Generated by Django 2.2.16 on 2020-10-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0015_auto_20200728_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryhero',
            name='disco_addon',
        ),
        migrations.RemoveField(
            model_name='primaryhero',
            name='image',
        ),
    ]
