# Generated by Django 2.2.20 on 2021-05-02 08:27

from django.db import migrations
import olympia.hero.models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0016_auto_20201028_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryheromodule',
            name='icon',
            field=olympia.hero.models.WidgetCharField(choices=[('Private browsing.svg', 'Private browsing.svg'), ('Help.svg', 'Help.svg'), ('Themes.svg', 'Themes.svg'), ('Extensions.svg', 'Extensions.svg'), ('Secure.svg', 'Secure.svg'), ('Save.svg', 'Save.svg'), ('Accessibility.svg', 'Accessibility.svg'), ('Window New.svg', 'Window New.svg'), ('Reader Mode.svg', 'Reader Mode.svg'), ('Sync.svg', 'Sync.svg'), ('Bookmark Outline.svg', 'Bookmark Outline.svg'), ('Performance.svg', 'Performance.svg'), ('Trackers Disabled.svg', 'Trackers Disabled.svg'), ('Login.svg', 'Login.svg'), ('Developer.svg', 'Developer.svg'), ('Highlights.svg', 'Highlights.svg'), ('History.svg', 'History.svg'), ('Store Data.svg', 'Store Data.svg'), ('Tab new.svg', 'Tab new.svg'), ('Mail.svg', 'Mail.svg'), ('Subscribe.svg', 'Subscribe.svg'), ('Midi.svg', 'Midi.svg'), ('Device Mobile.svg', 'Device Mobile.svg'), ('Video Recorder.svg', 'Video Recorder.svg'), ('Download.svg', 'Download.svg'), ('Popular.svg', 'Popular.svg'), ('Globe.svg', 'Globe.svg'), ('Dictionaries.svg', 'Dictionaries.svg'), ('Customize.svg', 'Customize.svg'), ('Folder.svg', 'Folder.svg'), ('Play.svg', 'Play.svg'), ('Search.svg', 'Search.svg'), ('Notification.svg', 'Notification.svg'), ('Tracking Protection.svg', 'Tracking Protection.svg'), ('Audio.svg', 'Audio.svg'), ('Bookmark.svg', 'Bookmark.svg'), ('Pin.svg', 'Pin.svg')], max_length=255),
        ),
    ]
