# Generated by Django 2.2.21 on 2021-05-11 12:56

from django.db import migrations
import olympia.hero.models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0016_auto_20201028_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryheromodule',
            name='icon',
            field=olympia.hero.models.WidgetCharField(choices=[('Notification.svg', 'Notification.svg'), ('Bookmark.svg', 'Bookmark.svg'), ('Tracking Protection.svg', 'Tracking Protection.svg'), ('Private browsing.svg', 'Private browsing.svg'), ('Developer.svg', 'Developer.svg'), ('Accessibility.svg', 'Accessibility.svg'), ('Tab new.svg', 'Tab new.svg'), ('Save.svg', 'Save.svg'), ('Pin.svg', 'Pin.svg'), ('Login.svg', 'Login.svg'), ('Search.svg', 'Search.svg'), ('Subscribe.svg', 'Subscribe.svg'), ('Sync.svg', 'Sync.svg'), ('Device Mobile.svg', 'Device Mobile.svg'), ('Folder.svg', 'Folder.svg'), ('Customize.svg', 'Customize.svg'), ('Trackers Disabled.svg', 'Trackers Disabled.svg'), ('Play.svg', 'Play.svg'), ('Store Data.svg', 'Store Data.svg'), ('Window New.svg', 'Window New.svg'), ('Midi.svg', 'Midi.svg'), ('Popular.svg', 'Popular.svg'), ('Download.svg', 'Download.svg'), ('Mail.svg', 'Mail.svg'), ('Help.svg', 'Help.svg'), ('Dictionaries.svg', 'Dictionaries.svg'), ('Extensions.svg', 'Extensions.svg'), ('Bookmark Outline.svg', 'Bookmark Outline.svg'), ('Globe.svg', 'Globe.svg'), ('Performance.svg', 'Performance.svg'), ('Highlights.svg', 'Highlights.svg'), ('History.svg', 'History.svg'), ('Audio.svg', 'Audio.svg'), ('Secure.svg', 'Secure.svg'), ('Video Recorder.svg', 'Video Recorder.svg'), ('Themes.svg', 'Themes.svg'), ('Reader Mode.svg', 'Reader Mode.svg')], max_length=255),
        ),
    ]
