# Generated by Django 2.2.17 on 2020-11-12 06:02

from django.db import migrations
import olympia.hero.models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0016_auto_20201028_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryheromodule',
            name='icon',
            field=olympia.hero.models.WidgetCharField(choices=[('Video Recorder.svg', 'Video Recorder.svg'), ('Developer.svg', 'Developer.svg'), ('Dictionaries.svg', 'Dictionaries.svg'), ('Highlights.svg', 'Highlights.svg'), ('Tracking Protection.svg', 'Tracking Protection.svg'), ('Folder.svg', 'Folder.svg'), ('Download.svg', 'Download.svg'), ('Store Data.svg', 'Store Data.svg'), ('Help.svg', 'Help.svg'), ('Save.svg', 'Save.svg'), ('Bookmark Outline.svg', 'Bookmark Outline.svg'), ('Search.svg', 'Search.svg'), ('Accessibility.svg', 'Accessibility.svg'), ('Tab new.svg', 'Tab new.svg'), ('Sync.svg', 'Sync.svg'), ('Bookmark.svg', 'Bookmark.svg'), ('Trackers Disabled.svg', 'Trackers Disabled.svg'), ('Customize.svg', 'Customize.svg'), ('Secure.svg', 'Secure.svg'), ('Globe.svg', 'Globe.svg'), ('Device Mobile.svg', 'Device Mobile.svg'), ('Window New.svg', 'Window New.svg'), ('Popular.svg', 'Popular.svg'), ('Reader Mode.svg', 'Reader Mode.svg'), ('Mail.svg', 'Mail.svg'), ('History.svg', 'History.svg'), ('Extensions.svg', 'Extensions.svg'), ('Private browsing.svg', 'Private browsing.svg'), ('Login.svg', 'Login.svg'), ('Themes.svg', 'Themes.svg'), ('Play.svg', 'Play.svg'), ('Performance.svg', 'Performance.svg'), ('Audio.svg', 'Audio.svg'), ('Pin.svg', 'Pin.svg'), ('Notification.svg', 'Notification.svg'), ('Subscribe.svg', 'Subscribe.svg'), ('Midi.svg', 'Midi.svg')], max_length=255),
        ),
    ]
