# Generated by Django 3.2.13 on 2022-05-30 16:39

from django.db import migrations, models
import olympia.hero.models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0017_auto_20210511_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryheroimage',
            name='custom_image',
            field=models.ImageField(storage=olympia.hero.models.hero_image_storage, upload_to=olympia.hero.models.hero_image_directory, verbose_name='custom image path'),
        ),
    ]
