# Generated by Django 3.2.15 on 2022-12-14 13:31

from django.db import migrations
import olympia.hero.models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0018_alter_primaryheroimage_custom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryheromodule',
            name='icon',
            field=olympia.hero.models.WidgetCharField(choices=[('Search.svg', 'Search.svg'), ('Tab new.svg', 'Tab new.svg'), ('Video Recorder.svg', 'Video Recorder.svg'), ('Tracking Protection.svg', 'Tracking Protection.svg'), ('Secure.svg', 'Secure.svg'), ('Themes.svg', 'Themes.svg'), ('Subscribe.svg', 'Subscribe.svg'), ('Mail.svg', 'Mail.svg'), ('Download.svg', 'Download.svg'), ('Pin.svg', 'Pin.svg'), ('Store Data.svg', 'Store Data.svg'), ('Login.svg', 'Login.svg'), ('Reader Mode.svg', 'Reader Mode.svg'), ('Private browsing.svg', 'Private browsing.svg'), ('Popular.svg', 'Popular.svg'), ('Save.svg', 'Save.svg'), ('Extensions.svg', 'Extensions.svg'), ('Midi.svg', 'Midi.svg'), ('Play.svg', 'Play.svg'), ('Notification.svg', 'Notification.svg'), ('Device Mobile.svg', 'Device Mobile.svg'), ('Window New.svg', 'Window New.svg'), ('Highlights.svg', 'Highlights.svg'), ('Performance.svg', 'Performance.svg'), ('Dictionaries.svg', 'Dictionaries.svg'), ('Audio.svg', 'Audio.svg'), ('Sync.svg', 'Sync.svg'), ('Trackers Disabled.svg', 'Trackers Disabled.svg'), ('Customize.svg', 'Customize.svg'), ('Globe.svg', 'Globe.svg'), ('Bookmark.svg', 'Bookmark.svg'), ('Help.svg', 'Help.svg'), ('History.svg', 'History.svg'), ('Folder.svg', 'Folder.svg'), ('Bookmark Outline.svg', 'Bookmark Outline.svg'), ('Developer.svg', 'Developer.svg'), ('Accessibility.svg', 'Accessibility.svg')], max_length=255),
        ),
    ]
