# Generated by Django 4.2.20 on 2025-03-25 19:03

from django.db import migrations, models
import django.db.models.deletion

def copy_over_promotions(apps, schema_editor):
    PromotedGroup = apps.get_model('promoted', 'PromotedGroup')
    Hero = apps.get_model('hero', 'PrimaryHero')
    for hero in Hero.objects.all():
        hero.addon = hero.promoted_addon.addon
        hero.promoted_group = PromotedGroup.objects.get(group_id=hero.promoted_addon.group.id)
        hero.save()

class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0023_promotedgroup_alter_promotedaddon_group_id_and_more'),
        ('addons', '0054_update_default_locale_es_to_es-es'),
        ('hero', '0019_alter_secondaryheromodule_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryhero',
            name='promoted_addon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='promoted.promotedaddon'),
        ),
        migrations.AddField(
            model_name='primaryhero',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons.addon', null=True),
        ),
        migrations.AddField(
            model_name='primaryhero',
            name='promoted_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promoted.promotedgroup'),
        ),
        migrations.RunPython(copy_over_promotions),
    ]
