# Generated by Django 4.2.20 on 2025-04-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0020_primaryhero_addon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryhero',
            name='promoted_addon',
        ),
    ]
