# Generated by Django 4.2.20 on 2025-04-29 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0054_update_default_locale_es_to_es-es'),
        ('hero', '0020_primaryhero_addon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryhero',
            name='promoted_addon',
        ),
        migrations.AlterField(
            model_name='primaryhero',
            name='addon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='addons.addon'),
        ),
    ]
