# Generated by Django 4.2.20 on 2025-03-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0054_update_default_locale_es_to_es-es'),
        ('hero', '0020_primaryhero_addon_primaryhero_promoted_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryhero',
            name='promoted_addon',
        ),
        migrations.AlterField(
            model_name='primaryhero',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons.addon'),
        ),
        migrations.AddConstraint(
            model_name='primaryhero',
            constraint=models.UniqueConstraint(condition=models.Q(('promoted_group__isnull', False)), fields=('addon', 'promoted_group'), name='unique_addon_promoted_group'),
        ),
    ]
