# Generated by Django 4.2.24 on 2025-10-01 09:14

from django.db import migrations
import olympia.hero.models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0021_remove_primaryhero_promoted_addon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryheromodule',
            name='icon',
            field=olympia.hero.models.WidgetCharField(choices=[('Mail.svg', 'Mail.svg'), ('Extensions.svg', 'Extensions.svg'), ('Dictionaries.svg', 'Dictionaries.svg'), ('Private browsing.svg', 'Private browsing.svg'), ('Save.svg', 'Save.svg'), ('Folder.svg', 'Folder.svg'), ('Highlights.svg', 'Highlights.svg'), ('Bookmark Outline.svg', 'Bookmark Outline.svg'), ('Sync.svg', 'Sync.svg'), ('Tracking Protection.svg', 'Tracking Protection.svg'), ('Developer.svg', 'Developer.svg'), ('Secure.svg', 'Secure.svg'), ('Help.svg', 'Help.svg'), ('Window New.svg', 'Window New.svg'), ('Subscribe.svg', 'Subscribe.svg'), ('Audio.svg', 'Audio.svg'), ('Popular.svg', 'Popular.svg'), ('Bookmark.svg', 'Bookmark.svg'), ('Performance.svg', 'Performance.svg'), ('Search.svg', 'Search.svg'), ('Play.svg', 'Play.svg'), ('Reader Mode.svg', 'Reader Mode.svg'), ('Accessibility.svg', 'Accessibility.svg'), ('Customize.svg', 'Customize.svg'), ('Tab new.svg', 'Tab new.svg'), ('Notification.svg', 'Notification.svg'), ('Download.svg', 'Download.svg'), ('Device Mobile.svg', 'Device Mobile.svg'), ('Pin.svg', 'Pin.svg'), ('Store Data.svg', 'Store Data.svg'), ('Trackers Disabled.svg', 'Trackers Disabled.svg'), ('Login.svg', 'Login.svg'), ('Globe.svg', 'Globe.svg'), ('History.svg', 'History.svg'), ('Midi.svg', 'Midi.svg'), ('Video Recorder.svg', 'Video Recorder.svg'), ('Themes.svg', 'Themes.svg')], max_length=255),
        ),
    ]
