# Generated by Django 2.2.12 on 2020-04-20 15:25

from django.db import migrations


def create_waffle_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.create(
        name='enable-git-extraction-cron',
        active=False,
        note='Perform git extraction with a CRON task instead of at submission',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0001_initial'),
        # This is needed otherwise `apps.get_model('waffle', 'Switch')` will
        # raise a Django app LookupError.
        ('waffle', '0001_initial'),
    ]

    operations = [migrations.RunPython(create_waffle_switch)]
