# Generated by Django 2.2.12 on 2020-04-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0002_auto_20200420_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitextractionentry',
            options={'base_manager_name': 'objects', 'get_latest_by': 'created', 'verbose_name_plural': 'Git extraction entries'},
        ),
    ]
