# Generated by Django 2.2.12 on 2020-04-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('git', '0002_gitextractionqueue')]

    operations = [
        migrations.RenameModel(
            old_name='GitExtraction', new_name='AddonGitExtraction'
        )
    ]
