# Generated by Django 2.2.12 on 2020-04-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('git', '0003_auto_20200420_1419')]

    operations = [
        migrations.RenameModel(
            old_name='GitExtractionQueue', new_name='GitExtractionEntry'
        )
    ]
