# Generated by Django 2.2.21 on 2021-05-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0003_auto_20200427_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitextractionentry',
            name='in_progress',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
