# Generated by Django 3.2.11 on 2022-02-25 11:41

from django.db import migrations


def create_waffle_switch_if_it_doesnt_already_exist(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.get_or_create(
        name='git-storage-deeper-structure',
        defaults={
            'active': False,
            'note': 'Enable deeper directory structure for git storage',
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0004_auto_20210511_1256'),
    ]

    operations = [
        migrations.RunPython(create_waffle_switch_if_it_doesnt_already_exist),
    ]
