# Generated by Django 3.2.12 on 2022-04-12 11:44

from django.db import migrations


def delete_waffle_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.filter(name='git-storage-broader-structure').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0005_auto_20220225_1141'),
    ]

    operations = [migrations.RunPython(delete_waffle_switch)]
