# Generated by Django 3.2.12 on 2022-04-12 11:44

from django.db import migrations
from olympia.core.db.migrations import DeleteWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0005_auto_20220225_1141'),
    ]

    operations = [DeleteWaffleSwitch('git-storage-broader-structure')]
