# Generated by Django 4.2.24 on 2025-10-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0006_auto_20220412_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GitExtractionEntry',
        ),
    ]
