# Generated by Django 4.2.21 on 2025-05-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0006_auto_20220412_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GitExtractionEntry',
        ),
    ]
