# Generated by Django 2.2.6 on 2019-11-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0002_autoapprovalsummary_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoapprovalsummary',
            name='is_listing_disabled',
            field=models.NullBooleanField(
                default=None, help_text='Has incomplete or disabled listing'),
        ),
    ]
