# Generated by Django 2.2.6 on 2019-11-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0003_autoapprovalsummary_is_listing_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoapprovalsummary',
            name='is_listing_disabled',
        ),
    ]
