# Generated by Django 2.2.12 on 2020-06-02 13:28

from django.db import migrations


def delete_waffle_flag(apps, schema_editor):
    Flag = apps.get_model('waffle', 'Flag')

    Flag.objects.filter(name='code-manager').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0004_remove_autoapprovalsummary_is_listing_disabled'),
    ]

    operations = [migrations.RunPython(delete_waffle_flag)]
