# Generated by Django 2.2.13 on 2020-06-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0005_remove_code_manager_waffle_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoapprovalsummary',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Version string and guid match a blocklist Block'),
        ),
        migrations.AlterField(
            model_name='autoapprovalsummary',
            name='has_auto_approval_disabled',
            field=models.BooleanField(default=False, help_text='Has auto-approval disabled/delayed flag set'),
        ),
    ]
