# Generated by Django 2.2.14 on 2020-07-30 13:35

from django.db import migrations, models


def replace_is_recommended_with_promoted(apps, schema_editor):
    AutoApprovalSummary = apps.get_model('reviewers', 'AutoApprovalSummary')
    AutoApprovalSummary.objects.all().update(
        is_promoted_prereview=models.F('is_recommendable'))


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0007_auto_20200730_1335'),
    ]

    operations = [
        migrations.RunPython(replace_is_recommended_with_promoted)
    ]
