# Generated by Django 2.2.16 on 2020-09-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0008_auto_20200730_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoapprovalsummary',
            name='weight_info',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
