# Generated by Django 2.2.16 on 2020-09-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0008_auto_20200730_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewersubscription',
            name='channel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unlisted'), (2, 'Listed')], default=2),
            preserve_default=False,
        ),
    ]
