# Generated by Django 2.2.16 on 2020-10-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0010_add_subscription_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoapprovalsummary',
            name='is_recommendable',
        ),
        migrations.AlterField(
            model_name='autoapprovalsummary',
            name='is_promoted_prereview',
            field=models.BooleanField(default=False, help_text='Is in a promoted addon group that requires pre-review', null=True),
        ),
    ]
