# Generated by Django 2.2.17 on 2021-01-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0011_auto_20201028_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoapprovalsummary',
            name='score',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
