# Generated by Django 2.2.17 on 2021-01-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0012_autoapprovalsummary_score'),
        # Need a recent enough migration to have score and version in ScannerResult
        ('scanners', '0037_auto_20200717_1233'),
        ('addons', '0002_addon_fk'),  # Need addon___current_version to exist
    ]

    operations = [
        # MAD scanner was removed, so no-op this migration
    ]
