# Generated by Django 2.2.17 on 2021-01-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0013_backfill_autoapprovalsummary_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoapprovalsummary',
            name='code_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autoapprovalsummary',
            name='metadata_weight',
            field=models.IntegerField(default=0),
        ),
    ]
