# Generated by Django 2.2.21 on 2021-05-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0014_auto_20210120_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoapprovalsummary',
            name='confirmed',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
