# Generated by Django 3.2.8 on 2021-11-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0016_reviewactionreason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewactionreason',
            options={'ordering': ('name',)},
        ),
    ]
