# Generated by Django 3.2.13 on 2022-05-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0017_alter_reviewactionreason_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoapprovalsummary',
            name='is_promoted_prereview',
            field=models.BooleanField(default=False, help_text='Is in a promoted add-on group that requires pre-review', null=True),
        ),
    ]
