# Generated by Django 3.2.16 on 2022-10-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0018_alter_autoapprovalsummary_is_promoted_prereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewactionreason',
            name='canned_response',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
