# Generated by Django 3.2.16 on 2022-11-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0019_reviewactionreason_canned_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewactionreason',
            name='addon_type',
            field=models.PositiveIntegerField(choices=[(0, 'All'), (1, 'Extension'), (10, 'Theme')], default=0),
        ),
    ]
