# Generated by Django 3.2.16 on 2022-12-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0020_auto_20221114_1835'),
        ('reviewers', '0020_reviewactionreason_addon_type'),
    ]

    operations = [
    ]
