# Generated by Django 3.2.16 on 2023-01-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0021_merge_20221205_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewactionreason',
            name='canned_response',
            field=models.TextField(blank=True),
        ),
    ]
