# Generated by Django 3.2.16 on 2023-01-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0022_alter_reviewactionreason_canned_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewerScore',
        ),
    ]
