# Generated by Django 3.2.18 on 2023-05-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviewers', '0025_needshumanreviewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='needshumanreview',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='needshumanreview',
            name='reason',
            field=models.SmallIntegerField(
                choices=[
                    (0, 'Unknown'),
                    (1, 'Hit scanner rule'),
                    (2, 'Belongs to a promoted group'),
                    (3, 'Over growth treshold for usage tier'),
                    (4, 'Previous version in channel had needs human review set'),
                    (5, 'Sources provided while pending rejection'),
                    (6, 'Developer replied'),
                    (7, 'Manually set as needing human review by a reviewer'),
                    (
                        8,
                        'Auto-approved but still had an approval delay set in the past',
                    ),
                ],
                default=0,
                editable=False,
            ),
        ),
    ]
