# Generated by Django 3.2.18 on 2023-05-17 19:44

from django.db import migrations, models
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):
    dependencies = [
        ('reviewers', '0027_backfill_needshumanreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageTier',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('lower_adu_threshold', models.IntegerField(default=None, null=True)),
                ('upper_adu_threshold', models.IntegerField(default=None, null=True)),
                (
                    'growth_threshold_before_flagging',
                    models.IntegerField(
                        default=None,
                        null=True,
                        help_text='Usage growth percentage threshold before we start automatically flagging the add-on for human review.',
                    ),
                ),
            ],
            options={
                'ordering': ('upper_adu_threshold',),
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
