# Generated by Django 3.2.18 on 2023-06-06 17:08

from django.db import migrations, models
from olympia.amo.utils import slugify


class Migration(migrations.Migration):
    dependencies = [
        ('reviewers', '0028_usagetier'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagetier',
            name='slug',
            field=models.CharField(
                help_text='Slug to help retrieve the UsageTier instance in our code.',
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='usagetier',
            name='growth_threshold_before_flagging',
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text='Usage growth percentage threshold before we start automatically flagging the add-on for human review.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='usagetier',
            name='lower_adu_threshold',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usagetier',
            name='upper_adu_threshold',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
