# Generated by Django 3.2.18 on 2023-06-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0029_auto_20230606_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagetier',
            name='abuse_reports_ratio_threshold_before_flagging',
            field=models.IntegerField(blank=True, default=None, help_text='Percentage threshold of ratio between abuse reports over the past 2 weeks to add-on usage before we start automatically flagging the add-on for human review.', null=True),
        ),
        migrations.AlterField(
            model_name='needshumanreview',
            name='reason',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Hit scanner rule'), (2, 'Belongs to a promoted group'), (3, 'Over growth threshold for usage tier'), (4, 'Previous version in channel had needs human review set'), (5, 'Sources provided while pending rejection'), (6, 'Developer replied'), (7, 'Manually set as needing human review by a reviewer'), (8, 'Auto-approved but still had an approval delay set in the past'), (9, 'Over abuse reports threshold for usage tier')], default=0, editable=False),
        ),
    ]
