# Generated by Django 4.2.8 on 2024-01-02 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0032_alter_needshumanreview_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewactionreason',
            name='cinder_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abuse.cinderpolicy'),
        ),
    ]
