# Generated by Django 4.2.9 on 2024-02-16 12:01

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):
    dependencies = [
        ("reviewers", "0033_reviewactionreason_cinder_policy"),
    ]

    operations = [
        CreateWaffleSwitch('enable-cinder-reviewer-tools-integration')
    ]
