# Generated by Django 4.2.9 on 2024-02-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("abuse", "0025_cinderjob_resolvable_in_reviewer_tools_and_more"),
        ("reviewers", "0034_create-specific-cinder-switch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewactionreason",
            name="cinder_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="abuse.cinderpolicy",
            ),
        ),
    ]
