# Generated by Django 4.2.15 on 2024-09-09 16:47

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0037_autoapprovalsummary_is_pending_rejection'),
    ]

    operations = [
        CreateWaffleSwitch('enable-activity-log-attachments')
    ]