# Generated by Django 4.2.16 on 2024-12-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0038_auto_20240909_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoapprovalsummary',
            name='verdict',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Would *not* have been auto-approved (dry-run mode was in effect)'), (1, 'Would have been auto-approved (dry-run mode was in effect)'), (2, 'Was auto-approved'), (3, 'Was *not* auto-approved')], default=3),
        ),
        migrations.AlterField(
            model_name='needshumanreview',
            name='reason',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Hit scanner rule'), (2, 'Was added to a promoted group'), (3, 'Over growth threshold for usage tier'), (4, 'Previous version in channel had needs human review set'), (5, 'Sources provided while pending rejection'), (6, 'Developer replied'), (7, 'Manually set as needing human review by a reviewer'), (8, 'Auto-approved but still had an approval delay set in the past'), (9, 'Over abuse reports threshold for usage tier'), (10, 'Escalated for an abuse report, via cinder'), (11, 'Reported for abuse within the add-on'), (12, "Appeal of a reviewer's decision about a policy violation"), (13, 'Has auto-approval disabled'), (14, 'Belongs to a promoted group')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='usagetier',
            name='growth_threshold_before_flagging',
            field=models.IntegerField(blank=True, default=None, help_text='Percentage point increase in growth over the average in that tier before we start automatically flagging the add-on for human review. For example, if set to 50 and the average hotness in that tier is 0.01, add-ons over 0.51 hotness get flagged.', null=True),
        ),
    ]
