# Generated by Django 4.2.16 on 2024-12-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0039_alter_autoapprovalsummary_verdict_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='queuecount',
            constraint=models.UniqueConstraint(fields=('name', 'date'), name='queue_count_unique_name_date'),
        ),
    ]
