# Generated by Django 4.2.17 on 2024-12-10 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0027_alter_activitylog_action'),
        ('versions', '0047_auto_20241031_1750'),
        ('reviewers', '0040_queuecount_queuecount_queue_count_unique_name_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewQueueHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('original_due_date', models.DateTimeField(help_text='Original due date when the version entered the queue')),
                ('exit_date', models.DateTimeField(blank=True, default=None, help_text='When the version left the queue (regardless of reason)', null=True)),
                ('review_decision_log', models.ForeignKey(blank=True, help_text='Activity Log associated with the reviewer decision that caused the version to leave the queue', null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activitylog')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versions.version')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
