# Generated by Django 4.2.20 on 2025-05-08 17:31

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0042_alter_needshumanreview_reason'),
    ]

    operations = [
        CreateWaffleSwitch('cinder_policy_review_reasons_enabled')
    ]
