# Generated by Django 4.2.21 on 2025-05-15 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0043_alter_needshumanreview_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuecount',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='queuecount',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
