# Generated by Django 4.2.23 on 2025-08-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0043_auto_20250508_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagetier',
            name='abuse_reports_ratio_threshold_before_blocking',
            field=models.IntegerField(blank=True, default=None, help_text='Percentage threshold of ratio between non individually actionable abuse reports over the past 2 weeks to add-on usage before we automatically disable the add-on. For example, if set to 4 and an add-on in that tier has 10,000 users, it will be disabled after 400 reports.', null=True),
        ),
        migrations.AddField(
            model_name='usagetier',
            name='ratings_ratio_threshold_before_blocking',
            field=models.IntegerField(blank=True, default=None, help_text='Percentage threshold of ratio between ratings over the past 2 weeksto add-on usage before we automatically disable the add-on. For example, if set to 5 and an add-on in that tier has 10,000 users, it will be disabled after 500 ratings.', null=True),
        ),
        migrations.AddField(
            model_name='usagetier',
            name='ratings_ratio_threshold_before_flagging',
            field=models.IntegerField(blank=True, default=None, help_text='Percentage threshold of ratio between ratings over the past 2 weeksto add-on usage before we start automatically flagging the add-on for human review. For example, if set to 5 and an add-on in that tier has 10,000 users, it will be flagged after 500 ratings.', null=True),
        ),
        migrations.AlterField(
            model_name='needshumanreview',
            name='reason',
            field=models.SmallIntegerField(choices=[(14, 'Belongs to a promoted group'), (2, 'Was added to a promoted group'), (6, 'Developer replied'), (10, 'Escalated for an abuse report, via cinder'), (11, 'Reported for abuse within the add-on'), (12, "Appeal of a reviewer's decision about a policy violation"), (15, 'Escalated appeal via cinder'), (16, 'Re-enqueued in reviewer tools from 2nd level approval'), (9, 'Over abuse reports threshold for usage tier'), (17, 'Over ratings threshold for usage tier'), (5, 'Sources provided while pending rejection'), (13, 'Has auto-approval disabled'), (1, 'Hit scanner rule'), (3, 'Over growth threshold for usage tier'), (4, 'Previous version in channel had needs human review set'), (7, 'Manually set as needing human review by a reviewer'), (8, 'Auto-approved but still had an approval delay set in the past'), (0, 'Unknown')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='usagetier',
            name='abuse_reports_ratio_threshold_before_flagging',
            field=models.IntegerField(blank=True, default=None, help_text='Percentage threshold of ratio between non individually actionable abuse reports over the past 2 weeks to add-on usage before we start automatically flagging the add-on for human review. For example, if set to 2 and an add-on in that tier has 10,000 users, it will be flagged after 200 reports.', null=True),
        ),
    ]
