# Generated by Django 4.2.23 on 2025-08-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0044_usagetier_abuse_reports_ratio_threshold_before_disabling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagetier',
            name='disable_and_block_action_available',
            field=models.BooleanField(default=False, help_text='Whether or not the "Force-disable and block" scanner action shouldbe available for add-ons belonging to that usage tier.', null=True),
        ),
        migrations.AlterField(
            model_name='usagetier',
            name='abuse_reports_ratio_threshold_before_blocking',
            field=models.IntegerField(blank=True, default=None, help_text='Percentage threshold of ratio between non individually actionable abuse reports over the past 2 weeks to add-on usage before we automatically disable and soft-block the add-on. For example, if set to 4 and an add-on in that tier has 10,000 users, it will be blocked after 400 reports.', null=True),
        ),
        migrations.AlterField(
            model_name='usagetier',
            name='ratings_ratio_threshold_before_blocking',
            field=models.IntegerField(blank=True, default=None, help_text='Percentage threshold of ratio between ratings over the past 2 weeksto add-on usage before we automatically disable and soft-block the add-on. For example, if set to 5 and an add-on in that tier has 10,000 users, it will be blocked after 500 ratings.', null=True),
        ),
    ]
