# Generated by Django 4.2.24 on 2025-10-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0045_usagetier_disable_and_block_action_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needshumanreview',
            name='reason',
            field=models.SmallIntegerField(choices=[(14, 'Belongs to a promoted group'), (2, 'Was added to a promoted group'), (6, 'Developer replied'), (10, 'Escalated for an abuse report, via cinder'), (11, 'Reported for abuse within the add-on'), (12, "Appeal of a reviewer's decision about a policy violation"), (15, 'Escalated appeal via cinder'), (16, 'Re-enqueued in reviewer tools from 2nd level approval'), (9, 'Over abuse reports threshold for usage tier'), (17, 'Over ratings threshold for usage tier'), (5, 'Sources provided while pending rejection'), (13, 'Has auto-approval disabled'), (1, 'Hit scanner rule'), (3, 'Over growth threshold for usage tier'), (4, 'Previous version in channel had needs human review set'), (7, 'Manually set as needing human review by a reviewer'), (8, 'Auto-approved but still had an approval delay set in the past'), (18, 'Rollback to a previous version that was unreviewed'), (0, 'Unknown')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='usagetier',
            name='disable_and_block_action_available',
            field=models.BooleanField(default=False, help_text='Whether or not the "Force-disable and block" scanner action shouldbe available for add-ons belonging to that usage tier.'),
        ),
    ]
