# Generated by Django 4.2.25 on 2025-10-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0046_alter_needshumanreview_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoapprovalsummary',
            name='score',
        ),
    ]
