# Generated by Django 4.2.27 on 2026-01-29 10:17

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0047_remove_autoapprovalsummary_score'),
    ]

    operations = [
        CreateWaffleSwitch(name='enable-content-rejection')
    ]
