# Generated by Django 4.2.28 on 2026-02-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0048_add_content_rejection_enabled_waffle'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoapprovalsummary',
            name='is_waiting_on_scanners',
            field=models.BooleanField(
                default=False, help_text='Is waiting on scanners'
            ),
        ),
    ]
