# Generated by Django 5.2.14 on 2026-05-26 11:39

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0049_autoapprovalsummary_is_waiting_on_scanners'),
    ]

    operations = [
        CreateWaffleSwitch('enable-policy-review-selection'),
    ]
