# Generated by Django 5.2.16 on 2026-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0050_add_enable_policy_review_selection_switch'),
    ]

    operations = [
        # No default, so that existing rows are left to NULL: that's how we
        # tell the summaries that predate this field apart from the new ones.
        migrations.AddField(
            model_name='autoapprovalsummary',
            name='scanner_actions_executed',
            field=models.BooleanField(
                help_text='Scanner actions have been executed', null=True
            ),
        ),
        # AlterField doesn't backfill, so the default applies to new rows only.
        migrations.AlterField(
            model_name='autoapprovalsummary',
            name='scanner_actions_executed',
            field=models.BooleanField(
                default=False, help_text='Scanner actions have been executed', null=True
            ),
        ),
        migrations.AlterField(
            model_name='autoapprovalsummary',
            name='is_promoted_prereview',
            field=models.BooleanField(
                default=False,
                help_text='Is in a promoted add-on group that requires pre-review',
            ),
        ),
        migrations.AlterField(
            model_name='needshumanreview',
            name='reason',
            field=models.SmallIntegerField(
                choices=[
                    (14, 'Belongs to a promoted group'),
                    (2, 'Was added to a promoted group'),
                    (6, 'Developer replied'),
                    (10, 'Escalated for an abuse report, via cinder'),
                    (11, 'Reported for abuse within the add-on'),
                    (12, "Appeal of a reviewer's decision about a policy violation"),
                    (15, 'Escalated appeal via cinder'),
                    (16, 'Re-enqueued in reviewer tools from 2nd level approval'),
                    (9, 'Over abuse reports threshold for usage tier'),
                    (17, 'Over ratings threshold for usage tier'),
                    (5, 'Sources provided while pending rejection'),
                    (13, 'Has auto-approval disabled'),
                    (1, 'Hit scanner rule'),
                    (3, 'Over growth threshold for usage tier'),
                    (4, 'Previous version in channel had needs human review set'),
                    (7, 'Manually set as needing human review by a reviewer'),
                    (
                        8,
                        'Auto-approved but still had an approval delay set in the past',
                    ),
                    (18, 'Rollback to a previous version that was unreviewed'),
                    (19, 'Some scanners have not returned results yet'),
                    (0, 'Unknown'),
                ],
                default=0,
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name='reviewersubscription',
            name='channel',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Unlisted'), (2, 'Listed'), (3, 'Enterprise')]
            ),
        ),
    ]
