# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('versions', '0001_initial'),
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ScannerRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='This is the exact name of the rule used by a scanner.', max_length=200)),
                ('pretty_name', models.CharField(blank=True, default='', help_text='Human-readable name for the scanner rule', max_length=255, verbose_name='Human-readable name')),
                ('description', models.CharField(blank=True, default='', help_text='Human readable description for the scanner rule', max_length=255)),
                ('scanner', models.PositiveSmallIntegerField(choices=[(1, 'customs'), (2, 'wat'), (3, 'yara'), (4, 'mad')])),
                ('definition', models.TextField(blank=True, null=True)),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'No action'), (20, 'Flag for human review'), (100, 'Delay auto-approval'), (200, 'Delay auto-approval indefinitely'), (300, 'Delay auto-approval indefinitely and add restrictions'), (400, 'Delay auto-approval indefinitely and add restrictions to future approvals')], default=1)),
                ('is_active', models.BooleanField(default=True, help_text='When unchecked, the scanner results will not be bound to this rule and the action will not be executed.')),
            ],
            options={
                'db_table': 'scanners_rules',
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
                'unique_together': {('name', 'scanner')},
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ScannerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('results', models.JSONField(default=list)),
                ('scanner', models.PositiveSmallIntegerField(choices=[(1, 'customs'), (2, 'wat'), (3, 'yara'), (4, 'mad')])),
                ('score', models.DecimalField(blank=True, decimal_places=5, default=-1, max_digits=6, null=True)),
                ('model_version', models.CharField(max_length=30, null=True)),
                ('has_matches', models.BooleanField(null=True)),
                ('state', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Unknown'), (1, 'True positive'), (2, 'False positive'), (3, 'Inconclusive')], default=None, null=True)),
                ('matched_rules', models.ManyToManyField(related_name='results', through='scanners.ScannerMatch', to='scanners.scannerrule')),
                ('upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='files.fileupload')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='versions.version')),
            ],
            options={
                'db_table': 'scanners_results',
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ScannerQueryRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='This is the exact name of the rule used by a scanner.', max_length=200)),
                ('pretty_name', models.CharField(blank=True, default='', help_text='Human-readable name for the scanner rule', max_length=255, verbose_name='Human-readable name')),
                ('description', models.CharField(blank=True, default='', help_text='Human readable description for the scanner rule', max_length=255)),
                ('definition', models.TextField(blank=True, null=True)),
                ('scanner', models.PositiveSmallIntegerField(choices=[(3, 'yara')], default=3)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Running'), (3, 'Aborted'), (5, 'Aborting'), (4, 'Completed'), (6, 'Scheduled')], default=1)),
                ('run_on_disabled_addons', models.BooleanField(default=False, help_text='Run this rule on add-ons that have been force-disabled as well.')),
                ('celery_group_result_id', models.UUIDField(default=None, null=True)),
                ('task_count', models.PositiveIntegerField(default=0)),
                ('completed', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'scanners_query_rules',
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
                'unique_together': {('name', 'scanner')},
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ScannerQueryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('results', models.JSONField(default=list)),
                ('scanner', models.PositiveSmallIntegerField(choices=[(1, 'customs'), (2, 'wat'), (3, 'yara'), (4, 'mad')])),
                ('was_blocked', models.BooleanField(default=None, null=True)),
                ('matched_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scanners.scannerqueryrule')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='versions.version')),
            ],
            options={
                'db_table': 'scanners_query_results',
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.AddField(
            model_name='scannermatch',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanners.scannerresult'),
        ),
        migrations.AddField(
            model_name='scannermatch',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanners.scannerrule'),
        ),
        migrations.AddIndex(
            model_name='scannerresult',
            index=models.Index(fields=['state'], name='scanners_re_state_2893a0_idx'),
        ),
        migrations.AddIndex(
            model_name='scannerresult',
            index=models.Index(fields=['has_matches'], name='scanners_re_has_mat_d3421d_idx'),
        ),
        migrations.AddConstraint(
            model_name='scannerresult',
            constraint=models.UniqueConstraint(fields=('upload', 'scanner', 'version'), name='scanners_results_upload_id_scanner_version_id_ad9eb8a6_uniq'),
        ),
        migrations.AddIndex(
            model_name='scannerqueryresult',
            index=models.Index(fields=['was_blocked'], name='scanners_qu_was_blo_7eec1c_idx'),
        ),
    ]
