# Generated by Django 2.2.6 on 2019-10-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0001_initial'),
        ('files', '0001_initial'),
        ('scanners', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScannersResult',
            new_name='ScannerResult',
        ),
    ]
