# Generated by Django 2.2.6 on 2019-10-17 15:14

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0002_auto_20191017_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerresult',
            name='has_matches',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='scannerresult',
            name='matches',
            field=django_extensions.db.fields.json.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='scannerresult',
            name='results',
            field=django_extensions.db.fields.json.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='scannerresult',
            name='scanner',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'customs'), (2, 'wat'), (3, 'yara')]),
        ),
        migrations.AddIndex(
            model_name='scannerresult',
            index=models.Index(fields=['has_matches'],
                               name='scanners_re_has_mat_d3421d_idx'),
        ),
    ]
