# Generated by Django 2.2.6 on 2019-10-21 17:04

from django.db import migrations

from olympia.constants.scanners import YARA


class Migration(migrations.Migration):

    dependencies = [('scanners', '0005_scannerrule')]

    operations = [
        migrations.RunSQL(
            [
                (
                    'UPDATE scanners_results '
                    'SET results = matches WHERE scanner = %s;',
                    [YARA],
                )
            ]
        )
    ]
