# Generated by Django 2.2.6 on 2019-10-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0006_auto_20191021_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scannerresult',
            name='matches',
        ),
    ]
