# Generated by Django 2.2.6 on 2019-10-21 17:18

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0007_remove_scannerresult_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerresult',
            name='results',
            field=django_extensions.db.fields.json.JSONField(default=[]),
        ),
    ]
