# Generated by Django 2.2.6 on 2019-10-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('scanners', '0009_auto_20191023_0906')]

    # Nothing to do...
    operations = []
