# Generated by Django 2.2.6 on 2019-11-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0011_auto_20191023_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerrule',
            name='name',
            field=models.CharField(
                help_text='This is the exact name of the rule used by a scanner.', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='scannerrule',
            unique_together={('name', 'scanner')},
        ),
    ]
