# Generated by Django 2.2.6 on 2019-11-05 15:22

from django.db import migrations


def create_waffle_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.create(
        name='run-action-in-auto-approve',
        active=False,
        note='Execute run_action() in auto_approve CRON',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0012_auto_20191105_1037'),
        ('waffle', '0003_update_strings_for_i18n'),
    ]

    operations = [migrations.RunPython(create_waffle_switch)]
