# Generated by Django 2.2.7 on 2019-11-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('scanners', '0014_alter_action_choices_on_scannerrule')]

    operations = [
        migrations.AddField(
            model_name='scannerresult',
            name='state',
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (None, 'Unknown'),
                    (1, 'True positive'),
                    (2, 'False positive'),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name='scannerresult',
            index=models.Index(
                fields=['state'], name='scanners_re_state_2893a0_idx'
            ),
        ),
    ]
