# Generated by Django 2.2.7 on 2019-11-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('scanners', '0015_auto_20191113_1126')]

    operations = [
        migrations.AddField(
            model_name='scannerrule',
            name='definition',
            field=models.TextField(blank=True, null=True),
        )
    ]
