# Generated by Django 2.2.9 on 2020-01-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0017_auto_20200107_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerqueryrule',
            name='is_active',
            field=models.BooleanField(
                default=True, help_text='When unchecked, the scanner results will not be bound to this rule and the action will not be executed.'),
        ),
        migrations.AlterField(
            model_name='scannerrule',
            name='is_active',
            field=models.BooleanField(
                default=True, help_text='When unchecked, the scanner results will not be bound to this rule and the action will not be executed.'),
        ),
    ]
