# Generated by Django 2.2.9 on 2020-01-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0019_auto_20200113_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerqueryrule',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(
                1, 'New'), (2, 'Running'), (3, 'Aborted'), (5, 'Aborting'), (4, 'Completed')], default=1),
        ),
    ]
