# Generated by Django 2.2.9 on 2020-01-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0020_auto_20200116_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerqueryresult',
            name='scanner',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'customs'), (2, 'wat'), (3, 'yara'), (4, 'ml_api')]),
        ),
        migrations.AlterField(
            model_name='scannerqueryrule',
            name='scanner',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'customs'), (2, 'wat'), (3, 'yara'), (4, 'ml_api')]),
        ),
        migrations.AlterField(
            model_name='scannerresult',
            name='scanner',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'customs'), (2, 'wat'), (3, 'yara'), (4, 'ml_api')]),
        ),
        migrations.AlterField(
            model_name='scannerrule',
            name='scanner',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'customs'), (2, 'wat'), (3, 'yara'), (4, 'ml_api')]),
        ),
    ]
