# Generated by Django 2.2.9 on 2020-01-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0021_auto_20200122_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerqueryrule',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Running'), (
                3, 'Aborted'), (5, 'Aborting'), (4, 'Completed'), (6, 'Scheduled')], default=1),
        ),
    ]
