# Generated by Django 2.2.9 on 2020-01-23 10:41

from django.db import migrations


def create_waffle_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.create(
        name='enable-scanner-ml-api-call',
        active=False,
        note='Call the ML API with the scanner results',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0022_auto_20200122_1644'),
    ]

    operations = [migrations.RunPython(create_waffle_switch)]
