# Generated by Django 2.2.10 on 2020-02-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0025_switch_enable_call_ml_api_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerqueryrule',
            name='run_on_disabled_addons',
            field=models.BooleanField(
                default=False, help_text='Run this rule on add-ons that have been force-disabled as well.'),
        ),
        migrations.AlterField(
            model_name='scannerqueryrule',
            name='scanner',
            field=models.PositiveSmallIntegerField(
                choices=[(3, 'yara')], default=3),
        ),
    ]
