# Generated by Django 2.2.11 on 2020-03-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0027_add_group_result_id_and_task_count_to_scannerqueryrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerqueryresult',
            name='scanner',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'customs'), (2, 'wat'), (3, 'yara'), (4, 'mad')]),
        ),
        migrations.AlterField(
            model_name='scannerresult',
            name='scanner',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'customs'), (2, 'wat'), (3, 'yara'), (4, 'mad')]),
        ),
        migrations.AlterField(
            model_name='scannerrule',
            name='scanner',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'customs'), (2, 'wat'), (3, 'yara'), (4, 'mad')]),
        ),
    ]
