# Generated by Django 2.2.11 on 2020-03-09 12:45

from django.db import migrations


def rename_waffle_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.filter(name='enable-scanner-ml-api-call').update(
        name='enable-mad'
    )


class Migration(migrations.Migration):

    dependencies = [('scanners', '0028_auto_20200309_1230')]

    operations = [migrations.RunPython(rename_waffle_switch)]
