# Generated by Django 2.2.10 on 2020-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0029_rename_ml_api_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerresult',
            name='score',
            field=models.DecimalField(
                blank=True, decimal_places=5, default=-1, max_digits=6, null=True),
        ),
    ]
