# Generated by Django 2.2.12 on 2020-05-19 14:38

from django.db import migrations


def delete_version_scanner_flags(apps, schema_editor):
    VersionScannerFlags = apps.get_model('scanners', 'VersionScannerFlags')
    VersionScannerFlags.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [('scanners', '0031_versionscannerflags')]

    operations = [migrations.RunPython(delete_version_scanner_flags)]
