# Generated by Django 2.2.12 on 2020-05-12 11:59

from django.db import migrations


def delete_waffle_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')

    Switch.objects.filter(name='enable-scanner-results-api').delete()


class Migration(migrations.Migration):

    dependencies = [('scanners', '0032_auto_20200519_1438')]

    operations = [migrations.RunPython(delete_waffle_switch)]
