# Generated by Django 2.2.13 on 2020-07-17 12:33
from django.db import migrations

from olympia.constants.scanners import CUSTOMS


def backfill_model_version(apps, schema_editor):
    ScannerResult = apps.get_model('scanners', 'ScannerResult')
    # Set a default model version for all customs results that are bound to a
    # version and have a score (and no model version already).
    ScannerResult.objects.exclude(version=None).exclude(score=None).filter(
        scanner=CUSTOMS
    ).filter(model_version=None).update(model_version='20200227')


class Migration(migrations.Migration):

    dependencies = [('scanners', '0036_scannerresult_model_version')]

    operations = [migrations.RunPython(backfill_model_version)]
