# Generated by Django 2.2.16 on 2020-09-23 18:08

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0038_scannerqueryrule_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerqueryresult',
            name='results',
            field=django_jsonfield_backport.models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='scannerresult',
            name='results',
            field=django_jsonfield_backport.models.JSONField(default=list),
        ),
    ]
