# Generated by Django 2.2.19 on 2021-03-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0042_remove_waffle_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerqueryrule',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'No action'), (20, 'Flag for human review'), (100, 'Delay auto-approval'), (200, 'Delay auto-approval indefinitely'), (300, 'Delay auto-approval indefinitely and add restrictions')], default=1),
        ),
        migrations.AlterField(
            model_name='scannerrule',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'No action'), (20, 'Flag for human review'), (100, 'Delay auto-approval'), (200, 'Delay auto-approval indefinitely'), (300, 'Delay auto-approval indefinitely and add restrictions')], default=1),
        ),
    ]
