# Generated by Django 2.2.21 on 2021-05-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0043_auto_20210325_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerqueryresult',
            name='has_matches',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='scannerqueryresult',
            name='was_blocked',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scannerresult',
            name='has_matches',
            field=models.BooleanField(null=True),
        ),
    ]
