# Generated by Django 2.2.23 on 2021-06-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0044_auto_20210511_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerqueryrule',
            name='action',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'No action'),
                    (20, 'Flag for human review'),
                    (100, 'Delay auto-approval'),
                    (200, 'Delay auto-approval indefinitely'),
                    (300, 'Delay auto-approval indefinitely and add restrictions'),
                    (
                        400,
                        'Delay auto-approval indefinitely and add restrictions to future approvals',
                    ),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name='scannerrule',
            name='action',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'No action'),
                    (20, 'Flag for human review'),
                    (100, 'Delay auto-approval'),
                    (200, 'Delay auto-approval indefinitely'),
                    (300, 'Delay auto-approval indefinitely and add restrictions'),
                    (
                        400,
                        'Delay auto-approval indefinitely and add restrictions to future approvals',
                    ),
                ],
                default=1,
            ),
        ),
    ]
