# Generated by Django 3.2.16 on 2022-10-17 19:00

from django.db import migrations, models
import django.db.models.deletion


def delete_existing_query_rules_and_results(apps, scheme_editor):
    # This migration deletes all ScannerQueryRule and ScannerQueryResults. We
    # shouldn't have many laying around in production and deleting them instead
    # of updating them to the new schema is a lot simpler: we can directly add
    # the matched_rule FK without allowing `None`.
    ScannerQueryRule = apps.get_model('scanners', 'ScannerQueryRule')
    ScannerQueryResult = apps.get_model('scanners', 'ScannerQueryResult')
    ScannerQueryRule.objects.all().delete()
    ScannerQueryResult.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0047_delete_wat_scanner_results'),
    ]

    operations = [
        migrations.RunPython(delete_existing_query_rules_and_results),
        migrations.RemoveField(
            model_name='scannerquerymatch',
            name='result',
        ),
        migrations.RemoveField(
            model_name='scannerquerymatch',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='scannerqueryresult',
            name='matched_rules',
        ),
        migrations.AddField(
            model_name='scannerqueryresult',
            name='matched_rule',
            field=models.ForeignKey(
                # Django requires a default in the migration, but it shouldn't
                # be used as we're deleting all data beforehand.
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='results',
                to='scanners.scannerqueryrule',
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='scannerqueryresult',
            index=models.Index(
                fields=['was_blocked'], name='scanners_qu_was_blo_7eec1c_idx'
            ),
        ),
        migrations.RemoveIndex(
            model_name='scannerqueryresult',
            name='scanners_qu_has_mat_a6766b_idx',
        ),
        migrations.RemoveField(
            model_name='scannerqueryresult',
            name='has_matches',
        ),
        migrations.DeleteModel(
            name='ScannerQueryMatch',
        ),
    ]
