# Generated by Django 3.2.16 on 2022-10-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0048_auto_20221017_1900'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scannerqueryresult',
            name='scanners_qu_state_32d49e_idx',
        ),
        migrations.RemoveField(
            model_name='scannerqueryresult',
            name='state',
        ),
        migrations.RemoveField(
            model_name='scannerqueryrule',
            name='action',
        ),
        migrations.RemoveField(
            model_name='scannerqueryrule',
            name='is_active',
        ),
    ]
