# Generated by Django 3.2.16 on 2022-10-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0049_auto_20221018_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scannerqueryrule',
            name='action',
        ),
        migrations.RemoveField(
            model_name='scannerqueryrule',
            name='is_active',
        ),
    ]
