# Generated by Django 3.2.16 on 2022-11-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0049_auto_20221018_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerqueryrule',
            name='pretty_name',
            field=models.CharField(blank=True, default='', help_text='Human-readable name for the scanner rule', max_length=255, verbose_name='Human-readable name'),
        ),
        migrations.AddField(
            model_name='scannerrule',
            name='pretty_name',
            field=models.CharField(blank=True, default='', help_text='Human-readable name for the scanner rule', max_length=255, verbose_name='Human-readable name'),
        ),
    ]
