# Generated by Django 3.2.16 on 2022-11-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0050_auto_20221107_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerqueryrule',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Human readable description for the scanner rule', max_length=255),
        ),
        migrations.AddField(
            model_name='scannerrule',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Human readable description for the scanner rule', max_length=255),
        ),
    ]
