# Generated by Django 4.2.1 on 2023-05-24 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('versions', '0039_alter_version_needs_human_review'),
        ('files', '0029_auto_20230301_1843'),
        ('scanners', '0051_auto_20221108_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerqueryresult',
            name='version',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)ss',
                to='versions.version',
            ),
        ),
        migrations.AlterField(
            model_name='scannerresult',
            name='upload',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='%(class)ss',
                to='files.fileupload',
            ),
        ),
        migrations.AlterField(
            model_name='scannerresult',
            name='version',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)ss',
                to='versions.version',
            ),
        ),
    ]
