# Generated by Django 4.2.23 on 2025-08-06 10:46

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch



class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0052_alter_scannerqueryresult_version_and_more'),
    ]

    operations = [
        CreateWaffleSwitch('enable-narc')
    ]
