# Generated by Django 4.2.23 on 2025-08-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0053_add_narc_waffle_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerqueryrule',
            name='run_on_current_version_only',
            field=models.BooleanField(default=False, help_text='Run this rule on the latest currently publicly listed version of each add-on only.'),
        ),
        migrations.AddField(
            model_name='scannerqueryrule',
            name='run_on_specific_channel',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, ''), (1, 'Unlisted'), (2, 'Listed')], default=None, help_text='Run this rule on versions in the specific channel only.', null=True),
        ),
        migrations.AlterField(
            model_name='scannerqueryresult',
            name='scanner',
            field=models.PositiveSmallIntegerField(choices=[(1, 'customs'), (2, 'wat'), (3, 'yara'), (4, 'mad'), (5, 'narc')]),
        ),
        migrations.AlterField(
            model_name='scannerqueryrule',
            name='scanner',
            field=models.PositiveSmallIntegerField(choices=[(3, 'yara'), (5, 'narc')]),
        ),
        migrations.AlterField(
            model_name='scannerresult',
            name='scanner',
            field=models.PositiveSmallIntegerField(choices=[(1, 'customs'), (2, 'wat'), (3, 'yara'), (4, 'mad'), (5, 'narc')]),
        ),
        migrations.AlterField(
            model_name='scannerrule',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'No action'), (20, 'Flag for human review'), (100, 'Delay auto-approval'), (200, 'Delay auto-approval indefinitely'), (300, 'Delay auto-approval indefinitely and add restrictions'), (400, 'Delay auto-approval indefinitely and add restrictions to future approvals'), (500, 'Force-disable and block')], default=1),
        ),
        migrations.AlterField(
            model_name='scannerrule',
            name='scanner',
            field=models.PositiveSmallIntegerField(choices=[(1, 'customs'), (2, 'wat'), (3, 'yara'), (4, 'mad'), (5, 'narc')]),
        ),
    ]
