# Generated by Django 4.2.25 on 2025-10-06 13:08

from django.db import migrations

from olympia.core.db.migrations import DeleteWaffleSwitch

class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0054_scannerqueryrule_run_on_current_version_only_and_more'),
    ]

    operations = [
        DeleteWaffleSwitch('enable-mad')
    ]
