# Generated by Django 4.2.25 on 2025-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0055_delete_enable_mad_waffle_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerqueryrule',
            name='exclude_promoted_addons',
            field=models.BooleanField(default=False, help_text='Exclude add-ons that are in a promoted group from this rule'),
        ),
        migrations.AddField(
            model_name='scannerrule',
            name='exclude_promoted_addons',
            field=models.BooleanField(default=False, help_text='Exclude add-ons that are in a promoted group from this rule'),
        ),
        migrations.AddField(
            model_name='scannerqueryresult',
            name='was_promoted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='scannerqueryresult',
            index=models.Index(fields=['was_promoted'], name='scanners_qu_was_pro_9a2314_idx'),
        ),
    ]
