# Generated by Django 4.2.25 on 2025-10-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0056_scannerqueryrule_exclude_promoted_addons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scannerresult',
            name='score',
        ),
    ]
