# Generated by Django 4.2.27 on 2025-12-22 16:14

from django.db import migrations
from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0057_remove_scannerresult_score'),
    ]

    operations = [CreateWaffleSwitch('enable-scanner-webhooks')]
