# Generated by Django 4.2.27 on 2026-01-07 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0058_create_waffle_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerWebhook',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=255)),
                ('api_key', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scanners_webhooks',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ScannerWebhookEvent',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ('modified', models.DateTimeField(auto_now=True)),
                (
                    'event',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'during_validation'),
                        ]
                    ),
                ),
                (
                    'webhook',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='scanners.scannerwebhook',
                    ),
                ),
            ],
            options={
                'db_table': 'scanners_webhook_events',
                'unique_together': {('webhook', 'event')},
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
