# Generated by Django 4.2.27 on 2026-01-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'scanners',
            '0060_remove_scannerresult_scanners_results_upload_id_scanner_version_id_ad9eb8a6_uniq_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerqueryresult',
            name='scanner',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'customs'),
                    (2, 'wat'),
                    (3, 'yara'),
                    (4, 'mad'),
                    (5, 'narc'),
                    (6, 'webhook'),
                ]
            ),
        ),
        migrations.AlterField(
            model_name='scannerresult',
            name='scanner',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'customs'),
                    (2, 'wat'),
                    (3, 'yara'),
                    (4, 'mad'),
                    (5, 'narc'),
                    (6, 'webhook'),
                ]
            ),
        ),
        migrations.AlterField(
            model_name='scannerrule',
            name='scanner',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'customs'),
                    (2, 'wat'),
                    (3, 'yara'),
                    (4, 'mad'),
                    (5, 'narc'),
                    (6, 'webhook'),
                ]
            ),
        ),
    ]
