# Generated by Django 4.2.27 on 2026-01-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0061_alter_scannerqueryresult_scanner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerwebhookevent',
            name='event',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'during_validation'), (2, 'on_source_code_uploaded')]
            ),
        ),
    ]
