# Generated by Django 4.2.27 on 2026-01-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0062_alter_scannerwebhookevent_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerwebhook',
            name='api_key',
            field=models.CharField(max_length=255),
        ),
    ]
