# Generated by Django 4.2.27 on 2026-01-27 09:17

from django.db import migrations

from olympia.constants.scanners import CUSTOMS, WEBHOOK


def create_customs_scanner_rules_for_webhook(apps, schema_editor):
    ScannerRule = apps.get_model('scanners', 'ScannerRule')
    # Create the same scanner rules that `customs` has but for `webhook`.
    # Disable them for now.
    for obj in ScannerRule.objects.filter(scanner=CUSTOMS):
        if ScannerRule.objects.filter(name=obj.name, scanner=WEBHOOK).exists():
            # Skip already existing entries.
            continue

        obj.pk = None
        obj.scanner = WEBHOOK
        obj.is_active = False
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0063_alter_scannerwebhook_api_key'),
    ]

    operations = [
        migrations.RunPython(
            create_customs_scanner_rules_for_webhook,
            reverse_code=migrations.RunPython.noop,
        )
    ]
