# Generated by Django 4.2.27 on 2026-01-29 16:09

from django.db import migrations
from olympia.constants.scanners import NARC


def add_default_configuration_for_narc(apps, schema_editor):
    ScannerRule = apps.get_model('scanners', 'ScannerRule')
    ScannerQueryRule =  apps.get_model('scanners', 'ScannerQueryRule')
    # This configuration matches the behavior NARC rules had when rule
    # configuration was introduced.
    narc_config = {
        'examine_slug': False,
        'examine_xpi_names': True,
        'examine_authors_names': True,
        'examine_listing_names': True,
        'examine_homoglyphs_variants': True,
        'examine_normalized_variants': True
    }
    ScannerRule.objects.filter(scanner=NARC, configuration={}).update(configuration=narc_config)
    ScannerQueryRule.objects.filter(scanner=NARC, configuration={}).update(configuration=narc_config)


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0064_scannerqueryrule_configuration_and_more'),
    ]

    operations = [
        migrations.RunPython(
            add_default_configuration_for_narc, migrations.RunPython.noop
        )
    ]
