# Generated by Django 4.2.27 on 2026-01-29 15:56

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0064_create_customs_scanner_rules_for_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerqueryrule',
            name='configuration',
            field=django_jsonform.models.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scannerrule',
            name='configuration',
            field=django_jsonform.models.fields.JSONField(blank=True, default=dict),
        ),
    ]
