# Generated by Django 4.2.28 on 2026-02-10 09:08
from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0066_default_narc_configuration'),
    ]

    operations = [CreateWaffleSwitch('use-yara-x')]
