# Generated by Django 4.2.28 on 2026-02-26 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0031_alter_activitylog_action'),
        ('scanners', '0072_delete_enable_customs_waffle_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerresult',
            name='activity_log',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='scanner_result',
                to='activity.activitylog',
            ),
        ),
    ]
