# Generated by Django 4.2.28 on 2026-03-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'scanners',
            '0075_alter_scannerqueryresult_results_alter_scannerresult_results',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scannerresult',
            name='model_version',
        ),
    ]
