# Generated by Django 4.2.29 on 2026-03-19 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scanners', '0078_remove_narc_meta_pattern_and_span'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerwebhook',
            name='service_account',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='scanner_webhooks',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
