# Generated by Django 4.2 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0079_scannerwebhook_service_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerwebhookevent',
            name='event',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'during_validation'),
                    (2, 'on_source_code_uploaded'),
                    (3, 'on_version_created'),
                    (4, 'push'),
                ]
            ),
        ),
    ]
