# Generated by Django 5.2.12 on 2026-03-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0080_alter_scannerwebhookevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerwebhookevent',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Whether the scanner should be called for this event. Once this event is added to the scanner, it cannot be removed because some scanner results might have already been linked to it.',
            ),
        ),
    ]
