# Generated by Django 5.2.13 on 2026-04-20 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0064_cinderjob_content_review_and_more'),
        ('scanners', '0082_remove_narc_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerrule',
            name='policy',
            field=models.ForeignKey(help_text='Policy used to automatically derive an action from when the rule hit.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='abuse.cinderpolicy'),
        ),
    ]
