# Generated by Django 5.2.13 on 2026-05-06 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0065_alter_contentdecision_action_and_more'),
        ('scanners', '0083_scannerrule_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerrule',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'No action'), (20, 'Flag for human review'), (100, 'Delay auto-approval'), (200, 'Delay auto-approval indefinitely'), (300, 'Delay auto-approval indefinitely and add restrictions'), (400, 'Delay auto-approval indefinitely and add restrictions to future approvals'), (500, 'Force-disable and block')], default=1, help_text='Workflow action to execute', verbose_name='Workflow action'),
        ),
        migrations.AlterField(
            model_name='scannerrule',
            name='policy',
            field=models.ForeignKey(blank=True, help_text='Policy used to automatically derive an action from when the rule hit.', limit_choices_to={'expose_in_reviewer_tools': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abuse.cinderpolicy'),
        ),
    ]
