# Generated by Django 5.2.16 on 2026-08-06 16:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0070_alter_cinderpolicy_expose_in_reviewer_tools_and_more'),
        ('scanners', '0086_delete_run_action_in_auto_approve_waffle_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerqueryrule',
            name='created_after',
            field=models.DateField(blank=True, db_default=None, default=datetime.date(2019, 4, 5), null=True),
        ),
        migrations.AlterField(
            model_name='scannerqueryrule',
            name='run_on_specific_channel',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, ''), (1, 'Unlisted'), (2, 'Listed'), (3, 'Enterprise')], default=None, help_text='Run this rule on versions in the specific channel only.', null=True),
        ),
        migrations.AlterField(
            model_name='scannerrule',
            name='policy',
            field=models.ForeignKey(blank=True, help_text='Policy used to automatically derive an action from when the rule hit.', limit_choices_to={'expose_in_reviewer_tools__in': [1, 2]}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abuse.cinderpolicy'),
        ),
    ]
