# Generated by Django 5.2.17 on 2026-08-17 14:50

from django.db import migrations, models
from olympia import amo

def channel_to_channel_list(apps, schema_editor):
    ScannerQueryRule = apps.get_model('scanners', 'ScannerQueryRule')
    for query_rule in ScannerQueryRule.objects.all():
        channel = query_rule.run_on_specific_channel
        query_rule.run_on_specific_channels = [channel] if channel else list(amo.CHANNEL_CHOICES)
        query_rule.save()


def channel_list_to_channel(apps, schema_editor):
    ScannerQueryRule = apps.get_model('scanners', 'ScannerQueryRule')
    for query_rule in ScannerQueryRule.objects.all():
        channels = query_rule.run_on_specific_channels
        query_rule.run_on_specific_channel = channels[0] if len(channels) == 1 else None
        query_rule.save()


class Migration(migrations.Migration):
    dependencies = [
        ('scanners', '0087_scannerqueryrule_created_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerqueryrule',
            name='run_on_specific_channels',
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(channel_to_channel_list, channel_list_to_channel),
    ]
