# Generated by Django 5.2.17 on 2026-08-17 14:50

from django.db import migrations, models

def channel_to_channel_list(apps, schema_editor):
    ScannerQueryRule = apps.get_model('scanners', 'ScannerQueryRule')
    for query_rule in ScannerQueryRule.objects.all():
        channel = query_rule.run_on_specific_channel
        query_rule.update(
            run_on_specific_channel=[channel] if channel else []
        )


def channel_list_to_channel(apps, schema_editor):
    ScannerQueryRule = apps.get_model('scanners', 'ScannerQueryRule')
    for query_rule in ScannerQueryRule.objects.all():
        channel = query_rule.run_on_specific_channel
        query_rule.update(
            run_on_specific_channel=channel[0] if channel else None
        )

class Migration(migrations.Migration):
    dependencies = [
        ('scanners', '0087_scannerqueryrule_created_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerqueryrule',
            name='run_on_specific_channel',
            field=models.JSONField(
                default=list,
                blank=True,
            ),
        ),
        migrations.RunPython(channel_to_channel_list, channel_list_to_channel),
    ]
