# Generated by Django 5.2.17 on 2026-09-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0088_alter_scannerqueryrule_run_on_specific_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerwebhook',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
