# Generated by Django 5.2.16 on 2026-09-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scanners', '0089_alter_scannerwebhook_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerresult',
            name='delivery_attempts',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text=(
                    'Number of times the webhook has been called for this result'
                ),
            ),
        ),
    ]
