# Generated by Django 2.2.5 on 2019-09-12 13:50

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json
import olympia.amo.fields
import olympia.stats.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCount',
            fields=[
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('versions', django_extensions.db.fields.json.JSONField(db_column='version', default=dict, null=True)),
                ('statuses', django_extensions.db.fields.json.JSONField(db_column='status', default=dict, null=True)),
                ('applications', django_extensions.db.fields.json.JSONField(db_column='application', default=dict, null=True)),
                ('oses', django_extensions.db.fields.json.JSONField(db_column='os', default=dict, null=True)),
                ('locales', django_extensions.db.fields.json.JSONField(db_column='locale', default=dict, null=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons.Addon')),
            ],
            options={
                'db_table': 'update_counts',
            },
            bases=(olympia.amo.models.SearchMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DownloadCount',
            fields=[
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('sources', django_extensions.db.fields.json.JSONField(db_column='src', default=dict, null=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons.Addon')),
            ],
            options={
                'db_table': 'download_counts',
            },
            bases=(olympia.amo.models.SearchMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='updatecount',
            index=models.Index(fields=['count'], name='count'),
        ),
        migrations.AddIndex(
            model_name='updatecount',
            index=models.Index(fields=['addon'], name='addon_id'),
        ),
        migrations.AddIndex(
            model_name='updatecount',
            index=models.Index(fields=['date'], name='date'),
        ),
        migrations.AddIndex(
            model_name='updatecount',
            index=models.Index(fields=['addon', 'count'], name='addon_and_count'),
        ),
        migrations.AddIndex(
            model_name='updatecount',
            index=models.Index(fields=['addon', 'date'], name='addon_date_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadcount',
            index=models.Index(fields=['count'], name='count'),
        ),
        migrations.AddIndex(
            model_name='downloadcount',
            index=models.Index(fields=['addon'], name='addon_id'),
        ),
        migrations.AddIndex(
            model_name='downloadcount',
            index=models.Index(fields=['addon', 'count'], name='addon_and_count'),
        ),
        migrations.AddIndex(
            model_name='downloadcount',
            index=models.Index(fields=['addon', 'date'], name='addon_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='downloadcount',
            constraint=models.UniqueConstraint(fields=('date', 'addon'), name='date_2'),
        ),
    ]
