# Generated by Django 2.2.12 on 2020-06-05 11:21

from django.db import migrations


def create_waffle_flag(apps, schema_editor):
    Flag = apps.get_model('waffle', 'Flag')
    Flag.objects.create(
        name='beta-stats',
        rollout=True,
        percent=0,
        note='Enable access to the beta statistics',
    )


class Migration(migrations.Migration):

    dependencies = [('stats', '0001_initial')]

    operations = [migrations.RunPython(create_waffle_flag)]
