# Generated by Django 2.2.13 on 2020-07-07 17:00
from django.db import migrations


def delete_waffle_flag(apps, schema_editor):
    Flag = apps.get_model('waffle', 'Flag')
    Flag.objects.filter(name='beta-stats').delete()


class Migration(migrations.Migration):

    dependencies = [('stats', '0002_beta_stats_flag')]

    operations = [migrations.RunPython(delete_waffle_flag)]
