# Generated by Django 2.2.13 on 2020-07-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_delete_beta_stats_flag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateCount',
        ),
    ]
