# Generated by Django 2.2.13 on 2020-07-27 08:43

from django.db import migrations


def create_waffle_switch(apps, schema_editor):
    Switch = apps.get_model("waffle", "Switch")

    Switch.objects.create(
        name="use-fenix-build-ids",
        # IMPORTANT: enabled by default
        active=True,
        note="Add a 'build' prefix to Fenix app versions (usage stats)",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0004_delete_updatecount"),
    ]

    operations = [migrations.RunPython(create_waffle_switch)]
