# Generated by Django 2.2.13 on 2020-07-23 16:13

from django.db import migrations


def create_waffle_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.create(
        name='use-bigquery-for-download-stats-cron',
        active=False,
        note='Use BigQuery in download stats cron tasks',
    )


class Migration(migrations.Migration):

    dependencies = [('stats', '0004_delete_updatecount')]

    operations = [migrations.RunPython(create_waffle_switch)]
