# Generated by Django 2.2.16 on 2020-09-23 18:08

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_create_switch_for_fenix_build_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadcount',
            name='sources',
            field=django_jsonfield_backport.models.JSONField(db_column='src', null=True),
        ),
    ]
