# Generated by Django 2.2.16 on 2020-10-07 08:39

from django.db import migrations


def delete_waffles(apps, schema_editor):
    Switch = apps.get_model("waffle", "Switch")
    Switch.objects.filter(name="use-bigquery-for-download-stats-cron").delete()
    Switch.objects.filter(name="use-bigquery-for-addon-adu").delete()

    Flag = apps.get_model("waffle", "Flag")
    Flag.objects.filter(name="bigquery-download-stats").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0007_delete_downloadcount"),
    ]

    operations = [migrations.RunPython(delete_waffles)]
