# Generated by Django 2.2.13 on 2020-07-27 08:43

from django.db import migrations


def delete_waffle_switch(apps, schema_editor):
    Switch = apps.get_model("waffle", "Switch")

    Switch.objects.filter(name="use-fenix-build-ids").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0008_auto_20201007_0839"),
    ]

    operations = [migrations.RunPython(delete_waffle_switch)]
