# Generated by Django 2.2.17 on 2021-01-12 16:14

from django.db import migrations


def create_waffle_switch(apps, schema_editor):
    Switch = apps.get_model("waffle", "Switch")

    Switch.objects.create(
        name="disable-bigquery",
        active=False,
        note="Disable the BigQuery queries when active (stats pages)",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20201013_1417'),
    ]

    operations = [migrations.RunPython(create_waffle_switch)]
