# Generated by Django 2.2.5 on 2019-09-12 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryItem',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True,
                                                 default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('custom_addon_name', models.CharField(
                    blank=True, help_text='Custom add-on name, if needed for space constraints. Will be used in the heading if present, but will <strong>not</strong> be translated.', max_length=255)),
                ('custom_heading', models.CharField(
                    blank=True, help_text='Short text used in the header. Can contain the following special tags: {start_sub_heading}, {addon_name}, {end_sub_heading}. Will be translated. Currently *not* visible to the user - #11817', max_length=255)),
                ('custom_description', models.TextField(
                    blank=True, help_text='Longer text used to describe an add-on. Should not contain any HTML or special tags. Will be translated.')),
                ('position', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0,
                                                              help_text='Position in the discovery pane when telemetry-aware recommendations are off (editorial fallback). The lower the number, the higher the item will appear in the page. If left blank or if the value is 0, the item will not appear unless part of telemetry-aware recommendations.')),
                ('position_china', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0,
                                                                    help_text='Position in the discovery pane in China (See position field above).')),
                ('position_override', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0,
                                                                       help_text='Position in the discovery pane when telemetry-aware recommendations are on but we want to override them.(See position field above).')),
                ('recommendable', models.BooleanField(db_index=True, default=False,
                                                      help_text="Should this add-on's versions be recommended. When enabled new versions will be reviewed for recommended status.")),
                ('addon', models.OneToOneField(help_text='Add-on id this item will point to (If you do not know the id, paste the slug instead and it will be transformed automatically for you. If you have access to the add-on admin page, you can use the magnifying glass to see all available add-ons.',
                                               on_delete=django.db.models.deletion.CASCADE, to='addons.Addon')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.OnChangeMixin, olympia.amo.models.SearchMixin,
                   olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
