# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations, models
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('custom_description', models.TextField(blank=True, help_text='Longer text used to describe an add-on. Should not contain any HTML or special tags. Will be translated.')),
                ('position', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, help_text='Position in the discovery pane when telemetry-aware recommendations are off (editorial fallback). The lower the number, the higher the item will appear in the page. If left blank or if the value is 0, the item will not appear unless part of telemetry-aware recommendations.')),
                ('position_china', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, help_text='Position in the discovery pane in China (See position field above).')),
                ('position_override', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, help_text='Position in the discovery pane when telemetry-aware recommendations are on but we want to override them.(See position field above).')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.OnChangeMixin, olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomepageShelves',
            fields=[
            ],
            options={
                'verbose_name_plural': 'homepage shelves',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shelves.shelf',),
        ),
    ]
