# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hero', '0001_initial'),
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryHeroImageUpload',
            fields=[
            ],
            options={
                'verbose_name_plural': 'primary hero images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hero.primaryheroimage',),
        ),
    ]
