# Generated by Django 2.2.5 on 2019-09-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('discovery', '0001_initial'),
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryHeroShelf',
            fields=[
            ],
            options={
                'verbose_name_plural': 'secondary hero shelves',
                'get_latest_by': 'created',
                'abstract': False,
                'proxy': True,
                'base_manager_name': 'objects',
                'indexes': [],
                'constraints': [],
            },
            bases=('hero.secondaryhero',),
        ),
    ]
