# Generated by Django 2.2.12 on 2020-06-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0009_primaryheroimage'),
        ('discovery', '0002_secondary_hero_shelf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryHeroImageShelf',
            fields=[
            ],
            options={
                'verbose_name_plural': 'primary hero images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hero.primaryheroimage',),
        ),
    ]
