# Generated by Django 2.2.14 on 2020-07-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
        ('discovery', '0003_primaryheroimageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfModule',
            fields=[
            ],
            options={
                'verbose_name_plural': 'shelves',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shelves.shelf',),
        ),
    ]
