# Generated by Django 2.2.14 on 2020-07-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_shelfmodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveryitem',
            name='recommendable',
            field=models.BooleanField(db_index=True, help_text="Should this add-on's versions be recommended. When enabled new versions will be reviewed for recommended status.", null=True),
        ),
    ]
