# Generated by Django 2.2.15 on 2020-08-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0006_shelfmanagement'),
        ('discovery', '0005_auto_20200717_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageShelves',
            fields=[
            ],
            options={
                'verbose_name_plural': 'homepage shelves',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shelves.shelfmanagement',),
        ),
    ]
