# Generated by Django 2.2.15 on 2020-08-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0006_shelfmanagement'),
        ('discovery', '0005_auto_20200717_1256'),
    ]

    operations = [
        # Have to disable this because it broke the migration chain when we deleted the
        # base shelves.shelfmanagement - django does seem to be able detect it changing.
        # Its okay though - it's only a proxy model (no database table backing it).
        #
        # migrations.CreateModel(
        #     name='HomepageShelves',
        #     fields=[
        #     ],
        #     options={
        #         'verbose_name_plural': 'homepage shelves',
        #         'proxy': True,
        #         'indexes': [],
        #         'constraints': [],
        #     },
        #     bases=('shelves.shelfmanagement',),
        # ),
    ]
