# Generated by Django 2.2.16 on 2020-10-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0007_auto_20200811_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoveryitem',
            name='recommendable',
        ),
    ]
