# Generated by Django 2.2.16 on 2020-10-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0008_remove_discoveryitem_recommendable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveryitem',
            name='custom_addon_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discoveryitem',
            name='custom_heading',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
