# Generated by Django 2.2.16 on 2020-11-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0009_auto_20201027_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoveryitem',
            name='custom_addon_name',
        ),
        migrations.RemoveField(
            model_name='discoveryitem',
            name='custom_heading',
        ),
    ]
