# Generated by Django 2.2.19 on 2021-03-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0010_auto_20201104_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelfmodule',
            options={'verbose_name_plural': 'shelf modules'},
        ),
    ]
