# Generated by Django 3.2.4 on 2021-07-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0011_auto_20210325_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShelfModule',
        ),
    ]
