# Generated by Django 3.2.4 on 2021-07-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0018_delete_shelfmanagement'),
        ('discovery', '0012_delete_shelfmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageShelves',
            fields=[
            ],
            options={
                'verbose_name_plural': 'homepage shelves',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shelves.shelf',),
        ),
    ]
