# Generated by Django 3.2.18 on 2023-02-27 11:44

from django.db import migrations


def create_waffle_switch_if_it_doesnt_already_exist(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.get_or_create(
        name='enable-taar',
        defaults={
            'active': True,
            'note': 'Enable requests to TAAR/TAAR-lite for recommendations',
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ('discovery', '0013_homepageshelves'),
    ]

    operations = [
        migrations.RunPython(create_waffle_switch_if_it_doesnt_already_exist),
    ]
