# Generated by Django 4.2.19 on 2025-03-10 11:14

from django.db import migrations

from olympia.core.db.migrations import DeleteWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0014_auto_20230227_1144'),
    ]

    operations = [
        DeleteWaffleSwitch('disco-recommendations')
    ]
