# Generated by Django 4.2.20 on 2025-05-01 19:49

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0029_auto_20250429_1315'),
        ('addons', '0054_update_default_locale_es_to_es-es'),
        ('discovery', '0015_auto_20250310_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromotedAddon',
        )
    ]
