# Generated by Django 4.2.24 on 2025-10-01 09:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0034_rename_promotedaddonpromotion_to_promotedaddon'),
        ('addons', '0057_alter_addon_description_and_more'),
        ('discovery', '0016_delete_promotedaddon_discoveryaddon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryAddon',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('addons.addon',),
            managers=[
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveryPromotedGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('promoted.promotedgroup',),
        ),
        migrations.CreateModel(
            name='PromotedAddon',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('promoted.promotedaddon',),
        ),
    ]
