# Generated by Django 4.2.21 on 2025-05-15 17:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0031_promotedaddon_and_more'),
        ('addons', '0055_alter_addon_description_and_more'),
        ('discovery', '0016_delete_promotedaddon_discoveryaddon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryAddon',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('addons.addon',),
            managers=[
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveryPromotedGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('promoted.promotedgroup',),
        ),
        migrations.CreateModel(
            name='PromotedAddon',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('promoted.promotedaddon',),
        ),
    ]
