# Generated by Django 2.2.5 on 2019-09-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('key', models.CharField(max_length=255,
                                         primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'config',
            },
        ),
    ]
