# Generated by Django 3.2.18 on 2023-05-22 09:38

from django.db import migrations


def rename_review_target_per_day_config(apps, schema_editor):
    Config = apps.get_model('zadmin', 'Config')
    Config.objects.filter(key='notable-review-target-per-day').update(
        key='extra-review-target-per-day'
    )


class Migration(migrations.Migration):
    dependencies = [
        ('zadmin', '0001_initial'),
    ]

    operations = [migrations.RunPython(rename_review_target_per_day_config)]
