# Generated by Django 2.2.16 on 2020-10-14 13:33
import importlib

from django.db import migrations

from olympia.versions.compare import version_int


def increase_version_int_for_asterisk(apps, schema_editor):
    AppVersion = apps.get_model('applications', 'AppVersion')
    for app in AppVersion.objects.filter(version='*'):
        app.update(version_int=version_int(app.version))


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20191101_1222'),
    ]

    operations = [
        migrations.RunPython(increase_version_int_for_asterisk)
    ]
