# Generated by Django 4.2.4 on 2023-09-08 10:40

from django.db import migrations

from olympia import amo
from olympia.versions.compare import version_int


def create_appversions_for_fenix_ga(apps, schema_editor):
    AppVersion = apps.get_model('applications', 'AppVersion')
    for version in ('119.0a1', '119.0', '120.0a1', '120.0'):
        # Might as well create for desktop as the same time for consistency.
        for app in (amo.ANDROID, amo.FIREFOX):
            AppVersion.objects.get_or_create(
                application=app.id,
                version=version,
                version_int=version_int(version),
            )


class Migration(migrations.Migration):
    dependencies = [
        ('applications', '0003_auto_20201014_1333'),
    ]

    operations = [migrations.RunPython(create_appversions_for_fenix_ga)]
