# Generated by Django 2.2.12 on 2020-06-24 02:25

from django.db import migrations, models
import olympia.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200612_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrestrictionhistory',
            options={'verbose_name_plural': 'User Restriction History'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=olympia.users.models.get_anonymized_username, max_length=255, unique=True),
        ),
    ]
