# Generated by Django 3.2.6 on 2021-08-23 14:54

from django.db import migrations
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210601_1421'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=olympia.amo.models.LongNameIndex(fields=['last_login_ip'], name='users_last_login_ip_2cfbbfbd'),
        ),
        migrations.AddIndex(
            model_name='userrestrictionhistory',
            index=olympia.amo.models.LongNameIndex(fields=['ip_address'], name='users_userrestrictionhistory_ip_address_4376df32'),
        ),
        migrations.AddIndex(
            model_name='userrestrictionhistory',
            index=olympia.amo.models.LongNameIndex(fields=['last_login_ip'], name='users_userrestrictionhistory_last_login_ip_d58d95ff'),
        ),
    ]
