# Generated by Django 3.2.6 on 2021-08-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210601_1421'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['last_login_ip'], name='users_last_login_ip_2cfbbfbd'),
        ),
        migrations.AddIndex(
            model_name='userrestrictionhistory',
            index=models.Index(fields=['ip_address'], name='u_restrict_hist_ip_4376df32'),
        ),
        migrations.AddIndex(
            model_name='userrestrictionhistory',
            index=models.Index(fields=['last_login_ip'], name='u_restrict_hist_la_ip_d58d95ff'),
        ),
    ]
