# Generated by Django 3.2.12 on 2022-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220125_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuserrestriction',
            name='email_pattern',
            field=models.CharField(help_text='Enter full email that should be blocked or use unix-style wildcards, e.g. "*@example.com". If you need to block a domain incl subdomains, add a second entry, e.g. "*@*.example.com".', max_length=100, verbose_name='Email Pattern'),
        ),
    ]
