# Generated by Django 3.2.16 on 2022-11-14 15:53

from django.db import migrations, models
from django.db.models.functions import Left, Length


def truncate_bios(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    models.CharField.register_lookup(Length)
    UserProfile.objects.annotate(length_bio=Length('biography')).filter(
        length_bio__gt=255
    ).update(biography=Left('biography', 255))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_emailuserrestriction_email_pattern'),
    ]

    operations = [
        migrations.RunPython(truncate_bios),
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
