# Generated by Django 3.2.17 on 2023-02-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposableemaildomainrestriction',
            name='reason',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                help_text='Private description of why this restriction was added.',
            ),
        ),
        migrations.AddField(
            model_name='emailuserrestriction',
            name='reason',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                help_text='Private description of why this restriction was added.',
            ),
        ),
        migrations.AddField(
            model_name='ipnetworkuserrestriction',
            name='reason',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                help_text='Private description of why this restriction was added.',
            ),
        ),
    ]
