# Generated by Django 4.2.1 on 2023-05-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_auto_20230209_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposableemaildomainrestriction',
            name='restriction_type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Add-on Submission'),
                    (2, 'Add-on Approval'),
                    (3, 'Rating'),
                    (4, 'Rating Flag for Moderation'),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name='emailuserrestriction',
            name='restriction_type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Add-on Submission'),
                    (2, 'Add-on Approval'),
                    (3, 'Rating'),
                    (4, 'Rating Flag for Moderation'),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name='ipnetworkuserrestriction',
            name='restriction_type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Add-on Submission'),
                    (2, 'Add-on Approval'),
                    (3, 'Rating'),
                    (4, 'Rating Flag for Moderation'),
                ],
                default=1,
            ),
        ),
    ]
