# Generated by Django 4.2.6 on 2023-11-15 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):
    dependencies = [
        ("addons", "0047_addonuser_original_role_alter_addon_type"),
        ("ratings", "0010_auto_20231106_1533"),
        (
            "bandwagon",
            "0008_alter_collection_options_alter_collection_managers_and_more",
        ),
        (
            "users",
            "0011_alter_disposableemaildomainrestriction_restriction_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedUserContent",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="content_disabled_on_ban",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("addons", models.ManyToManyField(to="addons.addon")),
                ("addons_users", models.ManyToManyField(to="addons.addonuser")),
                ("collections", models.ManyToManyField(to="bandwagon.collection")),
                ("ratings", models.ManyToManyField(to="ratings.rating")),
            ],
            options={
                "get_latest_by": "created",
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
