# Generated by Django 4.2.7 on 2023-12-07 11:53

from django.db import migrations
from django.db.models import Q


def clear_bad_homepage(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    qs = UserProfile.objects.exclude(homepage='').exclude(
        Q(homepage__startswith='http://') | Q(homepage__startswith='https://')
    )
    qs.update(homepage='')


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_suppressedemail"),
    ]

    operations = [
        migrations.RunPython(clear_bad_homepage, lambda *args: None)
    ]
