# Generated by Django 4.2.8 on 2023-12-11 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_clear_bad_homepage_url_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppressedEmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('confirmation_code', models.CharField(default=uuid.uuid4, max_length=255)),
                ('suppressed_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suppressed_email', to='users.suppressedemail')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
