# Generated by Django 4.2.8 on 2023-12-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_suppressedemailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppressedemailverification',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Delivered'), (2, 'Failed')], default=0),
        ),
    ]
