# Generated by Django 4.2.21 on 2025-06-09 10:45

from django.db import migrations
from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_suppressedemailverification_status'),
    ]

    operations = [
        CreateWaffleSwitch('enable-addons-hard-deletion')
    ]
