# Generated by Django 4.2.21 on 2025-05-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_suppressedemailverification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_public',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_full_profile',
            field=models.BooleanField(db_column='public', default=False),
        ),
    ]
