# Generated by Django 4.2.23 on 2025-07-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_enable-addons-hard-deletion-switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposableemaildomainrestriction',
            name='domain',
            field=models.CharField(help_text='Enter full disposable email domain that should be blocked. Wildcards are not supported: if you need those, or need to match against the entire email and not just the domain part, use "Email user restrictions" instead.', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='disposableemaildomainrestriction',
            constraint=models.UniqueConstraint(fields=('domain', 'restriction_type'), name='domain_restriction_type_uniq'),
        ),
        migrations.AddConstraint(
            model_name='emailuserrestriction',
            constraint=models.UniqueConstraint(fields=('email_pattern', 'restriction_type'), name='email_pattern_restriction_type_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ipnetworkuserrestriction',
            constraint=models.UniqueConstraint(fields=('network', 'restriction_type'), name='network_restriction_type_uniq'),
        ),
    ]
