# Generated by Django 4.2.24 on 2025-10-01 09:41

import django.core.validators
from django.db import migrations, models
import olympia.amo.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_tweak_restrictions_contraints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_public',
            new_name='has_full_profile',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2), olympia.amo.validators.OneOrMoreLetterOrNumberCharacterValidator()]),
        ),
    ]
