# Generated by Django 4.2.26 on 2025-11-20 11:59

from django.db import migrations, models
import django.utils.timezone
import olympia.amo.models
import olympia.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_is_public_userprofile_has_full_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('restriction_type', models.PositiveSmallIntegerField(choices=[(1, 'Add-on Submission'), (2, 'Add-on Approval'), (3, 'Rating'), (4, 'Rating Flag for Moderation')], default=1)),
                ('reason', models.CharField(blank=True, help_text='Private description of why this restriction was added.', max_length=255, null=True)),
                ('ja4', models.CharField(db_index=True, max_length=36)),
            ],
            options={
                'db_table': 'users_fingerprint_restriction',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model, olympia.users.models.RestrictionAbstractBase),
        ),
        migrations.AlterField(
            model_name='userrestrictionhistory',
            name='restriction',
            field=models.PositiveSmallIntegerField(choices=[(0, 'DeveloperAgreementRestriction'), (1, 'DisposableEmailDomainRestriction'), (2, 'EmailUserRestriction'), (3, 'IPNetworkUserRestriction'), (4, 'EmailReputationRestriction'), (5, 'IPReputationRestriction'), (6, 'FingerprintRestriction')], default=0),
        ),
        migrations.AddConstraint(
            model_name='fingerprintrestriction',
            constraint=models.UniqueConstraint(fields=('ja4', 'restriction_type'), name='ja4_restriction_type_uniq'),
        ),
    ]
