# Generated by Django 4.2.27 on 2026-01-19 09:44

from django.db import migrations


def null_blank_fxa_ids(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    qs = UserProfile.objects.filter(fxa_id='')
    qs.update(fxa_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_userprofile_email_userprofile_email'),
    ]

    operations = [
        migrations.RunPython(null_blank_fxa_ids, reverse_code=migrations.RunPython.noop)
    ]
