# Generated by Django 4.2.27 on 2026-01-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20260119_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fxa_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
