# Generated by Django 4.2.28 on 2026-03-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0042_alter_blockversion_block_type'),
        ('users', '0024_alter_userprofile_fxa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedusercontent',
            name='blocked_addons_submissions',
            field=models.ManyToManyField(to='blocklist.blocklistsubmission'),
        ),
    ]
