# Generated by Django 5.2.14 on 2026-06-12 17:16

import django.utils.timezone
import olympia.amo.models
import olympia.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_bannedusercontent_blocked_addons_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrestrictionhistory',
            name='restriction',
            field=models.PositiveSmallIntegerField(choices=[(0, 'DeveloperAgreementRestriction'), (1, 'DisposableEmailDomainRestriction'), (2, 'EmailUserRestriction'), (3, 'IPNetworkUserRestriction'), (4, 'EmailReputationRestriction'), (5, 'IPReputationRestriction'), (6, 'FingerprintRestriction'), (7, 'AsnUserRestriction')], default=0),
        ),
        migrations.CreateModel(
            name='AsnUserRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('restriction_type', models.PositiveSmallIntegerField(choices=[(1, 'Add-on Submission'), (2, 'Add-on Approval'), (3, 'Rating'), (4, 'Rating Flag for Moderation')], default=1)),
                ('reason', models.CharField(blank=True, help_text='Private description of why this restriction was added.', max_length=255, null=True)),
                ('asn', models.PositiveIntegerField(db_index=True)),
            ],
            options={
                'db_table': 'users_asn_restriction',
                'constraints': [models.UniqueConstraint(fields=('asn', 'restriction_type'), name='asn_restriction_type_uniq')],
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model, olympia.users.models.RestrictionAbstractBase),
        ),
    ]
