# Generated by Django 5.2.17 on 2026-08-25 14:53

import django.db.models.deletion
import olympia.amo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0026_alter_userrestrictionhistory_restriction_and_more'),
        ('versions', '0053_auto_20260720_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrestrictionhistory',
            name='restriction_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='userrestrictionhistory',
            name='restriction_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userrestrictionhistory',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restriction_history', to='versions.version'),
        ),
        migrations.AddIndex(
            model_name='userrestrictionhistory',
            index=olympia.amo.models.LongNameIndex(fields=['restriction_content_type', 'restriction_object_id'], name='users_userrestrictionhistory_restriction_content_type_object_id'),
        ),
    ]
