# Generated by Django 5.2.17 on 2026-08-24 16:23

import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0038_remove_enable_mv3_submissions_switch'),
        ('users', '0026_alter_userrestrictionhistory_restriction_and_more'),
        ('versions', '0053_auto_20260720_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrestrictionhistory',
            name='restriction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Add-on Submission'), (2, 'Add-on Approval'), (3, 'Rating'), (4, 'Rating Flag for Moderation')], null=True),
        ),
        migrations.AddField(
            model_name='userrestrictionhistory',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restriction_history', to='files.fileupload'),
        ),
        migrations.AddField(
            model_name='userrestrictionhistory',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restriction_history', to='versions.version'),
        ),
        migrations.CreateModel(
            name='UserRestrictionHistoryMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('snapshot', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='users.userrestrictionhistory')),
            ],
            options={
                'verbose_name_plural': 'User Restriction History Matches',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
