# Generated by Django 2.2.14 on 2020-07-15 18:38

from django.db import migrations, models
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('shelfType', models.CharField(choices=[('category', 'category'), ('collection', 'collection'), ('extension', 'extension'), ('recommended', 'recommended'), ('search', 'search'), ('theme', 'theme')], max_length=200, verbose_name='type')),
                ('criteria', models.CharField(help_text='e.g., search/?recommended=true&sort=random&type=extension', max_length=200)),
                ('footerText', models.CharField(default='See more', max_length=200, verbose_name='footer text')),
                ('footerPathname', models.CharField(help_text='e.g., collections/4757633/privacy-matters', max_length=1000, verbose_name='footer pathname')),
            ],
            options={
                'verbose_name_plural': 'shelves',
            },
            bases=(olympia.amo.models.SearchMixin, olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
