# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations, models
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Will be translated. `random-tag` shelves can use {tag} in the text, which will be substituted for the random tag selected.', max_length=70)),
                ('endpoint', models.CharField(choices=[('collections', 'collections'), ('search', 'search'), ('random-tag', 'random-tag')], db_column='shelf_type', max_length=20)),
                ('criteria', models.CharField(help_text='e.g., "?promoted=recommended&sort=random&type=extension" or the collection slug', max_length=200)),
                ('footer_text', models.CharField(blank=True, help_text='e.g., See more recommended extensions. Will be translated. `random-tag` shelves can use {tag} in the text, which will be substituted for the random tag selected.', max_length=70)),
                ('footer_pathname', models.CharField(blank=True, help_text='Can be set to override the default generated footer url/path to see more of the add-ons shown on the shelf. Leave blank otherwise', max_length=255)),
                ('addon_count', models.PositiveSmallIntegerField(default=0, help_text='0 means the default number (4, or 3 for themes) of add-ons will be included in shelf responses. Set to override.')),
                ('addon_type', models.PositiveIntegerField(choices=[(1, 'Extension'), (2, 'Deprecated Complete Theme'), (3, 'Dictionary'), (4, 'Deprecated Search Engine'), (5, 'Language Pack'), (6, 'Deprecated Language Pack (Add-on)'), (7, 'Deprecated Plugin'), (9, 'Deprecated LWT'), (10, 'Theme'), (12, 'Deprecated Site Permission')], db_column='addontype_id', default=1)),
                ('enabled', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'shelves',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
