# Generated by Django 2.2.14 on 2020-07-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelf',
            old_name='shelfType',
            new_name='shelf_type',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='footerPathname',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='footerText',
        ),
        migrations.AddField(
            model_name='shelf',
            name='footer_pathname',
            field=models.CharField(blank=True, help_text='e.g., collections/4757633/privacy-matters', max_length=255),
        ),
        migrations.AddField(
            model_name='shelf',
            name='footer_text',
            field=models.CharField(blank=True, help_text='e.g., See more recommended extensions', max_length=200),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='criteria',
            field=models.CharField(blank=True, help_text='e.g., search/?recommended=true&sort=random&type=extension', max_length=200),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
