# Generated by Django 2.2.14 on 2020-07-20 15:09

from django.db import migrations, models
import olympia.shelves.models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0002_auto_20200716_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='criteria',
            field=models.CharField(help_text='e.g., ?recommended=true&sort=random&type=extension', max_length=200,),
        ),
    ]
