# Generated by Django 2.2.15 on 2020-08-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0003_auto_20200720_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='shelf_type',
            field=models.CharField(choices=[('categories', 'categories'), ('collections', 'collections'), ('extension', 'extension'), ('recommended', 'recommended'), ('search', 'search'), ('theme', 'theme')], max_length=200, verbose_name='type'),
        ),
    ]
