# Generated by Django 2.2.15 on 2020-08-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0004_auto_20200805_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelf',
            name='shelf_type',
        ),
        migrations.AddField(
            model_name='shelf',
            name='endpoint',
            field=models.CharField(choices=[('collections', 'collections'), ('search', 'search')], max_length=200),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='criteria',
            field=models.CharField(help_text='e.g., ?sort=users&statictheme?recommended=true&sort=random&type=extensionpassword-managers', max_length=200),
        ),
    ]
