# Generated by Django 2.2.15 on 2020-08-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0004_auto_20200805_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='shelf_type',
            field=models.CharField(choices=[('collections', 'collections'), ('search', 'search')], db_column='shelf_type', max_length=200),
        ),
         migrations.RenameField(
            model_name='shelf',
            old_name='shelf_type',
            new_name='endpoint',
        ),
    ]
