# Generated by Django 2.2.15 on 2020-08-07 20:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0005_auto_20200807_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('shelf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shelves.Shelf')),
            ],
            options={
                'verbose_name_plural': 'homepage shelves',
            },
            bases=(olympia.amo.models.SearchMixin, olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
