# Generated by Django 2.2.15 on 2020-08-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0006_shelfmanagement'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shelfmanagement',
            constraint=models.UniqueConstraint(fields=('enabled', 'position'), name='position_id'),
        ),
    ]
