# Generated by Django 2.2.16 on 2020-10-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0007_auto_20200817_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='criteria',
            field=models.CharField(help_text='e.g., ?promoted=recommended&sort=random&type=extension', max_length=200),
        ),
    ]
