# Generated by Django 2.2.17 on 2021-01-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0008_auto_20201028_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='criteria',
            field=models.CharField(help_text='e.g., "?promoted=recommended&sort=random&type=extension" or the collection slug', max_length=200),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='endpoint',
            field=models.CharField(choices=[('collections', 'collections'), ('search', 'search'), ('search-themes', 'search-themes')], db_column='shelf_type', max_length=200),
        ),
    ]
