# Generated by Django 2.2.18 on 2021-02-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0010_shelf_addon_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='addon_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 means the default number (4, or 3 for search-themes) of add-ons will included be in shelf responses. Set to override.'),
        ),
    ]
