# Generated by Django 2.2.18 on 2021-02-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0011_auto_20210215_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelf',
            old_name='footer_pathname',
            new_name='footer_url',
        ),
    ]
