# Generated by Django 2.2.18 on 2021-02-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0011_auto_20210215_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='footer_text',
            field=models.CharField(blank=True, help_text='e.g., See more recommended extensions. Will be translated.', max_length=200),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='title',
            field=models.CharField(help_text='Will be translated.', max_length=200),
        ),
    ]
