# Generated by Django 2.2.19 on 2021-03-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0012_auto_20210218_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='addon_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 means the default number (4, or 3 for search-themes) of add-ons will be included in shelf responses. Set to override.'),
        ),
    ]
