# Generated by Django 2.2.20 on 2021-04-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0013_auto_20210325_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='addon_type',
            field=models.CharField(choices=[('extensions', 'extensions'), ('themes', 'themes')], default='extensions', max_length=200),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='addon_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 means the default number (4, or 3 for themes) of add-ons will be included in shelf responses. Set to override.'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='endpoint',
            field=models.CharField(choices=[('collections', 'collections'), ('search', 'search')], db_column='shelf_type', max_length=200),
        ),
    ]
