# Generated by Django 2.2.20 on 2021-04-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0013_auto_20210325_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='addon_type',
            field=models.PositiveIntegerField(choices=[(1, 'Extension'), (2, 'Deprecated Complete Theme'), (3, 'Dictionary'), (4, 'Search Engine'), (5, 'Language Pack (Application)'), (6, 'Language Pack (Add-on)'), (7, 'Plugin'), (9, 'Deprecated LWT'), (10, 'Theme (Static)')], db_column='addontype_id', default=1),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='addon_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 means the default number (4, or 3 for themes) of add-ons will be included in shelf responses. Set to override.'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='endpoint',
            field=models.CharField(choices=[('collections', 'collections'), ('search', 'search')], db_column='shelf_type', max_length=200),
        ),
    ]
