# Generated by Django 2.2.23 on 2021-06-17 11:13

from django.db import migrations, models


def truncate_columns_to_70(apps, schema_editor):
    Shelf = apps.get_model('shelves', 'Shelf')
    Shelf.objects.update(
        title=models.functions.Substr('title', 1, 70),
        footer_text=models.functions.Substr('footer_text', 1, 70),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0015_auto_20210422_1032'),
    ]

    operations = [
        migrations.RunPython(truncate_columns_to_70),
        migrations.AlterField(
            model_name='shelf',
            name='footer_text',
            field=models.CharField(blank=True, help_text='e.g., See more recommended extensions. Will be translated.', max_length=70),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='title',
            field=models.CharField(help_text='Will be translated.', max_length=70),
        ),
    ]
