# Generated by Django 3.2.4 on 2021-07-26 14:22

from django.db import migrations, models


def set_enabled_postion_from_management(apps, schema_editor):
    Shelf = apps.get_model('shelves', 'Shelf')

    for shelf in Shelf.objects.all():
        shelf.enabled = shelf.shelfmanagement.enabled
        shelf.position = shelf.shelfmanagement.position
        shelf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0016_auto_20210617_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelf',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='endpoint',
            field=models.CharField(choices=[('collections', 'collections'), ('search', 'search'), ('random-tag', 'random-tag')], db_column='shelf_type', max_length=20),
        ),
        migrations.RunPython(set_enabled_postion_from_management),
    ]
