# Generated by Django 3.2.4 on 2021-07-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0017_auto_20210726_1422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShelfManagement',
        ),
    ]
