# Generated by Django 3.2.6 on 2021-08-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0018_delete_shelfmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='footer_text',
            field=models.CharField(blank=True, help_text='e.g., See more recommended extensions. Will be translated. `random-tag` shelves can use {tag} in the text, which will be substituted for the random tag selected.', max_length=70),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='title',
            field=models.CharField(help_text='Will be translated. `random-tag` shelves can use {tag} in the text, which will be substituted for the random tag selected.', max_length=70),
        ),
    ]
