# Generated by Django 3.2.6 on 2021-08-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0019_auto_20210812_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='footer_pathname',
            field=models.CharField(blank=True, help_text='Can be set to override the default generated footer url/path to see more of the add-ons shown on the shelf. Leave blank otherwise', max_length=255),
        ),
    ]
