# Generated by Django 3.2.13 on 2022-05-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0020_alter_shelf_footer_pathname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='addon_type',
            field=models.PositiveIntegerField(choices=[(1, 'Extension'), (2, 'Deprecated Complete Theme'), (3, 'Dictionary'), (4, 'Search Engine'), (5, 'Language Pack (Application)'), (6, 'Language Pack (Add-on)'), (7, 'Plugin'), (9, 'Deprecated LWT'), (10, 'Theme (Static)'), (12, 'Site Permission')], db_column='addontype_id', default=1),
        ),
    ]
