# Generated by Django 4.2.24 on 2025-10-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0022_alter_shelf_addon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='addon_type',
            field=models.PositiveIntegerField(choices=[(1, 'Extension'), (2, 'Deprecated Complete Theme'), (3, 'Dictionary'), (4, 'Deprecated Search Engine'), (5, 'Language Pack'), (6, 'Deprecated Language Pack (Add-on)'), (7, 'Deprecated Plugin'), (9, 'Deprecated LWT'), (10, 'Theme'), (12, 'Deprecated Site Permission')], db_column='addontype_id', default=1),
        ),
    ]
