# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reindexing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_index', models.CharField(max_length=255, null=True)),
                ('new_index', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zadmin_reindexing',
            },
        ),
    ]
