# Generated by Django 3.2.6 on 2021-09-06 09:58

from django.db import migrations


def create_waffle_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.create(name='return-to-amo-for-all-listed', active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_remove-es-use-classic-similarity-waffle-switch'),
    ]

    operations = [migrations.RunPython(create_waffle_switch)]
