# Generated by Django 3.2.14 on 2022-07-20 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210906_0958'),
        ('es', '0004_delete_reindexing'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Reindexing',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_index', models.CharField(max_length=255, null=True)),
                ('new_index', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zadmin_reindexing',
            },
        ),
    ]

    # Only add Reindexing model, the database table should already exist as it
    # belonged to the lib.es app before.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[], state_operations=state_operations
        )
    ]
