from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    url('^$', views.landing, name='ecosystem.landing'),
    url('^partners$', views.partners, name='ecosystem.partners'),
    url('^support$', views.support, name='ecosystem.support'),
    url('^dev_phone$', views.dev_phone, name='ecosystem.dev_phone'),
    url('^docs/firefox_os_simulator$', views.firefox_os_simulator,
        name='ecosystem.firefox_os_simulator'),
    url('^docs/concept$', views.design_concept,
        name='ecosystem.design_concept'),
    url('^docs/fundamentals$', views.design_fundamentals,
        name='ecosystem.design_fundamentals'),
    url('^docs/ui_guidelines$', views.design_ui,
        name='ecosystem.design_ui'),
    url('^docs/patterns$', views.design_patterns,
        name='ecosystem.design_patterns'),
    url('^docs/review$', views.publish_review,
        name='ecosystem.publish_review'),
    url('^docs/deploy$', views.publish_deploy,
        name='ecosystem.publish_deploy'),
    url('^docs/hosted$', views.publish_hosted,
        name='ecosystem.publish_hosted'),
    url('^docs/packaged$', views.publish_packaged,
        name='ecosystem.publish_packaged'),
     url('^docs/submission$', views.publish_submit,
        name='ecosystem.publish_submit'),
    url('^docs/quick_start$', views.build_quick,
        name='ecosystem.build_quick'),
    url('^docs/intro_apps$', views.build_intro,
        name='ecosystem.build_intro'),
    url('^docs/reference_apps$', views.build_reference,
        name='ecosystem.build_reference'),
    url('^docs/firefox_os$', views.build_ffos,
        name='ecosystem.build_ffos'),
    url('^docs/manifests$', views.build_manifests,
        name='ecosystem.build_manifests'),
    url('^docs/tools$', views.build_tools,
        name='ecosystem.build_tools'),
    url('^docs/app_generator$', views.build_app_generator,
        name='ecosystem.build_app_generator'),
    url('^docs/apps_offline$', views.build_apps_offline,
        name='ecosystem.build_apps_offline'),
    url('^docs/game_apps$', views.build_game_apps,
        name='ecosystem.build_game_apps'),
    url('^docs/mobile_developers$', views.build_mobile_developers,
        name='ecosystem.build_mobile_developers'),
    url('^docs/web_developers$', views.build_web_developers,
        name='ecosystem.build_web_developers'),
    url('^docs/dev_tools$', views.build_dev_tools,
        name='ecosystem.build_dev_tools'),

    url('^docs/apps/(?P<page>\w+)?$', views.apps_documentation,
        name='ecosystem.apps_documentation'),
)
