from datetime import datetime

from django.conf import settings
from django.urls import reverse

from pyquery import PyQuery as pq

from olympia import amo
from olympia.amo.tests import TestCase, addon_factory, user_factory, version_factory
from olympia.reviewers.models import NeedsHumanReview
from olympia.versions.models import InstallOrigin, VersionProvenance


class TestVersionAdmin(TestCase):
    def setUp(self):
        self.addon = addon_factory()
        self.version = self.addon.current_version
        self.detail_url = reverse(
            'admin:versions_version_change', args=(self.version.pk,)
        )
        self.list_url = reverse('admin:versions_version_changelist')
        self.user = user_factory(email='someone@mozilla.com')
        self.grant_permission(self.user, 'Admin:Advanced')
        self.client.force_login(self.user)
        user_factory(pk=settings.TASK_USER_ID)

    def get_post_data(self, additional_post_data):
        post_data = {
            # Django wants the whole form to be submitted, unfortunately.
            'addon': self.addon.pk,
            'release_notes_en-us': '',
            'approval_notes': '',
            'license': self.version.license.pk,
            'source': {},
            'due_date_0': '2023-02-21',
            'due_date_1': '12:30:00',
            'reviewerflags-TOTAL_FORMS': '1',
            'reviewerflags-INITIAL_FORMS': '0',
            'reviewerflags-MIN_NUM_FORMS': '0',
            'reviewerflags-MAX_NUM_FORMS': '1',
            'reviewerflags-0-pending_rejection_0': '',
            'reviewerflags-0-pending_rejection_1': '',
            'reviewerflags-0-version': self.version.pk,
            'needshumanreview_set-TOTAL_FORMS': '0',
            'needshumanreview_set-INITIAL_FORMS': '0',
            'needshumanreview_set-MIN_NUM_FORMS': '0',
            'needshumanreview_set-MAX_NUM_FORMS': '1000',
            'versionprovenance_set-TOTAL_FORMS': '0',
            'versionprovenance_set-INITIAL_FORMS': '0',
            'versionprovenance_set-MIN_NUM_FORMS': '0',
            'versionprovenance_set-MAX_NUM_FORMS': '1000',
        }
        post_data.update(additional_post_data)
        return post_data

    def test_list_with_authorized_user(self):
        second_addon = addon_factory()
        version_factory(addon=second_addon)
        version_factory(addon=second_addon)
        with self.assertNumQueries(11):
            # - 2 savepoint/release
            # - 2 user and groups
            # - 1 count versions
            # - 1 select versions
            # - 1 select add-ons
            # - 1 add-on translations
            # - 1 versions translations
            # - 1 applications versions
            # - 1 addons promoted addons
            response = self.client.get(self.list_url, follow=True)
        assert response.status_code == 200

    def test_detail_with_authorized_user(self):
        response = self.client.get(self.detail_url, follow=True)
        assert response.status_code == 200

        doc = pq(response.content)
        assert doc('textarea#id_release_notes_0').length == 1

    def test_detail_with_authorized_user_including_version_provenance(self):
        VersionProvenance.objects.create(
            version=self.version,
            source=amo.UPLOAD_SOURCE_GENERATED,
            client_info='Blah/452',
        )
        response = self.client.get(self.detail_url, follow=True)
        assert response.status_code == 200

        doc = pq(response.content)
        assert (
            doc('#versionprovenance_set-0 .field-source label+div').text()
            == 'Automatically generated by AMO'
        )
        assert (
            doc('#versionprovenance_set-0 .field-client_info label+div').text()
            == 'Blah/452'
        )

    def test_unauthorized_user_has_no_access(self):
        user = user_factory(email='someoneelse@mozilla.com')
        self.client.force_login(user)
        response = self.client.get(self.detail_url, follow=True)
        assert response.status_code == 403

    def test_change_due_date(self):
        response = self.client.post(
            self.detail_url, self.get_post_data({}), follow=True
        )
        assert response.status_code == 200
        self.version.reload()
        assert self.version.due_date == datetime(2023, 2, 21, 12, 30)

    def test_new_needshumanreviewinline_is_saved(self):
        # Using default Django form, saving a new NeedsHumanReview through the
        # inline with no changes to the default values would not work. We have
        # a custom form to work around that issue.
        additional_post_data = {
            'needshumanreview_set-TOTAL_FORMS': '1',
            'needshumanreview_set-INITIAL_FORMS': '0',
            'needshumanreview_set-0-id': '',
            'needshumanreview_set-0-version': self.version.pk,
            'needshumanreview_set-0-is_active': 'on',
        }
        response = self.client.post(
            self.detail_url, self.get_post_data(additional_post_data), follow=True
        )
        assert response.status_code == 200
        self.version.reload()
        assert self.version.needshumanreview_set.count() == 1
        needs_human_review = self.version.needshumanreview_set.get()
        assert needs_human_review.reason == NeedsHumanReview.REASONS.UNKNOWN
        assert needs_human_review.is_active

    def test_existing_needshumanreviewinline_is_not_saved_if_no_changes(self):
        needs_human_review = NeedsHumanReview.objects.create(version=self.version)
        old_modified = self.days_ago(42)
        needs_human_review.update(modified=old_modified)
        self.version.update(modified=old_modified)
        additional_post_data = {
            'needshumanreview_set-TOTAL_FORMS': '1',
            'needshumanreview_set-INITIAL_FORMS': '1',
            'needshumanreview_set-0-id': needs_human_review.pk,
            'needshumanreview_set-0-version': self.version.pk,
            'needshumanreview_set-0-is_active': 'on',
        }
        response = self.client.post(
            self.detail_url, self.get_post_data(additional_post_data), follow=True
        )
        assert response.status_code == 200
        assert self.version.reload().modified != old_modified
        assert needs_human_review.reload().modified == old_modified
        assert needs_human_review.is_active

    def test_existing_needshumanreviewinline_is_saved_if_changes(self):
        needs_human_review = NeedsHumanReview.objects.create(version=self.version)
        old_modified = self.days_ago(42)
        needs_human_review.update(modified=old_modified)
        self.version.update(modified=old_modified)
        additional_post_data = {
            'due_date_0': '',
            'due_date_1': '',
            'needshumanreview_set-TOTAL_FORMS': '1',
            'needshumanreview_set-INITIAL_FORMS': '1',
            'needshumanreview_set-0-id': needs_human_review.pk,
            'needshumanreview_set-0-version': self.version.pk,
            'needshumanreview_set-0-is_active': '',
        }
        response = self.client.post(
            self.detail_url, self.get_post_data(additional_post_data), follow=True
        )
        assert response.status_code == 200
        assert self.version.reload().modified != old_modified
        assert needs_human_review.reload().modified != old_modified
        assert not needs_human_review.is_active


class TestInstallOriginAdmin(TestCase):
    def test_list(self):
        install_origin1 = InstallOrigin.objects.create(
            version=addon_factory().current_version,
            origin='https://one.example.com',
            base_domain='one.example.com',
        )
        install_origin2 = InstallOrigin.objects.create(
            version=addon_factory().current_version,
            origin='https://two.example.com',
            base_domain='two.example.com',
        )
        install_origin3 = InstallOrigin.objects.create(
            version=addon_factory().current_version,
            origin='https://three.example.com',
            base_domain='three.example.com',
        )
        list_url = reverse('admin:versions_installorigin_changelist')
        user = user_factory(email='someone@mozilla.com')
        self.grant_permission(user, '*:*')
        self.client.force_login(user)
        with self.assertNumQueries(6):
            # - 2 SAVEPOINTs
            # - 2 user & groups
            # - 1 count
            #     (show_full_result_count=False so we avoid the duplicate)
            # - 1 install origins
            response = self.client.get(list_url, follow=True)
        assert response.status_code == 200
        doc = pq(response.content)
        assert len(doc('#result_list tbody tr')) == 3
        assert doc('#result_list tbody tr:eq(2)').text() == '\n'.join(
            [
                str(install_origin1.id),
                install_origin1.version.addon.guid,
                install_origin1.version.version,
                install_origin1.origin,
                install_origin1.base_domain,
            ]
        )
        assert doc('#result_list tbody tr:eq(1)').text() == '\n'.join(
            [
                str(install_origin2.id),
                install_origin2.version.addon.guid,
                install_origin2.version.version,
                install_origin2.origin,
                install_origin2.base_domain,
            ]
        )
        assert doc('#result_list tbody tr:eq(0)').text() == '\n'.join(
            [
                str(install_origin3.id),
                install_origin3.version.addon.guid,
                install_origin3.version.version,
                install_origin3.origin,
                install_origin3.base_domain,
            ]
        )

    def test_add_disabled(self):
        add_url = reverse('admin:versions_installorigin_add')
        user = user_factory(email='someone@mozilla.com')
        self.grant_permission(user, '*:*')
        self.client.force_login(user)
        response = self.client.get(add_url, follow=True)
        assert response.status_code == 403

    def test_delete_disabled(self):
        install_origin = InstallOrigin.objects.create(
            version=addon_factory().current_version,
            origin='https://example.com',
            base_domain='example.com',
        )
        delete_url = reverse(
            'admin:versions_installorigin_delete', args=(install_origin.pk,)
        )
        user = user_factory(email='someone@mozilla.com')
        self.grant_permission(user, '*:*')
        self.client.force_login(user)
        response = self.client.get(delete_url, follow=True)
        assert response.status_code == 403

    def test_only_readonly_fields(self):
        install_origin = InstallOrigin.objects.create(
            version=addon_factory().current_version,
            origin='https://example.com',
            base_domain='example.com',
        )
        detail_url = reverse(
            'admin:versions_installorigin_change', args=(install_origin.pk,)
        )
        user = user_factory(email='someone@mozilla.com')
        self.grant_permission(user, '*:*')
        self.client.force_login(user)
        response = self.client.get(detail_url, follow=True)
        assert response.status_code == 200
        doc = pq(response.content)
        assert doc('#installorigin_form')
        assert not doc('#installorigin_form input:not([type=hidden])')
