# Generated by Django 3.2.14 on 2022-07-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0003_remove_reindexing_site'),
    ]

    database_operations = []

    state_operations = [migrations.DeleteModel('Reindexing')]

    # Only delete Reindexing as model from the lib.es app, but keep the
    # database intact - we're actually moving the model to a new app.
    # Fortunately there are no FKs or table renames to take care of...
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[], state_operations=state_operations
        )
    ]
