csv_keys = {
    locales: {
        "af":  gettext('Afrikaans'),
        "ak":  gettext('Akan'),
        "ast-ES":  gettext('Asturian'),
        "ar":  gettext('Arabic'),
        "as":  gettext('Assamese'),
        "be":  gettext('Belarusian'),
        "bg":  gettext('Bulgarian'),
        "bn-BD":  gettext('Bengali (Bangladesh)'),
        "bn-IN":  gettext('Bengali (India)'),
        "br-FR":  gettext('Breton'),
        "ca":  gettext('Catalan'),
        "ca-valencia":  gettext('Catalan (Valencian)'),
        "cs":  gettext('Czech'),
        "cy":  gettext('Welsh'),
        "da":  gettext('Danish'),
        "de":  gettext('German'),
        "de-AT":  gettext('German (Austria)'),
        "de-CH":  gettext('German (Switzerland)'),
        "de-DE":  gettext('German (Germany)'),
        "dsb":  gettext('Lower Sorbian'),
        "el":  gettext('Greek'),
        "en-AU":  gettext('English (Australian)'),
        "en-CA":  gettext('English (Canadian)'),
        "en-GB":  gettext('English (British)'),
        "en-NZ":  gettext('English (New Zealand)'),
        "en-US":  gettext('English (US)'),
        "en-ZA":  gettext('English (South African)'),
        "eo":  gettext('Esperanto'),
        "es-AR":  gettext('Spanish (Argentina)'),
        "es-CL":  gettext('Spanish (Chile)'),
        "es-ES":  gettext('Spanish (Spain)'),
        "es-MX":  gettext('Spanish (Mexico)'),
        "et":  gettext('Estonian'),
        "eu":  gettext('Basque'),
        "fa":  gettext('Persian'),
        "fi":  gettext('Finnish'),
        "fj-FJ":  gettext('Fijian'),
        "fr":  gettext('French'),
        "fur-IT":  gettext('Friulian'),
        "fy-NL":  gettext('Frisian'),
        "ga":  gettext('Irish'),
        "ga-IE":  gettext('Irish (Ireland)'),
        "gl":  gettext('Galician'),
        "gu-IN":  gettext('Gujarati'),
        "he":  gettext('Hebrew'),
        "hi":  gettext('Hindi'),
        "hi-IN":  gettext('Hindi (India)'),
        "hr":  gettext('Croatian'),
        "hsb":  gettext('Upper Sorbian'),
        "hu":  gettext('Hungarian'),
        "hy-AM":  gettext('Armenian'),
        "id":  gettext('Indonesian'),
        "is":  gettext('Icelandic'),
        "it":  gettext('Italian'),
        "ja":  gettext('Japanese'),
        "ja-JP-mac":  gettext('Japanese'),
        "ka":  gettext('Georgian'),
        "kk":  gettext('Kazakh'),
        "kn":  gettext('Kannada'),
        "ko":  gettext('Korean'),
        "ku":  gettext('Kurdish'),
        "la":  gettext('Latin'),
        "lt":  gettext('Lithuanian'),
        "lv":  gettext('Latvian'),
        "mg":  gettext('Malagasy'),
        "mi":  gettext('Maori (Aotearoa)'),
        "mk":  gettext('Macedonian'),
        "ml":  gettext('Malayalam'),
        "mn":  gettext('Mongolian'),
        "mr":  gettext('Marathi'),
        "nb-NO":  gettext('Norwegian (Bokm\u00e5l)'),
        "ne-NP":  gettext('Nepali'),
        "nn-NO":  gettext('Norwegian (Nynorsk)'),
        "nl":  gettext('Dutch'),
        "nr":  gettext('Ndebele, South'),
        "nso":  gettext('Northern Sotho'),
        "oc":  gettext('Occitan (Lengadocian)'),
        "or":  gettext('Oriya'),
        "pa-IN":  gettext('Punjabi'),
        "pl":  gettext('Polish'),
        "pt-BR":  gettext('Portuguese (Brazilian)'),
        "pt-PT":  gettext('Portuguese (Portugal)'),
        "ro":  gettext('Romanian'),
        "rm":  gettext('Romansh'),
        "ru":  gettext('Russian'),
        "rw":  gettext('Kinyarwanda'),
        "si":  gettext('Sinhala'),
        "sk":  gettext('Slovak'),
        "sl":  gettext('Slovenian'),
        "sq":  gettext('Albanian'),
        "sr":  gettext('Serbian'),
        "sr-Latn":  gettext('Serbian'),
        "ss":  gettext('Siswati'),
        "st":  gettext('Southern Sotho'),
        "sv-SE":  gettext('Swedish'),
        "ta":  gettext('Tamil'),
        "ta-IN":  gettext('Tamil (India)'),
        "ta-LK":  gettext('Tamil (Sri Lanka)'),
        "te":  gettext('Telugu'),
        "th":  gettext('Thai'),
        "tn":  gettext('Tswana'),
        "tr":  gettext('Turkish'),
        "ts":  gettext('Tsonga'),
        "tt-RU":  gettext('Tatar'),
        "uk":  gettext('Ukrainian'),
        "ur":  gettext('Urdu'),
        "ve":  gettext('Venda'),
        "vi":  gettext('Vietnamese'),
        "wo":  gettext('Wolof'),
        "xh":  gettext('Xhosa'),
        "zh-CN":  gettext('Chinese (Simplified)'),
        "zh-TW":  gettext('Chinese (Traditional)'),
        "zu":  gettext('Zulu')
    },
    os: {
        "WINNT": gettext('Windows'),
        "Darwin": gettext('Mac'),
        "null": gettext('unknown')
    },
    sources: {
        "null": gettext('unknown')
    },
    apps : {
        '{ec8030f7-c20a-464f-9b0e-13a3a9e97384}' : gettext('Firefox'),
        '{86c18b42-e466-45a9-ae7a-9b95ba6f5640}' : gettext('Mozilla'),
        '{3550f703-e582-4d05-9a08-453d09bdfdc6}' : gettext('Thunderbird'),
        '{718e30fb-e89b-41dd-9da7-e25a45638b28}' : gettext('Sunbird'),
        '{92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}' : gettext('SeaMonkey'),
        '{a23983c0-fd0e-11dc-95ff-0800200c9a66}' : gettext('Fennec')
    }
};