# Generated by Django 2.2.5 on 2019-09-12 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.fields
import olympia.amo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created', models.DateTimeField(blank=True,
                                                 default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', olympia.amo.fields.PositiveAutoField(
                    primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('rules', models.TextField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'groups',
            },
            bases=(olympia.amo.models.SearchMixin,
                   olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', olympia.amo.fields.PositiveAutoField(
                    primary_key=True, serialize=False)),
                ('group', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='access.Group')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_users',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(
                related_name='groups', through='access.GroupUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='groupuser',
            constraint=models.UniqueConstraint(
                fields=('group', 'user'), name='group_id'),
        ),
    ]
