# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.fields
import olympia.amo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('rules', models.TextField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'groups',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.group')),
            ],
            options={
                'db_table': 'groups_users',
            },
        ),
    ]
