# Generated by Django 3.2.14 on 2022-07-27 09:59

from django.db import migrations
from django.db.models import Q


def forwards_func(apps, schema_editor):
    Group = apps.get_model('access', 'Group')
    for group in Group.objects.filter(
        Q(rules__contains='Ratings:BypassThrottling')
        | Q(rules__contains='LanguagePack:Submit')
    ):
        rules = group.rules.split(',')
        rules.append('API:BypassThrottling')
        group.rules = ','.join(rules)
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
