# Generated by Django 4.2.21 on 2025-05-15 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_add_force_send_mail_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupuser',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='groupuser',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
