# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import olympia.amo.fields
import olympia.amo.models
import olympia.ratings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeniedRatingWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(help_text='Can only contain alphanumeric characters ("\\w", exc. "_"). If contains a "." it will be interpreted as a domain name instead, and can contain any character', max_length=255, unique=True, validators=[olympia.ratings.models.word_validator])),
                ('moderation', models.BooleanField(default=False, help_text='Flag for moderation rather than immediately deny.')),
            ],
            options={
                'db_table': 'reviews_denied_word',
                'ordering': ('word', 'moderation'),
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(None, 'None'), (0, '☆☆☆☆☆'), (1, '☆☆☆☆★'), (2, '☆☆☆★★'), (3, '☆☆★★★'), (4, '☆★★★★'), (5, '★★★★★')], null=True)),
                ('body', models.TextField(blank=True, db_column='text_body', max_length=4000, null=True)),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=45)),
                ('editorreview', models.BooleanField(default=False)),
                ('flag', models.BooleanField(default=False)),
                ('deleted', models.IntegerField(default=0)),
                ('is_latest', models.BooleanField(default=True, editable=False, help_text="Is this the user's latest rating for the add-on?")),
                ('previous_count', models.PositiveIntegerField(default=0, editable=False, help_text='How many previous ratings by the user for this add-on?')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ('-created',),
                'base_manager_name': 'unfiltered',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
            managers=[
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RatingAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('count_1', models.IntegerField(default=0)),
                ('count_2', models.IntegerField(default=0)),
                ('count_3', models.IntegerField(default=0)),
                ('count_4', models.IntegerField(default=0)),
                ('count_5', models.IntegerField(default=0)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RatingFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('flag', models.CharField(choices=[('review_flag_reason_spam', 'Spam or otherwise non-review content'), ('review_flag_reason_language', 'Inappropriate language/dialog'), ('review_flag_reason_bug_support', 'Misplaced bug report or support request'), ('review_flag_reason_other', 'Other (please specify)'), ('review_flag_reason_auto_match', 'Auto-flagged due to word match'), ('review_flag_reason_auto_user_restriction', 'Auto-flagged due to user restriction')], db_column='flag_name', default='review_flag_reason_other', max_length=64)),
                ('note', models.CharField(blank=True, db_column='flag_notes', default='', max_length=100)),
                ('rating', models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='ratings.rating')),
            ],
            options={
                'db_table': 'reviews_moderation_flags',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
