# Generated by Django 2.2.10 on 2020-03-29 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addons', '0005_Addded_RatingVote'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('vote', models.PositiveSmallIntegerField(choices=[(None, 'None'), (0, 'down_vote'), (1, 'up_vote')], null=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_votings', to='addons.Addon')),
                ('rating', models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='ratings.Rating')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating_vote',
            },
            bases=(olympia.amo.models.SearchMixin, olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='ratingvote',
            index=models.Index(fields=['user'], name='index_user'),
        ),
        migrations.AddIndex(
            model_name='ratingvote',
            index=models.Index(fields=['rating'], name='index_review'),
        ),
        migrations.AddIndex(
            model_name='ratingvote',
            index=models.Index(fields=['modified'], name='index_modified'),
        ),
        migrations.AddIndex(
            model_name='ratingvote',
            index=models.Index(fields=['addon'], name='addon_id'),
        ),
        migrations.AddConstraint(
            model_name='ratingvote',
            constraint=models.UniqueConstraint(fields=('rating', 'user'), name='index_review_user'),
        ),
    ]
