# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('versions', '0001_initial'),
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addons', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingflag',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingaggregate',
            name='addon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='addons.addon'),
        ),
        migrations.AddField(
            model_name='rating',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_ratings', to='addons.addon'),
        ),
        migrations.AddField(
            model_name='rating',
            name='reply_to',
            field=models.ForeignKey(db_column='reply_to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ratings.rating'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_ratings_all', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='versions.version'),
        ),
        migrations.AddIndex(
            model_name='ratingflag',
            index=models.Index(fields=['user'], name='index_user'),
        ),
        migrations.AddIndex(
            model_name='ratingflag',
            index=models.Index(fields=['rating'], name='index_review'),
        ),
        migrations.AddIndex(
            model_name='ratingflag',
            index=models.Index(fields=['modified'], name='index_modified'),
        ),
        migrations.AddConstraint(
            model_name='ratingflag',
            constraint=models.UniqueConstraint(fields=('rating', 'user'), name='index_review_user'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['version'], name='version_id'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user'], name='reviews_ibfk_2'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['addon'], name='reviews_addon_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['reply_to', 'is_latest', 'addon', 'created'], name='latest_reviews'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['ip_address'], name='reviews_ip_address_057fddfa'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('version', 'user', 'reply_to', 'deleted'), name='one_review_per_user'),
        ),
    ]
