# Generated by Django 2.2.11 on 2020-03-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_Addded_RatingVote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingvote',
            name='vote',
            field=models.SmallIntegerField(choices=[(-1, 'cleaned_vote'), (0, 'down_vote'), (1, 'up_vote')], null=True),
        ),
    ]
