# Generated by Django 3.2.6 on 2021-08-13 09:41

from django.db import migrations, models

from olympia.amo.migrations import RenameIndexesOperation


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_ratingaggregate'),
    ]

    operations = [
        RenameIndexesOperation(
            'reviews',
            [
                (
                    migrations.AddIndex(
                        model_name='rating',
                        index=models.Index(fields=['addon'], name='reviews_addon_idx'),
                    ),
                    'addon_id',
                ),
            ]
        ),
    ]
