# Generated by Django 3.2.6 on 2021-08-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_ratingaggregate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['addon'], name='reviews_addon_idx'),
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='addon_id',
        ),
    ]
