# Generated by Django 3.2.6 on 2021-08-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20210813_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=45),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['ip_address'], name='reviews_ip_address_057fddfa'),
        ),
    ]
