# Generated by Django 3.2.16 on 2022-11-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20210823_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='body',
            field=models.TextField(db_column='text_body', max_length=4000, null=True),
        ),
    ]
