# Generated by Django 3.2.15 on 2022-12-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_alter_rating_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='body',
            field=models.TextField(blank=True, db_column='text_body', max_length=4000, null=True),
        ),
    ]
