# Generated by Django 3.2.18 on 2023-03-24 10:53

from django.db import migrations, models
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_alter_rating_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeniedRatingWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=255, unique=True)),
                ('flag', models.BooleanField(default=True, help_text='Flag for moderation rather than immediately deny.')),
            ],
            options={
                'db_table': 'reviews_denied_word',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='ratingflag',
            name='flag',
            field=models.CharField(choices=[('review_flag_reason_spam', 'Spam or otherwise non-review content'), ('review_flag_reason_language', 'Inappropriate language/dialog'), ('review_flag_reason_bug_support', 'Misplaced bug report or support request'), ('review_flag_reason_auto_match', 'Auto-flagged due to word match'), ('review_flag_reason_other', 'Other (please specify)')], db_column='flag_name', default='review_flag_reason_other', max_length=64),
        ),
    ]
