# Generated by Django 4.2.1 on 2023-05-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ratings', '0007_auto_20230324_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deniedratingword',
            options={'ordering': ('word', 'moderation')},
        ),
        migrations.AlterField(
            model_name='ratingflag',
            name='flag',
            field=models.CharField(
                choices=[
                    ('review_flag_reason_spam', 'Spam or otherwise non-review content'),
                    ('review_flag_reason_language', 'Inappropriate language/dialog'),
                    (
                        'review_flag_reason_bug_support',
                        'Misplaced bug report or support request',
                    ),
                    ('review_flag_reason_other', 'Other (please specify)'),
                    ('review_flag_reason_auto_match', 'Auto-flagged due to word match'),
                    (
                        'review_flag_reason_auto_user_restriction',
                        'Auto-flagged due to user restriction',
                    ),
                ],
                db_column='flag_name',
                default='review_flag_reason_other',
                max_length=64,
            ),
        ),
    ]
