# Generated by Django 4.2.6 on 2023-10-27 10:17

from django.db import migrations, models
import olympia.ratings.models


class Migration(migrations.Migration):
    dependencies = [
        ('ratings', '0008_alter_deniedratingword_options_alter_ratingflag_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deniedratingword',
            name='word',
            field=models.CharField(
                help_text='Can only contain alphanumeric characters ("\\w", exc. "_"). If contains a "." it will be interpreted as a domain name instead, and can contain any character',
                max_length=255,
                unique=True,
                validators=[olympia.ratings.models.word_validator],
            ),
        ),
    ]
