# Generated by Django 4.2.6 on 2023-11-06 15:33

from django.db import migrations
from olympia import amo
from olympia.activity.models import ActivityLog
from django.db.models import F

def remove_flagged_rating_edit_log_activity(apps, schema_editor):
    ActivityLog.objects.filter(action=amo.LOG.EDIT_RATING.id).exclude(ratinglog__rating__user=F('user')).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0009_alter_deniedratingword_word"),
        ("activity", "0024_alter_activitylog_action"),
    ]

    operations = [
        migrations.RunPython(remove_flagged_rating_edit_log_activity),
    ]
