# Generated by Django 4.2.7 on 2023-11-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0010_auto_20231106_1533'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='one_review_per_user',
        ),
        migrations.AlterField(
            model_name='rating',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('version', 'user', 'reply_to', 'deleted'), name='one_review_per_user'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reply_to',
            field=models.ForeignKey(db_column='reply_to', null=True, on_delete=models.deletion.CASCADE, related_name='replies', to='ratings.rating'),
        ),
    ]
