# Generated by Django 2.2.14 on 2020-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotedaddon',
            name='application_id',
            field=models.SmallIntegerField(choices=[(1, 'Firefox'), (61, 'Firefox for Android')], null=True),
        ),
    ]
