# Generated by Django 2.2.14 on 2020-07-21 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0002_promotedaddon_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedaddon',
            name='addon',
            field=models.OneToOneField(help_text='Add-on id this item will point to (If you do not know the id, paste the slug instead and it will be transformed automatically for you. If you have access to the add-on admin page, you can use the magnifying glass to see all available add-ons.', on_delete=django.db.models.deletion.CASCADE, to='addons.Addon'),
        ),
        migrations.AlterField(
            model_name='promotedaddon',
            name='application_id',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'All'), (1, 'Firefox'), (61, 'Firefox for Android')], null=True, verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='promotedaddon',
            name='group_id',
            field=models.SmallIntegerField(choices=[(0, 'Not Promoted'), (1, 'Recommended'), (2, 'Verified - Tier 1'), (3, 'Verified - Tier 2'), (4, 'Line'), (5, 'Spotlight'), (6, 'Strategic')], default=0, help_text='Can be set to Not Promoted to disable promotion without deleting it.  Note: changing the group does *not* change approvals of versions.', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='promotedapproval',
            name='group_id',
            field=models.SmallIntegerField(choices=[(1, 'Recommended'), (2, 'Verified - Tier 1'), (3, 'Verified - Tier 2'), (4, 'Line'), (5, 'Spotlight'), (6, 'Strategic')], null=True, verbose_name='Group'),
        ),
    ]
