# Generated by Django 2.2.14 on 2020-07-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0003_auto_20200721_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedaddon',
            name='application_id',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'All Applications'), (1, 'Firefox'), (61, 'Firefox for Android')], null=True, verbose_name='Application'),
        ),
    ]
