# Generated by Django 2.2.16 on 2020-09-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0006_auto_20200819_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotedapproval',
            name='application_id',
            field=models.SmallIntegerField(choices=[(1, 'Firefox'), (61, 'Firefox for Android')], default=None, null=True, verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='promotedaddon',
            name='group_id',
            field=models.SmallIntegerField(choices=[(0, 'Not Promoted'), (1, 'Recommended'), (2, 'Sponsored'), (3, 'Verified'), (4, 'By Firefox'), (5, 'Spotlight'), (6, 'Strategic')], default=0, help_text='Can be set to Not Promoted to disable promotion without deleting it.  Note: changing the group does *not* change approvals of versions.', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='promotedapproval',
            name='group_id',
            field=models.SmallIntegerField(choices=[(1, 'Recommended'), (2, 'Sponsored'), (3, 'Verified'), (4, 'By Firefox'), (5, 'Spotlight')], null=True, verbose_name='Group'),
        ),
        migrations.RemoveConstraint(
            model_name='promotedapproval',
            name='unique_promoted_version',
        ),
        migrations.AddConstraint(
            model_name='promotedapproval',
            constraint=models.UniqueConstraint(fields=('group_id', 'version', 'application_id'), name='unique_promoted_version'),
        ),
    ]
