# Generated by Django 2.2.16 on 2020-09-24 13:29

from django.db import migrations

from olympia import amo


@amo.decorators.use_primary_db
def add_application_to_promoted_approvals(apps, schema_editor):
    PromotedApproval = apps.get_model('promoted', 'PromotedApproval')
    qs = PromotedApproval.objects.filter(application_id=None)
    for approval in qs:
        promo = getattr(approval.version.addon, 'promotedaddon', None)
        if not promo:
            continue
        if promo.application_id is None:
            approval.application_id = amo.FIREFOX.id
            approval.save()
            PromotedApproval.objects.create(
                version_id=approval.version_id,
                group_id=approval.group_id,
                application_id=amo.ANDROID.id,
            )
        else:
            approval.application_id = promo.application_id
        approval.save()


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0007_auto_20200924_1328'),
    ]

    operations = [
        migrations.RunPython(add_application_to_promoted_approvals)
    ]
