# Generated by Django 2.2.16 on 2020-10-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0008_auto_20200924_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotedTheme',
            fields=[
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'proxy': True,
                'base_manager_name': 'objects',
                'indexes': [],
                'constraints': [],
            },
            bases=('promoted.promotedaddon',),
        ),
    ]
