# Generated by Django 2.2.16 on 2020-10-16 14:48

from django.db import migrations


def create_waffle_switch(apps, schema_editor):
    Switch = apps.get_model("waffle", "Switch")

    Switch.objects.create(
        name="enable-subscriptions-for-promoted-addons",
        active=False,
        note="Enable the subscription feature for promoted add-ons.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("promoted", "0010_promotedsubscription"),
    ]

    operations = [migrations.RunPython(create_waffle_switch)]
