# Generated by Django 2.2.16 on 2020-10-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0011_create_switch_for_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotedsubscription',
            old_name='paid_at',
            new_name='payment_completed_at',
        ),
    ]
