# Generated by Django 2.2.16 on 2020-10-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promoted", "0013_auto_20201022_0906"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotedsubscription",
            name="onboarding_rate",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text=(
                    "If set, this rate will be used to charge the developer"
                    " for this subscription. The value should be a"
                    " non-negative integer in cents."
                ),
                null=True,
            ),
        ),
    ]
