# Generated by Django 2.2.17 on 2020-11-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promoted", "0015_promotedsubscription_stripe_subscription_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotedsubscription",
            name="onboarding_period",
            field=models.CharField(
                blank=True,
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                help_text=(
                    "If set, this billing period will be used for this"
                    " subscription. The default period configured in Stripe"
                    " for the promoted groupwill be used otherwise."
                ),
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="promotedsubscription",
            name="onboarding_rate",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text=(
                    "If set, this rate will be used to charge the developer"
                    " for this subscription. The value should be a"
                    " non-negative integer in cents. The default rate"
                    " configured in Stripe for the promoted group will be used"
                    " otherwise."
                ),
                null=True,
            ),
        ),
    ]
