# Generated by Django 2.2.17 on 2020-11-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promoted", "0016_auto_20201106_1355"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promotedsubscription",
            old_name="payment_cancelled_at",
            new_name="checkout_cancelled_at",
        ),
        migrations.RenameField(
            model_name="promotedsubscription",
            old_name="payment_completed_at",
            new_name="checkout_completed_at",
        ),
    ]
