# Generated by Django 2.2.17 on 2020-11-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promoted", "0017_auto_20201106_1507"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotedsubscription",
            name="cancelled_at",
            field=models.DateTimeField(
                help_text=(
                    "This date is set when the subscription has been"
                    " cancelled."
                ),
                null=True,
            ),
        ),
    ]
