# Generated by Django 2.2.19 on 2021-03-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0018_auto_20201106_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromotedSubscription',
        ),
    ]
