# Generated by Django 4.2.18 on 2025-02-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0021_auto_20240919_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedaddon',
            name='group_id',
            field=models.SmallIntegerField(choices=[(0, 'Not Promoted'), (1, 'Recommended'), (4, 'By Firefox'), (5, 'Spotlight'), (6, 'Strategic'), (7, 'Notable'), (8, 'Sponsored'), (9, 'Verified')], default=0, help_text='Can be set to Not Promoted to disable promotion without deleting it.  Note: changing the group does *not* change approvals of versions.', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='promotedapproval',
            name='group_id',
            field=models.SmallIntegerField(choices=[(0, 'Not Promoted'), (1, 'Recommended'), (4, 'By Firefox'), (5, 'Spotlight'), (6, 'Strategic'), (7, 'Notable'), (8, 'Sponsored'), (9, 'Verified')], null=True, verbose_name='Group'),
        ),
    ]
