# Generated by Django 4.2.16 on 2024-11-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0053_alter_addon_summary_alter_addon_type'),
        ('promoted', '0021_auto_20240919_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedaddon',
            name='addon',
            field=models.ForeignKey(help_text='Add-on id this item will point to (If you do not know the id, paste the slug instead and it will be transformed automatically for you. If you have access to the add-on admin page, you can use the magnifying glass to see all available add-ons.', on_delete=django.db.models.deletion.CASCADE, related_name='promoted_addons', to='addons.addon'),
        ),
    ]
