# Generated by Django 4.2.18 on 2025-02-04 19:21
from collections import namedtuple

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models
from olympia.constants import applications
from olympia.constants.promoted import PROMOTED_GROUP_CHOICES

_PromotedSuperClass = namedtuple(
    '_PromotedSuperClass',
    [
        # Be careful when adding to this list to adjust defaults too.
        'id',
        'name',
        'api_name',
        'search_ranking_bump',
        'listed_pre_review',
        'unlisted_pre_review',
        'admin_review',
        'badged',  # See BADGE_CATEGORIES in frontend too: both need changing
        'autograph_signing_states',
        'can_primary_hero',  # can be added to a primary hero shelf
        'immediate_approval',  # will addon be auto-approved once added
        'flag_for_human_review',  # will be add-on be flagged for another review
        'can_be_compatible_with_all_fenix_versions',  # If addon is promoted for Android
        'high_profile',  # the add-on is considered high-profile for review purposes
        'high_profile_rating',  # developer replies are considered high-profile
    ],
    defaults=(
        # "Since fields with a default value must come after any fields without
        # a default, the defaults are applied to the rightmost parameters"
        # No defaults for: id, name, api_name.
        0.0,  # search_ranking_bump
        False,  # listed_pre_review
        False,  # unlisted_pre_review
        False,  # admin_review
        False,  # badged
        {},  # autograph_signing_states - should be a dict of App.short: state
        False,  # can_primary_hero
        False,  # immediate_approval
        False,  # flag_for_human_review
        False,  # can_be_compatible_with_all_fenix_versions
        False,  # high_profile
        False,  # high_profile_rating
    ),
)


class PromotedClass(_PromotedSuperClass):
    __slots__ = ()

    def __bool__(self):
        return bool(self.id)


RECOMMENDED = PromotedClass(
    id=PROMOTED_GROUP_CHOICES.RECOMMENDED,
    name='Recommended',
    api_name=PROMOTED_GROUP_CHOICES.RECOMMENDED.api_value,
    search_ranking_bump=5.0,
    listed_pre_review=True,
    badged=True,
    autograph_signing_states={
        applications.FIREFOX.short: 'recommended',
        applications.ANDROID.short: 'recommended-android',
    },
    can_primary_hero=True,
    can_be_compatible_with_all_fenix_versions=True,
    high_profile=True,
    high_profile_rating=True,
)

LINE = PromotedClass(
    id=PROMOTED_GROUP_CHOICES.LINE,
    name='By Firefox',
    api_name=PROMOTED_GROUP_CHOICES.LINE.api_value,
    search_ranking_bump=5.0,
    listed_pre_review=True,
    admin_review=True,
    badged=True,
    autograph_signing_states={
        applications.FIREFOX.short: 'line',
        applications.ANDROID.short: 'line',
    },
    can_primary_hero=True,
    can_be_compatible_with_all_fenix_versions=True,
    high_profile=True,
    high_profile_rating=True,
)

SPOTLIGHT = PromotedClass(
    id=PROMOTED_GROUP_CHOICES.SPOTLIGHT,
    name='Spotlight',
    api_name=PROMOTED_GROUP_CHOICES.SPOTLIGHT.api_value,
    listed_pre_review=True,
    admin_review=True,
    can_primary_hero=True,
    immediate_approval=True,
    high_profile=True,
)

STRATEGIC = PromotedClass(
    id=PROMOTED_GROUP_CHOICES.STRATEGIC,
    name='Strategic',
    api_name=PROMOTED_GROUP_CHOICES.STRATEGIC.api_value,
    admin_review=True,
)

NOTABLE = PromotedClass(
    id=PROMOTED_GROUP_CHOICES.NOTABLE,
    name='Notable',
    api_name=PROMOTED_GROUP_CHOICES.NOTABLE.api_value,
    listed_pre_review=True,
    unlisted_pre_review=True,
    flag_for_human_review=True,
    high_profile=True,
)

PARTNER = PromotedClass(
    id=PROMOTED_GROUP_CHOICES.PARTNER,
    name='Partner',
    api_name=PROMOTED_GROUP_CHOICES.PARTNER.api_value,
    listed_pre_review=True,
    unlisted_pre_review=True,
    high_profile=True,
    high_profile_rating=True,
)

PROMOTED_GROUPS = [
    RECOMMENDED,
    LINE,
    SPOTLIGHT,
    STRATEGIC,
    NOTABLE,
    PARTNER,
]

def create_promoted_groups(apps, schema_editor):
    PromotedGroup = apps.get_model('promoted', 'PromotedGroup')
    # Import legacy promoted groups from constants

    # Loop over all groups (active and inactive) from PROMOTED_GROUPS_BY_ID
    for group in PROMOTED_GROUPS:
        PromotedGroup.objects.create(
            group_id=group.id,
            name=group.name,
            api_name=group.api_name,
            search_ranking_bump=group.search_ranking_bump,
            listed_pre_review=group.listed_pre_review,
            unlisted_pre_review=group.unlisted_pre_review,
            admin_review=group.admin_review,
            badged=group.badged,
            autograph_signing_states=group.autograph_signing_states,
            can_primary_hero=group.can_primary_hero,
            immediate_approval=group.immediate_approval,
            flag_for_human_review=group.flag_for_human_review,
            can_be_compatible_with_all_fenix_versions=group.can_be_compatible_with_all_fenix_versions,
            high_profile=group.high_profile,
            high_profile_rating=group.high_profile_rating,
            # We only include actively promoted groups so we can hardcode to true
            active=True,
        )


def reverse_promoted_groups(apps, schema_editor):
    PromotedGroup = apps.get_model('promoted', 'PromotedGroup')
    PromotedGroup.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0022_alter_promotedaddon_group_id_and_more'),
    ]

    operations = [
        # 1. Create the new models
        migrations.CreateModel(
            name='PromotedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.SmallIntegerField(choices=[(0, 'Not Promoted'), (1, 'Recommended'), (4, 'By Firefox'), (5, 'Spotlight'), (6, 'Strategic'), (7, 'Notable'), (8, 'Sponsored'), (9, 'Verified')], help_text='The legacy  ID from back when promoted groups were static classes')),
                ('name', models.CharField(help_text='Human-readable name for the promotion group.', max_length=255)),
                ('api_name', models.CharField(help_text='Programmatic API name for the promotion group.', max_length=100)),
                ('search_ranking_bump', models.FloatField(default=0.0, help_text='Boost value used to influence search ranking for add-ons in this group.')),
                ('listed_pre_review', models.BooleanField(default=False, help_text='Indicates if listed versions require pre-review.')),
                ('unlisted_pre_review', models.BooleanField(default=False, help_text='Indicates if unlisted versions require pre-review.')),
                ('admin_review', models.BooleanField(default=False, help_text='Specifies whether the promotion requires administrative review.')),
                ('badged', models.BooleanField(default=False, help_text='Specifies if the add-on receives a badge upon promotion.')),
                ('autograph_signing_states', models.JSONField(default=dict, help_text='Mapping of application shorthand to autograph signing states.')),
                ('can_primary_hero', models.BooleanField(default=False, help_text='Determines if the add-on can be featured in a primary hero shelf.')),
                ('immediate_approval', models.BooleanField(default=False, help_text='If true, add-ons are auto-approved upon saving.')),
                ('flag_for_human_review', models.BooleanField(default=False, help_text='If true, add-ons are flagged for manual human review.')),
                ('can_be_compatible_with_all_fenix_versions', models.BooleanField(default=False, help_text='Determines compatibility with all Fenix (Android) versions.')),
                ('high_profile', models.BooleanField(default=False, help_text='Indicates if the add-on is high-profile for review purposes.')),
                ('high_profile_rating', models.BooleanField(default=False, help_text='Indicates if developer replies are treated as high-profile.')),
                ('active', models.BooleanField(default=False, help_text='Marks whether this promotion group is active (inactive groups are considered obsolete).')),
            ],
        ),
        migrations.CreateModel(
            name='PromotedAddonPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('application_id', models.SmallIntegerField(choices=[(1, 'Firefox'), (61, 'Firefox for Android')], verbose_name='Application')),
                ('addon', models.ForeignKey(help_text='Add-on id this item will point to (If you do not know the id, paste the slug instead and it will be transformed automatically for you. If you have access to the add-on admin page, you can use the magnifying glass to see all available add-ons.', on_delete=django.db.models.deletion.CASCADE, to='addons.addon')),
                ('promoted_group', models.ForeignKey(help_text='Can be set to Not Promoted to disable promotion without deleting it.  Note: changing the group does *not* change approvals of versions.', on_delete=django.db.models.deletion.CASCADE, to='promoted.promotedgroup')),
            ],
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PromotedAddonVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('promoted_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_versions', to='promoted.promotedgroup')),
                ('application_id', models.SmallIntegerField(choices=[(1, 'Firefox'), (61, 'Firefox for Android')], verbose_name='Application')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_versions', to='versions.version')),
            ],
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        # 2. Add constraints on the new tables that match the legacy tables.
        # This is to support full sync compatibility between the two models
        # until we have ported all code references to the new models.
        migrations.AddConstraint(
            model_name='promotedaddonpromotion',
            constraint=models.UniqueConstraint(fields=('addon', 'application_id'), name='unique_promoted_addon_application'),
        ),
        migrations.AddConstraint(
            model_name='promotedaddonversion',
            constraint=models.UniqueConstraint(fields=('promoted_group', 'application_id', 'version'), name='unique_promoted_addon_version'),
        ),
        # 3. Finally we can populate the PromotedGroup instances since they
        # are static and do not frequently change.
        migrations.RunPython(create_promoted_groups, reverse_promoted_groups),
    ]
