# Generated by Django 4.2.18 on 2025-02-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0023_promotedgroup_alter_promotedaddon_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedaddonpromotion',
            name='application_id',
            field=models.SmallIntegerField(choices=[(1, 'Firefox'), (61, 'Firefox for Android')], null=True, verbose_name='Application'),
        ),
    ]
