# Generated by Django 4.2.20 on 2025-03-26 18:09

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0054_update_default_locale_es_to_es-es'),
        ('promoted', '0023_promotedgroup_alter_promotedaddon_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedaddonpromotion',
            name='promoted_group',
            field=models.ForeignKey(help_text='The promotion can be deleted to disable promotion. Note: changing the group does *not* change approvals of versions.', on_delete=django.db.models.deletion.CASCADE, to='promoted.promotedgroup'),
        ),
    ]
