# Generated by Django 4.2.18 on 2025-02-25 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0023_promotedgroup_alter_promotedaddon_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedaddonpromotion',
            name='addon',
            field=models.ForeignKey(help_text='Add-on id this item will point to (If you do not know the id, paste the slug instead and it will be transformed automatically for you. If you have access to the add-on admin page, you can use the magnifying glass to see all available add-ons.', on_delete=django.db.models.deletion.CASCADE, related_name='promotedaddonpromotion', to='addons.addon'),
        ),
        migrations.AlterField(
            model_name='promotedaddonpromotion',
            name='application_id',
            field=models.SmallIntegerField(choices=[(1, 'Firefox'), (61, 'Firefox for Android')], null=True, verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='promotedgroup',
            name='group_id',
            field=models.SmallIntegerField(choices=[(0, 'Not Promoted'), (1, 'Recommended'), (4, 'By Firefox'), (5, 'Spotlight'), (6, 'Strategic'), (7, 'Notable'), (8, 'Sponsored'), (9, 'Verified')], help_text='The legacy ID from back when promoted groups were static classes'),
        ),
    ]
