# Generated by Django 4.2.20 on 2025-04-01 16:39

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0054_update_default_locale_es_to_es-es'),
        ('promoted', '0026_auto_20250401_1656'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promotedaddonpromotion',
            name='unique_promoted_addon_application',
        ),
        migrations.AddConstraint(
            model_name='promotedaddonpromotion',
            constraint=models.UniqueConstraint(fields=('addon', 'promoted_group', 'application_id'), name='unique_addon_promotion_application'),
        ),
    ]
