# Generated by Django 4.2.20 on 2025-04-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0054_update_default_locale_es_to_es-es'),
        ('hero', '0021_remove_primaryhero_promoted_addon'),
        ('promoted', '0027_alter_promotedaddonpromotion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotedaddon',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='promotedapproval',
            name='version',
        ),
        migrations.DeleteModel(
            name='PromotedTheme',
        ),
        migrations.DeleteModel(
            name='PromotedAddon',
        ),
        migrations.DeleteModel(
            name='PromotedApproval',
        ),
        migrations.RenameModel('PromotedAddonPromotion', 'PromotedAddon')
    ]
