# Generated by Django 4.2.20 on 2025-04-25 19:48

from django.db import migrations

from olympia.constants.promoted import PROMOTED_GROUP_CHOICES

PROMOTED_GROUPS_TO_UPDATE = [PROMOTED_GROUP_CHOICES.STRATEGIC, 
                             PROMOTED_GROUP_CHOICES.NOTABLE]

def update_public_promoted_groups(apps, schema_editor):
    PromotedGroup = apps.get_model('promoted', 'PromotedGroup')
    for group_id in PROMOTED_GROUPS_TO_UPDATE:
        group = PromotedGroup.objects.get(group_id=group_id)
        group.is_public = False
        group.save()

def reverse_public_promoted_group(apps, schema_editor):
    PromotedGroup = apps.get_model('promoted', 'PromotedGroup')
    for group_id in PROMOTED_GROUPS_TO_UPDATE:
        group = PromotedGroup.objects.get(group_id=group_id)
        group.is_public = True
        group.save()

class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0027_alter_promotedaddonpromotion_options_and_more'),
    ]

    operations = [
        migrations.RunPython(update_public_promoted_groups, reverse_public_promoted_group)
    ]
