# Generated by Django 4.2.20 on 2025-04-29 13:15

from django.db import migrations

from olympia.constants.promoted import PROMOTED_GROUP_CHOICES

def set_partner_group_high_profile_rating(apps, schema_editor):
    PromotedGroup = apps.get_model('promoted', 'PromotedGroup')
    try: 
        group = PromotedGroup.objects.get(group_id=PROMOTED_GROUP_CHOICES.PARTNER)
        group.high_profile_rating = True
        group.save()
    except PromotedGroup.DoesNotExist:
        pass


def reverse_partner_group_high_profile_rating(apps, schema_editor):
    PromotedGroup = apps.get_model('promoted', 'PromotedGroup')
    try:
        group = PromotedGroup.objects.get(group_id=PROMOTED_GROUP_CHOICES.PARTNER)
        group.high_profile_rating = False
        group.save()
    except PromotedGroup.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0028_auto_20250425_1948'),
    ]

    operations = [
        migrations.RunPython(set_partner_group_high_profile_rating, reverse_partner_group_high_profile_rating)
    ]
