# Generated by Django 4.2.20 on 2025-05-01 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0016_delete_promotedaddon_discoveryaddon_and_more'),
        ('addons', '0054_update_default_locale_es_to_es-es'),
        ('promoted', '0029_auto_20250429_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromotedTheme',
        ),
        migrations.DeleteModel(
            name='PromotedAddon',
        ),
        migrations.DeleteModel(
            name='PromotedApproval',
        ),
    ]
