# Generated by Django 4.2.21 on 2025-05-15 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0048_alter_version_release_notes'),
        ('addons', '0055_alter_addon_description_and_more'),
        ('promoted', '0030_remove_promotedaddon_addon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotedAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('application_id', models.SmallIntegerField(choices=[(1, 'Firefox'), (61, 'Firefox for Android')], verbose_name='Application')),
                ('addon', models.ForeignKey(help_text='Add-on id this item will point to (If you do not know the id, paste the slug instead and it will be transformed automatically for you. If you have access to the add-on admin page, you can use the magnifying glass to see all available add-ons.', on_delete=django.db.models.deletion.CASCADE, related_name='promotedaddon', to='addons.addon')),
            ],
            options={
                'db_table': 'promoted_promotedaddonpromotion',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.RenameModel(
            old_name='PromotedAddonVersion',
            new_name='PromotedApproval',
        ),
        migrations.AlterField(
            model_name='promotedgroup',
            name='group_id',
            field=models.SmallIntegerField(choices=[(0, 'Not Promoted'), (1, 'Recommended'), (4, 'By Firefox'), (5, 'Spotlight'), (6, 'Strategic'), (7, 'Notable'), (8, 'Sponsored'), (9, 'Verified'), (10, 'Partner')], help_text='The legacy ID from back when promoted groups were static classes'),
        ),
        migrations.AlterModelTable(
            name='promotedapproval',
            table='promoted_promotedaddonversion',
        ),
        migrations.DeleteModel(
            name='PromotedAddonPromotion',
        ),
        migrations.AddField(
            model_name='promotedaddon',
            name='promoted_group',
            field=models.ForeignKey(help_text='The promotion can be deleted to disable promotion.Note: changing the group does *not* change approvals of versions.', on_delete=django.db.models.deletion.CASCADE, to='promoted.promotedgroup'),
        ),
        migrations.AddConstraint(
            model_name='promotedaddon',
            constraint=models.UniqueConstraint(fields=('addon', 'promoted_group', 'application_id'), name='unique_addon_promotion_application'),
        ),
    ]
