# Generated by Django 4.2.21 on 2025-05-26 12:00

from django.db import migrations

from olympia.constants.promoted import PROMOTED_GROUP_CHOICES

def set_partner_group_pre_review(apps, schema_editor):
    PromotedGroup = apps.get_model('promoted', 'PromotedGroup')
    try:
        group = PromotedGroup.objects.get(group_id=PROMOTED_GROUP_CHOICES.PARTNER)
        group.listed_pre_review = True
        group.unlisted_pre_review = True
        group.save()
    except PromotedGroup.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0030_remove_promotedaddon_addon_and_more'),
    ]

    operations = [
        migrations.RunPython(set_partner_group_pre_review)
    ]
