# Generated by Django 4.2.20 on 2025-05-02 18:59

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0047_auto_20241031_1750'),
        ('addons', '0054_update_default_locale_es_to_es-es'),
        ('promoted', '0030_remove_promotedaddon_addon_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PromotedAddonPromotion',
            new_name='PromotedAddon',
        ),
        migrations.RenameModel(
            old_name='PromotedAddonVersion',
            new_name='PromotedApproval',
        ),
    ]
