# Generated by Django 4.2.23 on 2025-08-21 13:29

from django.db import migrations

def remove_not_promoted_promoted_group(apps, schema_editor):
    PromotedGroup = apps.get_model('promoted', 'PromotedGroup')
    try:
        group = PromotedGroup.objects.get(group_id=0)
        group.delete()
    except PromotedGroup.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0031_auto_20250526_1200'),
    ]

    operations = [
        migrations.RunPython(remove_not_promoted_promoted_group)
    ]
