# Generated by Django 4.2.24 on 2025-10-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0048_alter_version_release_notes'),
        ('addons', '0057_alter_addon_description_and_more'),
        ('promoted', '0032_auto_20250821_1329'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='promotedaddonversion',
            table='promoted_promotedaddonversion',
        ),
        migrations.RenameModel(
            old_name='PromotedAddonVersion',
            new_name='PromotedApproval',
        ),
        migrations.AlterField(
            model_name='promotedgroup',
            name='group_id',
            field=models.SmallIntegerField(choices=[(1, 'Recommended'), (4, 'By Firefox'), (5, 'Spotlight'), (6, 'Strategic'), (7, 'Notable'), (8, 'Sponsored'), (9, 'Verified'), (10, 'Partner')], help_text='The legacy ID from back when promoted groups were static classes'),
        ),
    ]
