# Generated by Django 4.2.24 on 2025-10-01 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0034_rename_promotedaddonpromotion_to_promotedaddon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedaddon',
            name='promoted_group',
            field=models.ForeignKey(help_text='The promotion can be deleted to disable promotion.Note: changing the group does *not* change approvals of versions.', on_delete=django.db.models.deletion.CASCADE, to='promoted.promotedgroup'),
        ),
    ]
