# Generated by Django 5.2.15 on 2026-07-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0035_alter_promotedaddon_promoted_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedgroup',
            name='api_name',
            field=models.CharField(help_text='Programmatic API name for the promotion group.', max_length=100, unique=True),
        ),
    ]
