# Generated by Django 5.2.15 on 2026-07-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0036_alter_promotedgroup_api_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedgroup',
            name='active',
            field=models.BooleanField(default=False, help_text='Marks whether this promotion group is active (inactive groups are considered obsolete).', null=True),
        ),
        migrations.AlterField(
            model_name='promotedgroup',
            name='group_id',
            field=models.SmallIntegerField(help_text='The legacy ID from back when promoted groups were static classes', null=True),
        ),
    ]
