# Generated by Django 5.2.15 on 2026-07-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoted', '0036_alter_promotedgroup_api_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotedgroup',
            name='group_id',
        ),
    ]
