# These are all languages - both languages that do meet the threshold for being
# available on AMO prod, and ones that don't - see PROD_LANGUAGES.
# Where a language is not in AMO_LANGUAGES, we don't offer translations but they may
# still be used to show that language a locale code maps to, for instance in statistics
# views.
ALL_LANGUAGES = {
    'ach': {'english': 'Acholi', 'native': 'Acholi'},
    'af': {'english': 'Afrikaans', 'native': 'Afrikaans'},
    'ak': {'english': 'Akan', 'native': 'Akan'},
    'am': {'english': 'Amharic', 'native': 'አማርኛ'},
    'an': {'english': 'Aragonese', 'native': 'aragonés'},
    'ar': {'english': 'Arabic', 'native': 'عربي'},
    'as': {'english': 'Assamese', 'native': 'অসমীয়া'},
    'ast': {'english': 'Asturian', 'native': 'Asturianu'},
    'az': {'english': 'Azerbaijani', 'native': 'Azərbaycanca'},
    'azz': {
        'english': 'Highland Puebla Nahuatl',
        'native': 'nahuatl sierra norte Puebla',
    },
    'be': {'english': 'Belarusian', 'native': 'Беларуская'},
    'bg': {'english': 'Bulgarian', 'native': 'Български'},
    'bm': {'english': 'Bambara', 'native': 'Bamanankan'},
    'bn': {'english': 'Bengali', 'native': 'বাংলা'},
    'br': {'english': 'Breton', 'native': 'Brezhoneg'},
    'brx': {'english': 'Bodo', 'native': "बर'"},
    'bs': {'english': 'Bosnian', 'native': 'Bosanski'},
    'ca': {'english': 'Catalan', 'native': 'Català'},
    'ca-valencia': {'english': 'Catalan (Valencian)', 'native': 'català (valencià)'},
    'cak': {'english': 'Kaqchikel', 'native': 'Maya Kaqchikel'},
    'cs': {'english': 'Czech', 'native': 'Čeština'},
    'csb': {'english': 'Kashubian', 'native': 'Kaszëbsczi'},
    'cy': {'english': 'Welsh', 'native': 'Cymraeg'},
    'da': {'english': 'Danish', 'native': 'Dansk'},
    'de': {'english': 'German', 'native': 'Deutsch'},
    'de-AT': {'english': 'German (Austria)', 'native': 'Deutsch (Österreich)'},
    'de-CH': {'english': 'German (Switzerland)', 'native': 'Deutsch (Schweiz)'},
    'de-DE': {'english': 'German (Germany)', 'native': 'Deutsch (Deutschland)'},
    'dsb': {'english': 'Lower Sorbian', 'native': 'Dolnoserbšćina'},
    'ee': {'english': 'Ewe', 'native': 'Eʋe'},
    'el': {'english': 'Greek', 'native': 'Ελληνικά'},
    'en-AU': {'english': 'English (Australian)', 'native': 'English (Australian)'},
    'en-CA': {'english': 'English (Canadian)', 'native': 'English (Canadian)'},
    'en-GB': {'english': 'English (British)', 'native': 'English (British)'},
    'en-NZ': {'english': 'English (New Zealand)', 'native': 'English (New Zealand)'},
    'en-US': {'english': 'English (US)', 'native': 'English (US)'},
    'en-ZA': {
        'english': 'English (South African)',
        'native': 'English (South African)',
    },
    'eo': {'english': 'Esperanto', 'native': 'Esperanto'},
    'es-AR': {'english': 'Spanish (Argentina)', 'native': 'Español (de Argentina)'},
    'es-CL': {'english': 'Spanish (Chile)', 'native': 'Español (de Chile)'},
    'es-ES': {'english': 'Spanish (Spain)', 'native': 'Español (de España)'},
    'es-MX': {'english': 'Spanish (Mexico)', 'native': 'Español (de México)'},
    'et': {'english': 'Estonian', 'native': 'Eesti keel'},
    'eu': {'english': 'Basque', 'native': 'Euskara'},
    'fa': {'english': 'Persian', 'native': 'فارسی'},
    'ff': {'english': 'Fulah', 'native': 'Pulaar-Fulfulde'},
    'fi': {'english': 'Finnish', 'native': 'suomi'},
    'fj-FJ': {'english': 'Fijian', 'native': 'Vosa vaka-Viti'},
    'fr': {'english': 'French', 'native': 'Français'},
    'fur': {'english': 'Friulian', 'native': 'Furlan'},
    'fy-NL': {'english': 'Frisian', 'native': 'Frysk'},
    'ga-IE': {'english': 'Irish', 'native': 'Gaeilge'},
    'gd': {'english': 'Gaelic (Scotland)', 'native': 'Gàidhlig'},
    'gl': {'english': 'Galician', 'native': 'Galego'},
    'gn': {'english': 'Guarani', 'native': "Avañe'ẽ"},
    'gu': {'english': 'Gujarati', 'native': 'ગુજરાતી'},
    'gu-IN': {'english': 'Gujarati (India)', 'native': 'ગુજરાતી (ભારત)'},
    'ha': {'english': 'Hausa', 'native': 'Hausa'},
    'he': {'english': 'Hebrew', 'native': 'עברית'},
    'hi': {'english': 'Hindi', 'native': 'हिन्दी'},
    'hi-IN': {'english': 'Hindi (India)', 'native': 'हिन्दी (भारत)'},
    'hr': {'english': 'Croatian', 'native': 'Hrvatski'},
    'hsb': {'english': 'Upper Sorbian', 'native': 'Hornjoserbsce'},
    'hu': {'english': 'Hungarian', 'native': 'magyar'},
    'hy-AM': {'english': 'Armenian', 'native': 'Հայերեն'},
    'ia': {'english': 'Interlingua', 'native': 'Interlingua'},
    'id': {'english': 'Indonesian', 'native': 'Bahasa Indonesia'},
    'ig': {'english': 'Igbo', 'native': 'Igbo'},
    'is': {'english': 'Icelandic', 'native': 'íslenska'},
    'it': {'english': 'Italian', 'native': 'Italiano'},
    'ja': {'english': 'Japanese', 'native': '日本語'},
    'ja-JP-mac': {'english': 'Japanese', 'native': '日本語'},
    'ka': {'english': 'Georgian', 'native': 'ქართული'},
    'kab': {'english': 'Kabyle', 'native': 'Taqbaylit'},
    'kk': {'english': 'Kazakh', 'native': 'Қазақ'},
    'km': {'english': 'Khmer', 'native': 'ខ្មែរ'},
    'kn': {'english': 'Kannada', 'native': 'ಕನ್ನಡ'},
    'ko': {'english': 'Korean', 'native': '한국어'},
    'kok': {'english': 'Konkani', 'native': 'कोंकनी'},
    'ks': {'english': 'Kashmiri', 'native': 'كشمیری'},
    'ku': {'english': 'Kurdish', 'native': 'Kurdî'},
    'la': {'english': 'Latin', 'native': 'Latina'},
    'lg': {'english': 'Luganda', 'native': 'Luganda'},
    'lij': {'english': 'Ligurian', 'native': 'Ligure'},
    'ln': {'english': 'Lingala', 'native': 'Lingála'},
    'lo': {'english': 'Lao', 'native': 'ພາສາລາວ'},
    'lt': {'english': 'Lithuanian', 'native': 'Lietuvių'},
    'ltg': {'english': 'Latgalian', 'native': 'Latgaliešu valoda'},
    'lv': {'english': 'Latvian', 'native': 'Latviešu'},
    'mai': {'english': 'Maithili', 'native': 'मैथिली মৈথিলী'},
    'mg': {'english': 'Malagasy', 'native': 'Malagasy'},
    'mi': {'english': 'Maori (Aotearoa)', 'native': 'Māori (Aotearoa)'},
    'mk': {'english': 'Macedonian', 'native': 'Македонски'},
    'ml': {'english': 'Malayalam', 'native': 'മലയാളം'},
    'mn': {'english': 'Mongolian', 'native': 'Монгол'},
    'mr': {'english': 'Marathi', 'native': 'मराठी'},
    'ms': {'english': 'Malay', 'native': 'Melayu'},
    'mt': {'english': 'Maltese', 'native': 'Malti'},
    'my': {'english': 'Burmese', 'native': 'မြန်မာဘာသာ'},
    'nb-NO': {'english': 'Norwegian (Bokmål)', 'native': 'Norsk bokmål'},
    'ne-NP': {'english': 'Nepali', 'native': 'नेपाली'},
    'nl': {'english': 'Dutch', 'native': 'Nederlands'},
    'nn-NO': {'english': 'Norwegian (Nynorsk)', 'native': 'Norsk nynorsk'},
    'nr': {'english': 'Ndebele, South', 'native': 'isiNdebele'},
    'nso': {'english': 'Northern Sotho', 'native': 'Sepedi'},
    'oc': {'english': 'Occitan', 'native': 'occitan'},
    'or': {'english': 'Odia', 'native': 'ଓଡ଼ିଆ'},
    'pa': {'english': 'Punjabi', 'native': 'ਪੰਜਾਬੀ'},
    'pa-IN': {'english': 'Punjabi (India)', 'native': 'ਪੰਜਾਬੀ (ਭਾਰਤ)'},
    'pl': {'english': 'Polish', 'native': 'Polski'},
    'pt-BR': {
        'english': 'Portuguese (Brazilian)',
        'native': 'Português (do\xa0Brasil)',
    },
    'pt-PT': {'english': 'Portuguese (Portugal)', 'native': 'Português (Europeu)'},
    'rm': {'english': 'Romansh', 'native': 'rumantsch'},
    'ro': {'english': 'Romanian', 'native': 'Română'},
    'ru': {'english': 'Russian', 'native': 'Русский'},
    'rw': {'english': 'Kinyarwanda', 'native': 'Ikinyarwanda'},
    'sa': {'english': 'Sanskrit', 'native': 'संस्कृत'},
    'sah': {'english': 'Sakha', 'native': 'Сахалыы'},
    'sat': {'english': 'Santali', 'native': 'ᱥᱟᱱᱛᱟᱲᱤ'},
    'si': {'english': 'Sinhala', 'native': 'සිංහල'},
    'sk': {'english': 'Slovak', 'native': 'slovenčina'},
    'skr': {'english': 'Saraiki', 'native': 'سرائیکی'},
    'sl': {'english': 'Slovenian', 'native': 'Slovenščina'},
    'son': {'english': 'Songhai', 'native': 'Soŋay'},
    'sq': {'english': 'Albanian', 'native': 'Shqip'},
    'sr': {'english': 'Serbian', 'native': 'Српски'},
    'sr-Cyrl': {'english': 'Serbian', 'native': 'Српски'},
    'sr-Latn': {'english': 'Serbian', 'native': 'Srpski'},
    'ss': {'english': 'Siswati', 'native': 'siSwati'},
    'st': {'english': 'Southern Sotho', 'native': 'Sesotho'},
    'sv-SE': {'english': 'Swedish', 'native': 'Svenska'},
    'sw': {'english': 'Swahili', 'native': 'Kiswahili'},
    'ta': {'english': 'Tamil', 'native': 'தமிழ்'},
    'ta-IN': {'english': 'Tamil (India)', 'native': 'தமிழ் (இந்தியா)'},
    'ta-LK': {'english': 'Tamil (Sri Lanka)', 'native': 'தமிழ் (இலங்கை)'},
    'te': {'english': 'Telugu', 'native': 'తెలుగు'},
    'th': {'english': 'Thai', 'native': 'ไทย'},
    'tl': {'english': 'Tagalog', 'native': 'Tagalog'},
    'tn': {'english': 'Tswana', 'native': 'Setswana'},
    'tr': {'english': 'Turkish', 'native': 'Türkçe'},
    'ts': {'english': 'Tsonga', 'native': 'Xitsonga'},
    'tsz': {'english': 'Purépecha', 'native': 'Purépecha'},
    'tt-RU': {'english': 'Tatar', 'native': 'Tatarça'},
    'uk': {'english': 'Ukrainian', 'native': 'Українська'},
    'ur': {'english': 'Urdu', 'native': 'اُردو'},
    'uz': {'english': 'Uzbek', 'native': 'Oʻzbek tili'},
    've': {'english': 'Venda', 'native': 'Tshivenḓa'},
    'vi': {'english': 'Vietnamese', 'native': 'Tiếng Việt'},
    'wo': {'english': 'Wolof', 'native': 'Wolof'},
    'x-testing': {'english': 'Testing', 'native': 'Ŧḗşŧīƞɠ'},
    'xh': {'english': 'Xhosa', 'native': 'isiXhosa'},
    'yo': {'english': 'Yoruba', 'native': 'Yorùbá'},
    'zh-CN': {'english': 'Chinese (Simplified)', 'native': '中文 (简体)'},
    'zh-TW': {'english': 'Chinese (Traditional)', 'native': '正體中文 (繁體)'},
    'zu': {'english': 'Zulu', 'native': 'isiZulu'},
}


# these are used by prod and stage settings
PROD_LANGUAGES = [
    'cs',
    'de',
    'dsb',
    'el',
    'en-CA',
    'en-GB',
    'en-US',
    'es-AR',
    'es-CL',
    'es-ES',
    'es-MX',
    'fi',
    'fr',
    'fur',
    'fy-NL',
    'he',
    'hr',
    'hsb',
    'hu',
    'ia',
    'it',
    'ja',
    'ka',
    'kab',
    'ko',
    'nb-NO',
    'nl',
    'nn-NO',
    'pl',
    'pt-BR',
    'pt-PT',
    'ro',
    'ru',
    'sk',
    'sl',
    'sq',
    'sv-SE',
    'tr',
    'uk',
    'vi',
    'zh-CN',
    'zh-TW',
]

# Languages we can support, but have to fake support for Babel.
# See olympia.amo.utils.get_locale_from_lang
LANGUAGES_NOT_IN_BABEL = [
    'ach',
    'azz',
    'cak',
    'csb',
    'fj-FJ',
    'son',
    'tl',
    'tsz',
]

# Languages we've historically supported for statistics, etc, but we can't use because
# they have a format we don't support in urls
UNSUPPORTED_LANGUAGES = [
    'ca-valencia',
    'ja-JP-mac',
    'sr-Cyrl',
    'sr-Latn',
    'x-testing',
]

# Languages that we support on AMO
# Overriden in prod (&stage) settings to locales that have a high % completeness
AMO_LANGUAGES = [lang for lang in ALL_LANGUAGES if lang not in UNSUPPORTED_LANGUAGES]
