# Generated by Django 2.2.6 on 2019-10-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yara', '0003_auto_20191010_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YaraResult',
        ),
    ]
