#!/bin/sh
#
# Runs "pip install" whenever we detect changes to the requirements after
# a pull.
#
# To install, symlink inside your repo's .git/hooks/ directory.

if [ $(git diff HEAD@{1} HEAD --name-only | grep 'requirements/' -c) -ne 0 ]
then
	$VIRTUAL_ENV/bin/pip install --no-deps -r requirements/dev.txt
fi
