# Generated by Django 3.2.4 on 2021-07-21 11:46

from django.db import migrations


def drop_dynamic_theme_tag(apps, schema_editor):
    Tag = apps.get_model('tags', 'Tag')
    Tag.objects.filter(tag_text='dynamic theme').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20210713_1131'),
    ]

    operations = [
        migrations.RunPython(drop_dynamic_theme_tag)
    ]
