# Generated by Django 3.2.4 on 2021-07-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20210721_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='denied',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='restricted',
        ),
    ]
