# Generated by Django 3.2.6 on 2021-08-13 09:41

from django.db import migrations, models

from olympia.amo.migrations import RenameIndexesOperation


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_auto_20210728_1724'),
    ]

    operations = [
        RenameIndexesOperation(
            'users_tags_addons',
            [
                (
                    migrations.AddIndex(
                        model_name='addontag',
                        index=models.Index(fields=['addon'], name='users_tags_addons_addon_idx'),
                    ),
                    'addon_id',
                ),
            ],
        ),
    ]
