# Generated by Django 3.2.6 on 2021-08-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_auto_20210813_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='enable_for_random_shelf',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
