# Generated by Django 4.2.13 on 2024-06-11 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.fields
import olympia.amo.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('date_posted', models.DateField(default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('permalink', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'blogposts',
                'ordering': ('-date_posted',),
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RssKey',
            fields=[
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('key', models.UUIDField(db_column='rsskey', default=uuid.uuid4, null=True, unique=True)),
                ('created', models.DateField(default=datetime.datetime.now)),
                ('addon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addons.addon', unique=True)),
            ],
            options={
                'db_table': 'hubrsskeys',
            },
        ),
    ]
