# Generated by Django 3.2.12 on 2022-02-09 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
    ]
