# Generated by Django 3.2.13 on 2022-04-13 10:16

from django.db import migrations

from olympia.core.db.migrations import DeleteWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('devhub', '0002_auto_20220209_1845'),
    ]

    operations = [
        DeleteWaffleSwitch('metadata-content-review')
    ]
