# Generated by Django 4.2.8 on 2024-01-09 11:18

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch

class Migration(migrations.Migration):

    dependencies = [
        ('devhub', '0005_auto_20220531_1043'),
    ]

    operations = [
        CreateWaffleSwitch('suppressed-email')
    ]
