# Generated by Django 4.2.19 on 2025-03-12 19:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.fields
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devhub', '0006_auto_20240109_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('survey_id', models.IntegerField(help_text='Alchemy identifier for the survey.')),
                ('date_responded', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveyresponse', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(fields=('survey_id', 'user'), name='unique_survey_user'),
        ),
    ]
