# Generated by Django 4.2.21 on 2025-05-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhub', '0008_auto_20250313_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey_id',
            field=models.IntegerField(help_text='Alchemer survey identifier.'),
        ),
    ]
