# Generated by Django 4.2.21 on 2025-06-05 13:02

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('devhub', '0008_auto_20250313_0001'),
    ]

    operations = [
        CreateWaffleSwitch('enable-data-collection-permissions')
    ]
