# Generated by Django 4.2.21 on 2025-05-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhub', '0009_alter_surveyresponse_survey_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsskey',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
