# Generated by Django 4.2.24 on 2025-10-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhub', '0009_auto_20250605_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey_id',
            field=models.IntegerField(help_text='Alchemer survey identifier.'),
        ),
    ]
