# Generated by Django 4.2.25 on 2025-10-15 12:42

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('devhub', '0010_alter_surveyresponse_survey_id'),
    ]

    operations = [CreateWaffleSwitch('enforce-data-collection-for-new-addons')]
