# Generated by Django 4.2.20 on 2025-03-19 12:40

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0001_initial'),
    ]

    operations = [
        CreateWaffleSwitch('dummy-monitor-fails'),
    ]
