# Generated by Django 5.2.14 on 2026-06-11 15:06

from django.db import migrations
from multidb.pinning import this_thread_is_pinned


def dummy_forwards(apps, schema_editor):
    assert this_thread_is_pinned()


def dummy_backwards(apps, schema_editor):
    assert this_thread_is_pinned()


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0002_auto_20250319_1240'),
    ]

    operations = [
        migrations.RunPython(dummy_forwards, dummy_backwards)
    ]
