# Generated by Django 2.2.6 on 2019-10-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0002_version_needs_human_review'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='version',
            name='version_int_idx',
        ),
        migrations.RemoveField(
            model_name='version',
            name='version_int',
        ),
    ]
