# Generated by Django 2.2.12 on 2020-05-12 17:18

from django.db import migrations, models
import olympia.versions.models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0003_drop_version_int_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='source',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=olympia.versions.models.source_upload_path),
        ),
    ]
