# Generated by Django 2.2.12 on 2020-05-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0004_auto_20200512_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='source_git_hash',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
