# Generated by Django 2.2.12 on 2020-06-02 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0006_remove_version_source_git_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionReviewerFlags',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='versions.Version')),
                ('needs_human_review_by_mad', models.BooleanField(default=False)),
                ('pending_rejection', models.DateTimeField(default=None)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SearchMixin, olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
