# Generated by Django 2.2.14 on 2020-07-17 11:37

from django.db import migrations, models

from olympia.constants.promoted import RECOMMENDED


def add_promoted_approval_for_each_recommended(apps, schema_editor):
    Version = apps.get_model('versions', 'Version')
    PromotedApproval = apps.get_model('promoted', 'PromotedApproval')
    for version in Version.unfiltered.filter(recommendation_approved=True):
        PromotedApproval.objects.create(
            version=version, group_id=RECOMMENDED.id)


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0008_auto_20200625_1114'),
    ]

    operations = [
        migrations.RunPython(add_promoted_approval_for_each_recommended),
        migrations.AlterField(
            model_name='version',
            name='recommendation_approved',
            field=models.BooleanField(null=True),
        ),
    ]
