# Generated by Django 2.2.15 on 2020-09-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0009_auto_20200717_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionreviewerflags',
            name='needs_human_review_by_mad',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='versionreviewerflags',
            name='pending_rejection',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
