# Generated by Django 2.2.16 on 2020-09-23 18:08

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0010_auto_20200901_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionpreview',
            name='colors',
            field=django_jsonfield_backport.models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='versionpreview',
            name='sizes',
            field=django_jsonfield_backport.models.JSONField(default=dict),
        ),
    ]
