# Generated by Django 2.2.16 on 2020-10-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0011_auto_20200923_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='needs_human_review',
            field=models.BooleanField(default=False),
        ),
    ]
