# Generated by Django 2.2.16 on 2020-10-28 16:47

from django.db import migrations
import olympia.versions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0012_auto_20201020_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='recommendation_approved',
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=olympia.versions.fields.VersionStringField(default='0.1', max_length=255),
        ),
    ]
