# Generated by Django 2.2.16 on 2020-10-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0013_auto_20201028_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='versions.License'),
        ),
    ]
