# Generated by Django 2.2.17 on 2020-11-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0014_auto_20201030_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionreviewerflags',
            name='pending_rejection',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
