# Generated by Django 2.2.19 on 2021-03-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0015_auto_20201105_1039'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(
                fields=('addon', 'version'),
                name='versions_addon_id_version_5a2e75b6_uniq',
            ),
        ),
    ]
