# Generated by Django 3.2.9 on 2021-11-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0017_installorigin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='some_rights',
            field=models.BooleanField(default=False, help_text='Show "Some Rights Reserved" instead of the license name?', null=True),
        ),
    ]
