# Generated by Django 3.2.9 on 2021-11-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0018_alter_license_some_rights'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeniedInstallOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname_pattern', models.CharField(help_text='Hostname unix-style pattern to deny.', max_length=255, unique=True)),
                ('include_subdomains', models.BooleanField(default=False, help_text='Automatically check for subdomains of hostname pattern (Additional check with `*.` prepended to the original pattern).')),
            ],
        ),
    ]
