# Generated by Django 3.2.9 on 2021-11-24 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0019_auto_20211123_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deniedinstallorigin',
            options={'base_manager_name': 'objects', 'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='installorigin',
            options={'base_manager_name': 'objects', 'get_latest_by': 'created'},
        ),
        migrations.AddField(
            model_name='deniedinstallorigin',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='deniedinstallorigin',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='installorigin',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='installorigin',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
