# Generated by Django 3.2.9 on 2021-11-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0020_auto_20211124_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='creative_commons',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
