# Generated by Django 3.2.11 on 2022-02-03 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('versions', '0021_auto_20211130_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionreviewerflags',
            name='pending_rejection_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
