# Generated by Django 3.2.11 on 2022-02-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0022_auto_20220203_2057'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='versionreviewerflags',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('pending_rejection__isnull', True), ('pending_rejection_by__isnull', True)), ('pending_rejection__isnull', False), _connector='OR'), name='pending_rejection_both_none'),
        ),
    ]
