# Generated by Django 3.2.13 on 2022-05-30 16:39

from django.db import migrations, models
import olympia.versions.models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0023_auto_20220204_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versionreviewerflags',
            options={},
        ),
        migrations.RemoveField(
            model_name='license',
            name='creative_commons',
        ),
        migrations.RemoveField(
            model_name='license',
            name='icons',
        ),
        migrations.RemoveField(
            model_name='license',
            name='some_rights',
        ),
        migrations.AlterField(
            model_name='version',
            name='source',
            field=models.FileField(blank=True, max_length=255, null=True, storage=olympia.versions.models.source_upload_storage, upload_to=olympia.versions.models.source_upload_path),
        ),
    ]
