# Generated by Django 3.2.14 on 2022-07-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0025_auto_20220614_1653'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='versionreviewerflags',
            name='pending_rejection_both_none',
        ),
        migrations.AddField(
            model_name='versionreviewerflags',
            name='pending_content_rejection',
            field=models.BooleanField(null=True),
        ),
        migrations.AddConstraint(
            model_name='versionreviewerflags',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('pending_content_rejection__isnull', True), ('pending_rejection__isnull', True), ('pending_rejection_by__isnull', True)), ('pending_rejection__isnull', False), _connector='OR'), name='pending_rejection_all_none'),
        ),
    ]
