# Generated by Django 3.2.14 on 2022-07-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0025_auto_20220614_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionreviewerflags',
            name='pending_content_rejection',
            field=models.BooleanField(default=False),
        ),
    ]
