# Generated by Django 3.2.14 on 2022-07-29 09:32

from django.db import migrations, models


def set_content_rejection_to_false(apps, schema_editor):
    VersionReviewerFlags = apps.get_model('versions', 'VersionReviewerFlags')
    (VersionReviewerFlags.objects
        .filter(pending_rejection__isnull=False, pending_content_rejection__isnull=True)
        .update(pending_content_rejection=False)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0026_auto_20220722_1704'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='versionreviewerflags',
            name='pending_rejection_all_none',
        ),
        migrations.RunPython(set_content_rejection_to_false),
        migrations.AddConstraint(
            model_name='versionreviewerflags',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('pending_content_rejection__isnull', True), ('pending_rejection__isnull', True), ('pending_rejection_by__isnull', True)), models.Q(('pending_content_rejection__isnull', False), ('pending_rejection__isnull', False), ('pending_rejection_by__isnull', False)), _connector='OR'), name='pending_rejection_all_none'),
        ),
    ]
