# Generated by Django 3.2.15 on 2022-08-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0027_auto_20220729_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='approval_notes',
            field=models.TextField(blank=True, db_column='approvalnotes', default=''),
        ),
    ]
