# Generated by Django 4.1 on 2022-08-30 10:25

from django.db import migrations, models
import django.db.models.deletion
import olympia.translations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('versions', '0027_auto_20220729_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='on_form',
            field=models.BooleanField(null=True),
        ),
    ]
