# Generated by Django 3.2.16 on 2022-11-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0028_alter_license_on_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='on_form',
        ),
        migrations.RemoveField(
            model_name='license',
            name='url',
        ),
        migrations.AlterField(
            model_name='version',
            name='approval_notes',
            field=models.TextField(blank=True, db_column='approvalnotes', default='', max_length=10000),
        ),
    ]
