# Generated by Django 3.2.16 on 2022-11-22 13:12

from django.db import migrations, models
import django.db.models.deletion
import olympia.translations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('versions', '0029_auto_20221114_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='name',
            field=olympia.translations.fields.TranslatedField(blank=True, db_column='name', max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='License_name_set+', require_locale=True, short=True, to='translations.Translation', to_field='id', unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='text',
            field=olympia.translations.fields.LinkifiedField(blank=True, db_column='text', max_length=75000, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='License_text_set+', require_locale=True, short=True, to='translations.LinkifiedTranslation', to_field='id', unique=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='approval_notes',
            field=models.TextField(blank=True, db_column='approvalnotes', default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='version',
            name='release_notes',
            field=olympia.translations.fields.PurifiedField(blank=True, db_column='releasenotes', max_length=3000, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Version_release_notes_set+', require_locale=True, short=False, to='translations.PurifiedTranslation', to_field='id', unique=True),
        ),
    ]
