# Generated by Django 3.2.16 on 2023-01-07 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0030_auto_20221122_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='nomination',
            new_name='due_date',
        ),
    ]
