# Generated by Django 3.2.16 on 2023-01-07 00:48
from datetime import timedelta

from django.db import models, migrations

from olympia import amo

from olympia.versions.utils import get_review_due_date


def adjust_due_date_now_its_not_nomination_date(apps, schema_editor):
    Version = apps.get_model('versions', 'Version')
    version_qs = Version.unfiltered.filter(
        deleted=False, due_date__isnull=False
    )
    # clear any versions that had a nomination date that weren't awaiting review
    version_qs.exclude(file__status=amo.STATUS_AWAITING_REVIEW).update(due_date=None)
    # And calculate a due date based on the nomination date for the rest
    for version in version_qs.filter(file__status=amo.STATUS_AWAITING_REVIEW):
        version.update(get_review_due_date(version.due_date))


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0031_rename_nomination_version_due_date'),
    ]

    operations = [
        migrations.RunPython(adjust_due_date_now_its_not_nomination_date)
    ]
