# Generated by Django 3.2.16 on 2023-01-07 00:48
from django.db import migrations

from olympia import amo

from olympia.versions.utils import get_review_due_date


def set_due_date_from_nomination_date(apps, schema_editor):
    Version = apps.get_model('versions', 'Version')
    version_qs = Version.unfiltered.filter(
        deleted=False,
        nomination__isnull=False,
        file__status=amo.STATUS_AWAITING_REVIEW,
    )
    # Calculate a due date based on the nomination date
    for version in version_qs:
        version.due_date = get_review_due_date(version.nomination)
        version.save(update_fields=['due_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0031_add_due_date'),
        ('files', '0014_auto_20210824_1722'),
    ]

    operations = [migrations.RunPython(set_due_date_from_nomination_date)]
