# Generated by Django 3.2.16 on 2023-01-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0032_auto_20230107_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='nomination',
        ),
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=['due_date'], name='versions_due_date_b9c73ed7'),
        ),
    ]
