# Generated by Django 3.2.16 on 2023-01-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0033_auto_20230118_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='human_review_date',
            field=models.DateTimeField(null=True),
        ),
    ]
