# Generated by Django 3.2.16 on 2023-01-07 00:48
from django.db import migrations
from django.db.models import Q

from olympia import amo


def set_human_review_date_from_reviewed(apps, schema_editor):
    Version = apps.get_model('versions', 'Version')
    # This is based on Version.has_been_human_reviewed, before it was removed
    version_qs = Version.unfiltered.filter(
        Q(file__status=amo.STATUS_DISABLED, file__reviewed__isnull=False)
        | Q(
            Q(autoapprovalsummary__version__isnull=True)
            | Q(autoapprovalsummary__verdict=amo.NOT_AUTO_APPROVED)
            | Q(autoapprovalsummary__confirmed=True)
            , file__status=amo.STATUS_APPROVED,
        ),
        reviewed__isnull=False).using('default')
    for version in version_qs:
        version.human_review_date = version.reviewed
        version.save(update_fields=['human_review_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0034_auto_20230131_1821'),
        ('reviewers', '0001_initial'),
    ]

    operations = [migrations.RunPython(set_human_review_date_from_reviewed)]
