# Generated by Django 3.2.18 on 2023-05-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0037_auto_20230502_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='reviewed',
        ),
        migrations.AlterField(
            model_name='version',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
