# Generated by Django 3.2.18 on 2023-05-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0038_auto_20230511_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='needs_human_review',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
