# Generated by Django 4.2.1 on 2023-05-24 08:34

from django.db import migrations
import django.db.models.deletion
import olympia.translations.fields


class Migration(migrations.Migration):
    dependencies = [
        ('translations', '0001_initial'),
        ('versions', '0039_alter_version_needs_human_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='name',
            field=olympia.translations.fields.TranslatedField(
                blank=True,
                db_column='name',
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                require_locale=True,
                short=True,
                to='translations.Translation',
                to_field='id',
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='license',
            name='text',
            field=olympia.translations.fields.LinkifiedField(
                blank=True,
                db_column='text',
                max_length=75000,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                require_locale=True,
                short=True,
                to='translations.LinkifiedTranslation',
                to_field='id',
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='version',
            name='release_notes',
            field=olympia.translations.fields.PurifiedField(
                blank=True,
                db_column='releasenotes',
                max_length=3000,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                require_locale=True,
                short=False,
                to='translations.PurifiedTranslation',
                to_field='id',
                unique=True,
            ),
        ),
    ]
