# Generated by Django 3.2.18 on 2023-05-26 13:53

from django.db import migrations

from olympia import amo


def remove_static_themes_android_compatibility(apps, schema_editor):
    ApplicationsVersions = apps.get_model('versions', 'ApplicationsVersions')
    ApplicationsVersions.objects.filter(
        version__addon__type=amo.ADDON_STATICTHEME, application=amo.ANDROID.id
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('versions', '0040_alter_license_name_and_more'),
    ]

    operations = [
        migrations.RunPython(
            remove_static_themes_android_compatibility, lambda *args: None
        )
    ]
