# Generated by Django 3.2.18 on 2023-05-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0041_remove_static_themes_android_compatibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsversions',
            name='originated_from',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Automatically determined'), (2, 'Set by developer through devhub or API'), (3, 'Set in the manifest (gecko key)'), (4, 'Set in the manifest (gecko_android key)')], default=0, null=True),
        ),
    ]
