# Generated by Django 4.2.8 on 2024-02-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0024_cinderpolicy_parent_alter_cinderpolicy_uuid'),
        ('versions', '0042_auto_20230531_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='needs_human_review',
        ),
        migrations.AddField(
            model_name='versionreviewerflags',
            name='pending_resolution_cinder_jobs',
            field=models.ManyToManyField(related_name='pending_rejections', to='abuse.cinderjob'),
        ),
        migrations.AlterField(
            model_name='applicationsversions',
            name='originated_from',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Automatically determined'), (5, 'Automatically set by a migration'), (2, 'Set by developer through devhub or API'), (3, 'Set in the manifest (gecko key)'), (4, 'Set in the manifest (gecko_android key)')], default=0, null=True),
        ),
    ]
