# Generated by Django 4.2.5 on 2023-09-27 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('versions', '0042_auto_20230531_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionProvenance',
            fields=[
                (
                    'version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to='versions.version',
                    ),
                ),
                (
                    'source',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'Developer Hub'),
                            (2, 'Signing API'),
                            (3, 'Add-on API'),
                            (4, 'Automatically generated by AMO'),
                        ]
                    ),
                ),
                (
                    'client_info',
                    models.CharField(default=None, max_length=255, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='version',
            name='needs_human_review',
        ),
        migrations.AlterField(
            model_name='applicationsversions',
            name='originated_from',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'Unknown'),
                    (1, 'Automatically determined'),
                    (5, 'Automatically set by a migration'),
                    (2, 'Set by developer through devhub or API'),
                    (3, 'Set in the manifest (gecko key)'),
                    (4, 'Set in the manifest (gecko_android key)'),
                ],
                default=0,
                null=True,
            ),
        ),
    ]
