# Generated by Django 4.2.7 on 2023-11-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("versions", "0042_auto_20230531_0926"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="version",
            name="needs_human_review",
        ),
        migrations.AddField(
            model_name="versionpreview",
            name="image_hash",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="applicationsversions",
            name="originated_from",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Automatically determined"),
                    (5, "Automatically set by a migration"),
                    (2, "Set by developer through devhub or API"),
                    (3, "Set in the manifest (gecko key)"),
                    (4, "Set in the manifest (gecko_android key)"),
                ],
                default=0,
                null=True,
            ),
        ),
    ]
