# Generated by Django 4.2.11 on 2024-03-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0028_cinderdecision_backfill'),
        ('versions', '0043_remove_version_needs_human_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionreviewerflags',
            name='pending_resolution_cinder_jobs',
            field=models.ManyToManyField(related_name='pending_rejections', to='abuse.cinderdecision'),
        ),
    ]
