# Generated by Django 4.2.11 on 2024-04-09 13:58

from django.db import migrations

from olympia import amo


def clear_due_dates_from_old_disabled_addons(apps, schema_editor):
    Version = apps.get_model('versions', 'Version')
    Version.unfiltered.filter(
        addon__status=amo.STATUS_DISABLED, due_date__isnull=False
    ).update(due_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0043_remove_version_needs_human_review_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_due_dates_from_old_disabled_addons)
    ]
