# Generated by Django 4.2.11 on 2024-04-09 13:58

from django.db import migrations

from olympia import amo

class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0043_remove_version_needs_human_review_and_more'),
    ]

    operations = [
    ]
