# Generated by Django 4.2.11 on 2024-04-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0044_auto_20240409_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionProvenance',
            fields=[
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='versions.version')),
                ('source', models.PositiveSmallIntegerField(choices=[(1, 'Developer Hub'), (2, 'Signing API'), (3, 'Add-on API'), (4, 'Automatically generated by AMO')])),
                ('client_info', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
