# Generated by Django 4.2.16 on 2024-09-16 12:40

from django.db import migrations
from olympia.constants.licenses import (
    LICENSE_CC_BY40,
    LICENSE_CC_BY_NC40,
    LICENSE_CC_BY_NC_ND40,
    LICENSE_CC_BY_NC_SA40,
    LICENSE_CC_BY_ND40,
    LICENSE_CC_BY_SA40,
)


def create_cc40_licenses(apps, schema_editor):
    License = apps.get_model('versions', 'License')
    for license in [
        LICENSE_CC_BY40,
        LICENSE_CC_BY_NC40,
        LICENSE_CC_BY_NC_ND40,
        LICENSE_CC_BY_NC_SA40,
        LICENSE_CC_BY_ND40,
        LICENSE_CC_BY_SA40,
    ]:
        license = License.objects.get_or_create(
            builtin=license.builtin,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('versions', '0045_versionprovenance'),
    ]

    operations = [migrations.RunPython(create_cc40_licenses, lambda a, s: None)]
