# Generated by Django 4.2.14 on 2024-07-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0045_versionprovenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='due_date_reasons',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
