# Generated by Django 4.2.24 on 2025-10-01 09:41

from django.db import migrations
import django.db.models.deletion
import olympia.translations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_puretranslation_purifiedmarkdowntranslation'),
        ('versions', '0047_auto_20241031_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='release_notes',
            field=olympia.translations.fields.PurifiedMarkdownField(blank=True, db_column='releasenotes', max_length=3000, null=True, on_delete=django.db.models.deletion.SET_NULL, require_locale=True, short=False, to='translations.PurifiedMarkdownTranslation', to_field='id', unique=True),
        ),
    ]
