# Generated by Django 4.2.21 on 2025-05-15 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0048_alter_version_release_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versionprovenance',
            options={'base_manager_name': 'objects', 'get_latest_by': 'created'},
        ),
        migrations.AddField(
            model_name='applicationsversions',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='applicationsversions',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='versionprovenance',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='versionprovenance',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
