# Generated by Django 4.2.25 on 2025-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0048_alter_version_release_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionreviewerflags',
            name='needs_human_review_by_mad',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
    ]
