# Generated by Django 4.2.25 on 2025-10-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0049_alter_versionreviewerflags_needs_human_review_by_mad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionreviewerflags',
            name='needs_human_review_by_mad',
        ),
    ]
