# Generated by Django 4.2.26 on 2025-11-13 08:55

from django.db import migrations
from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0050_remove_versionreviewerflags_needs_human_review_by_mad'),
    ]

    operations = [CreateWaffleSwitch('enable-source-builder')]
