# Generated by Django 5.2.15 on 2026-07-20 13:45

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch

class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0052_delete_enable_source_builder_waffle_switch'),
    ]

    operations = [
        CreateWaffleSwitch('enterprise-channel')
    ]
