# -*- coding: utf8 -*-
from lib.constants import ALL_CURRENCIES

from tower import ugettext_lazy as _lazy

# From page 10 of the Mozilla Exporter API docs v1.0.0
BANGO_CURRENCIES = ['AUD', 'CAD', 'CHF', 'COP', 'DKK', 'EGP', 'EUR', 'GBP',
                    'IDR', 'MXN', 'MYR', 'NOK', 'NZD', 'PHP', 'PLN', 'QAR',
                    'SEK', 'SGD', 'THB', 'USD', 'ZAR']
BANGO_CURRENCIES = dict((k, ALL_CURRENCIES[k]) for k in BANGO_CURRENCIES)

BANGO_OUTPAYMENT_CURRENCIES = ['EUR', 'GBP', 'USD']
BANGO_OUTPAYMENT_CURRENCIES = [(k, ALL_CURRENCIES[k])
                               for k in BANGO_OUTPAYMENT_CURRENCIES]

BANGO_COUNTRIES = [
    ('AFG', _lazy(u'Afghanistan')),
    ('ALA', _lazy(u'Åland Islands')),
    ('ALB', _lazy(u'Albania')),
    ('DZA', _lazy(u'Algeria')),
    ('ASM', _lazy(u'American Samoa')),
    ('AND', _lazy(u'Andorra')),
    ('AGO', _lazy(u'Angola')),
    ('AIA', _lazy(u'Anguilla')),
    ('ATA', _lazy(u'Antarctica')),
    ('ATG', _lazy(u'Antigua and Barbuda')),
    ('ARG', _lazy(u'Argentina')),
    ('ARM', _lazy(u'Armenia')),
    ('ABW', _lazy(u'Aruba')),
    ('AUS', _lazy(u'Australia')),
    ('AUT', _lazy(u'Austria')),
    ('AZE', _lazy(u'Azerbaijan')),
    ('BHS', _lazy(u'Bahamas')),
    ('BHR', _lazy(u'Bahrain')),
    ('BGD', _lazy(u'Bangladesh')),
    ('BRB', _lazy(u'Barbados')),
    ('BLR', _lazy(u'Belarus')),
    ('BEL', _lazy(u'Belgium')),
    ('BLZ', _lazy(u'Belize')),
    ('BEN', _lazy(u'Benin')),
    ('BMU', _lazy(u'Bermuda')),
    ('BTN', _lazy(u'Bhutan')),
    ('BOL', _lazy(u'Bolivia')),
    ('BES', _lazy(u'Bonaire, Saint Eustatius and Saba')),
    ('BIH', _lazy(u'Bosnia and Herzegovina')),
    ('BWA', _lazy(u'Botswana')),
    ('BVT', _lazy(u'Bouvet Island')),
    ('BRA', _lazy(u'Brazil')),
    ('IOT', _lazy(u'British Indian Ocean Territory')),
    ('BRN', _lazy(u'Brunei Darussalam')),
    ('BGR', _lazy(u'Bulgaria')),
    ('BFA', _lazy(u'Burkina Faso')),
    ('BDI', _lazy(u'Burundi')),
    ('KHM', _lazy(u'Cambodia')),
    ('CMR', _lazy(u'Cameroon')),
    ('CAN', _lazy(u'Canada')),
    ('CPV', _lazy(u'Cape Verde')),
    ('CYM', _lazy(u'Cayman Islands')),
    ('CAF', _lazy(u'Central African Republic')),
    ('TCD', _lazy(u'Chad')),
    ('CHL', _lazy(u'Chile')),
    ('CHN', _lazy(u'China')),
    ('CXR', _lazy(u'Christmas Island')),
    ('CCK', _lazy(u'Cocos (Keeling) Islands')),
    ('COL', _lazy(u'Colombia')),
    ('COM', _lazy(u'Comoros')),
    ('COG', _lazy(u'Congo')),
    ('COD', _lazy(u'Congo, Democratic Republic')),
    ('COK', _lazy(u'Cook Islands')),
    ('CRI', _lazy(u'Costa Rica')),
    ('CIV', _lazy(u"Côte d'Ivoire")),
    ('HRV', _lazy(u'Croatia')),
    ('CUB', _lazy(u'Cuba')),
    ('CUW', _lazy(u'Curaçao')),
    ('CYP', _lazy(u'Cyprus')),
    ('CZE', _lazy(u'Czech Republic')),
    ('DNK', _lazy(u'Denmark Do')),
    ('DJI', _lazy(u'Djibouti')),
    ('DMA', _lazy(u'Dominica')),
    ('DOM', _lazy(u'Dominican Republic')),
    ('ECU', _lazy(u'Ecuador')),
    ('EGY', _lazy(u'Egypt')),
    ('SLV', _lazy(u'El Salvador')),
    ('GNQ', _lazy(u'Equatorial Guinea')),
    ('ERI', _lazy(u'Eritrea')),
    ('EST', _lazy(u'Estonia')),
    ('ETH', _lazy(u'Ethiopia')),
    ('FLK', _lazy(u'Falkland Islands (Malvinas)')),
    ('FRO', _lazy(u'Faroe Islands')),
    ('FJI', _lazy(u'Fiji')),
    ('FIN', _lazy(u'Finland')),
    ('FRA', _lazy(u'France')),
    ('GUF', _lazy(u'French Guiana')),
    ('PYF', _lazy(u'French Polynesia')),
    ('ATF', _lazy(u'French Southern Territories')),
    ('GAB', _lazy(u'Gabon')),
    ('GMB', _lazy(u'Gambia')),
    ('GEO', _lazy(u'Georgia')),
    ('DEU', _lazy(u'Germany')),
    ('GHA', _lazy(u'Ghana')),
    ('GIB', _lazy(u'Gibraltar')),
    ('GRC', _lazy(u'Greece')),
    ('GRL', _lazy(u'Greenland')),
    ('GRD', _lazy(u'Grenada')),
    ('GLP', _lazy(u'Guadeloupe')),
    ('GUM', _lazy(u'Guam')),
    ('GTM', _lazy(u'Guatemala')),
    ('GGY', _lazy(u'Guernsey')),
    ('GIN', _lazy(u'Guinea')),
    ('GNB', _lazy(u'Guinea-Bissau')),
    ('GUY', _lazy(u'Guyana')),
    ('HTI', _lazy(u'Haiti')),
    ('HMD', _lazy(u'Heard and McDonald Islands')),
    ('VAT', _lazy(u'Holy See (Vatican City State)')),
    ('HND', _lazy(u'Honduras')),
    ('HKG', _lazy(u'Hong Kong')),
    ('HUN', _lazy(u'Hungary')),
    ('ISL', _lazy(u'Iceland')),
    ('IND', _lazy(u'India')),
    ('IDN', _lazy(u'Indonesia')),
    ('IRN', _lazy(u'Iran, Islamic Republic of')),
    ('IRQ', _lazy(u'Iraq')),
    ('IRL', _lazy(u'Ireland')),
    ('IMN', _lazy(u'Isle of Man')),
    ('ISR', _lazy(u'Israel')),
    ('ITA', _lazy(u'Italy')),
    ('JAM', _lazy(u'Jamaica')),
    ('JPN', _lazy(u'Japan')),
    ('JEY', _lazy(u'Jersey')),
    ('JOR', _lazy(u'Jordan')),
    ('KAZ', _lazy(u'Kazakhstan')),
    ('KEN', _lazy(u'Kenya')),
    ('KIR', _lazy(u'Kiribati')),
    ('PRK', _lazy(u"Korea, Democratic People's Rep")),
    ('KOR', _lazy(u'Korea, Republic of')),
    ('KOS', _lazy(u'Kosovo')),
    ('KWT', _lazy(u'Kuwait')),
    ('KGZ', _lazy(u'Kyrgyzstan')),
    ('LAO', _lazy(u"Lao People's Democratic Rep")),
    ('LVA', _lazy(u'Latvia')),
    ('LBN', _lazy(u'Lebanon')),
    ('LSO', _lazy(u'Lesotho')),
    ('LBR', _lazy(u'Liberia')),
    ('LBY', _lazy(u'Libyan Arab Jamahiriya')),
    ('LIE', _lazy(u'Liechtenstei')),
    ('LTU', _lazy(u'Lithuania')),
    ('LUX', _lazy(u'Luxembourg')),
    ('MAC', _lazy(u'Macao')),
    ('MKD', _lazy(u'Macedonia, Former Yugoslav Rep')),
    ('MDG', _lazy(u'Madagascar')),
    ('MWI', _lazy(u'Malawi')),
    ('MYS', _lazy(u'Malaysia')),
    ('MDV', _lazy(u'Maldives')),
    ('MLI', _lazy(u'Mali')),
    ('MLT', _lazy(u'Malta')),
    ('MHL', _lazy(u'Marshall Islands')),
    ('MTQ', _lazy(u'Martinique')),
    ('MRT', _lazy(u'Mauritania')),
    ('MUS', _lazy(u'Mauritius')),
    ('MYT', _lazy(u'Mayotte')),
    ('MEX', _lazy(u'Mexico')),
    ('FSM', _lazy(u'Micronesia, Federated States of')),
    ('MDA', _lazy(u'Moldova, Republic of')),
    ('MCO', _lazy(u'Monaco')),
    ('MNG', _lazy(u'Mongolia')),
    ('MNE', _lazy(u'Montenegro')),
    ('MSR', _lazy(u'Montserrat')),
    ('MAR', _lazy(u'Morocco')),
    ('MOZ', _lazy(u'Mozambique')),
    ('MMR', _lazy(u'Myanmar')),
    ('NAM', _lazy(u'Namibia')),
    ('NRU', _lazy(u'Nauru')),
    ('NPL', _lazy(u'Nepal')),
    ('NLD', _lazy(u'Netherlands')),
    ('NCL', _lazy(u'New Caledonia')),
    ('NZL', _lazy(u'New Zealand')),
    ('NIC', _lazy(u'Nicaragua')),
    ('NER', _lazy(u'Niger')),
    ('NGA', _lazy(u'Nigeria')),
    ('NIU', _lazy(u'Niue')),
    ('NFK', _lazy(u'Norfolk Island')),
    ('MNP', _lazy(u'Northern Mariana Islands')),
    ('NOR', _lazy(u'Norway')),
    ('OMN', _lazy(u'Oman')),
    ('PAK', _lazy(u'Pakistan')),
    ('PLW', _lazy(u'Palau')),
    ('PSE', _lazy(u'Palestinian Territory, Occupied')),
    ('PAN', _lazy(u'Panama')),
    ('PNG', _lazy(u'Papua New Guinea')),
    ('PRY', _lazy(u'Paraguay')),
    ('PER', _lazy(u'Peru')),
    ('PHL', _lazy(u'Philippines')),
    ('PCN', _lazy(u'Pitcairn')),
    ('POL', _lazy(u'Poland')),
    ('PRT', _lazy(u'Portugal')),
    ('PRI', _lazy(u'Puerto Rico')),
    ('QAT', _lazy(u'Qatar')),
    ('REU', _lazy(u'Réunion')),
    ('ROU', _lazy(u'Romania')),
    ('RUS', _lazy(u'Russian Federation')),
    ('RWA', _lazy(u'Rwanda')),
    ('BLM', _lazy(u'Saint Barthélemy')),
    ('SHN', _lazy(u'Saint Helena')),
    ('KNA', _lazy(u'Saint Kitts and Nevis')),
    ('LCA', _lazy(u'Saint Lucia')),
    ('MAF', _lazy(u'Saint Martin')),
    ('SPM', _lazy(u'Saint Pierre and Miquelon')),
    ('VCT', _lazy(u'Saint Vincent and the Grenadines')),
    ('WSM', _lazy(u'Samoa')),
    ('SMR', _lazy(u'San Marino')),
    ('STP', _lazy(u'Sao Tome and Principe')),
    ('SAU', _lazy(u'Saudi Arabia')),
    ('SEN', _lazy(u'Senega')),
    ('SRB', _lazy(u'Serbia')),
    ('SCG', _lazy(u'Serbia and Montenegro')),
    ('SYC', _lazy(u'Seychelles')),
    ('SLE', _lazy(u'Sierra Leone')),
    ('SGP', _lazy(u'Singapore')),
    ('SXM', _lazy(u'Sint Maarten (Dutch part)')),
    ('SVK', _lazy(u'Slovakia')),
    ('SVN', _lazy(u'Slovenia')),
    ('SLB', _lazy(u'Solomon Islands')),
    ('SOM', _lazy(u'Somalia')),
    ('ZAF', _lazy(u'South Africa')),
    ('SGS', _lazy(u'South Georgia and the South Sandwich Islands')),
    ('SSD', _lazy(u'South Sudan')),
    ('ESP', _lazy(u'Spain')),
    ('LKA', _lazy(u'Sri Lanka')),
    ('SDN', _lazy(u'Sudan')),
    ('SUR', _lazy(u'Suriname')),
    ('SJM', _lazy(u'Svalbard and Jan Mayen')),
    ('SWZ', _lazy(u'Swaziland')),
    ('SWE', _lazy(u'Sweden')),
    ('CHE', _lazy(u'Switzerland')),
    ('SYR', _lazy(u'Syrian Arab Republic')),
    ('TWN', _lazy(u'Taiwan, Province of China')),
    ('TJK', _lazy(u'Tajikistan')),
    ('TZA', _lazy(u'Tanzania, United Republic of')),
    ('THA', _lazy(u'Thailand')),
    ('TLS', _lazy(u'Timor-Leste')),
    ('TGO', _lazy(u'Togo')),
    ('TKL', _lazy(u'Tokelau')),
    ('TON', _lazy(u'Tonga')),
    ('TTO', _lazy(u'Trinidad and Tobago')),
    ('TUN', _lazy(u'Tunisia')),
    ('TUR', _lazy(u'Turkey')),
    ('TKM', _lazy(u'Turkmenistan')),
    ('TCA', _lazy(u'Turks and Caicos Islands')),
    ('TUV', _lazy(u'Tuvalu')),
    ('UGA', _lazy(u'Uganda')),
    ('UKR', _lazy(u'Ukraine')),
    ('ARE', _lazy(u'United Arab Emirates')),
    ('GBR', _lazy(u'United Kingdom')),
    ('USA', _lazy(u'United States')),
    ('UMI', _lazy(u'United States Minor Outlying Islands')),
    ('URY', _lazy(u'Uruguay')),
    ('UZB', _lazy(u'Uzbekistan')),
    ('VUT', _lazy(u'Vanuatu')),
    ('VEN', _lazy(u'Venezuela, Bolivarian Republic of')),
    ('VNM', _lazy(u'Viet Nam')),
    ('VGB', _lazy(u'Virgin Islands, British')),
    ('VIR', _lazy(u'Virgin Islands, U.S.')),
    ('WLF', _lazy(u'Wallis and Futuna')),
    ('ESH', _lazy(u'Western Sahara')),
    ('YEM', _lazy(u'Yemen')),
    ('ZMB', _lazy(u'Zambia')),
    ('ZWE', _lazy(u'Zimbabwe')),
]
