# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import olympia.amo.fields
import olympia.amo.models
import olympia.translations.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(max_length=255, null=True, unique=True)),
                ('slug', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('default_locale', models.CharField(db_column='defaultlocale', default='en-US', max_length=10)),
                ('type', models.PositiveIntegerField(choices=[(1, 'Extension'), (2, 'Deprecated Complete Theme'), (3, 'Dictionary'), (4, 'Deprecated Search Engine'), (5, 'Language Pack'), (6, 'Deprecated Language Pack (Add-on)'), (7, 'Deprecated Plugin'), (9, 'Deprecated LWT'), (10, 'Theme'), (12, 'Deprecated Site Permission')], db_column='addontype_id', default=1)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Incomplete'), (3, 'Awaiting Review'), (4, 'Approved'), (5, 'Disabled by Mozilla'), (11, 'Deleted')], default=0)),
                ('icon_type', models.CharField(blank=True, db_column='icontype', max_length=25)),
                ('icon_hash', models.CharField(blank=True, max_length=8, null=True)),
                ('average_rating', models.FloatField(db_column='averagerating', default=0, max_length=255, null=True)),
                ('bayesian_rating', models.FloatField(db_column='bayesianrating', default=0)),
                ('total_ratings', models.PositiveIntegerField(db_column='totalreviews', default=0)),
                ('text_ratings_count', models.PositiveIntegerField(db_column='textreviewscount', default=0)),
                ('weekly_downloads', models.PositiveIntegerField(db_column='weeklydownloads', default=0)),
                ('hotness', models.FloatField(default=0)),
                ('average_daily_users', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(help_text='Last time this add-on had a file/version update', null=True)),
                ('disabled_by_user', models.BooleanField(db_column='inactive', default=False)),
                ('target_locale', models.CharField(blank=True, help_text='For dictionaries and language packs. Identifies the language and, optionally, region that this add-on is written for. Examples: en-US, fr, and de-AT', max_length=255, null=True)),
                ('contributions', models.URLField(blank=True, max_length=255)),
                ('is_experimental', models.BooleanField(db_column='experimental', default=False)),
                ('reputation', models.SmallIntegerField(choices=[(0, 'No Reputation'), (1, 'Good (1)'), (2, 'Very Good (2)'), (3, 'Excellent (3)')], default=0, help_text='The higher the reputation value, the further down the add-on will be in the auto-approved review queue. A value of 0 has no impact', null=True)),
                ('requires_payment', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'addons',
                'base_manager_name': 'unfiltered',
            },
            bases=(olympia.amo.models.OnChangeMixin, olympia.amo.models.SaveUpdateMixin, models.Model),
            managers=[
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AddonBrowserMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('browser', models.PositiveSmallIntegerField(choices=[(1, 'chrome')])),
                ('extension_id', models.CharField(db_index=True, max_length=255)),
            ],
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AddonCategory',
            fields=[
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('category_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'addons_categories',
            },
        ),
        migrations.CreateModel(
            name='AddonGUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(db_index=True, max_length=255)),
                ('hashed_guid', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'addons_reusedguid',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AddonUser',
            fields=[
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('role', models.SmallIntegerField(choices=[(5, 'Owner'), (4, 'Developer'), (6, '(Deleted)')], default=5)),
                ('original_role', models.SmallIntegerField(choices=[(5, 'Owner'), (4, 'Developer')], default=4, editable=False, help_text='Role to assign if user is unbanned')),
                ('listed', models.BooleanField(default=True, verbose_name='Listed')),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'addons_users',
                'base_manager_name': 'unfiltered',
            },
            bases=(olympia.amo.models.OnChangeMixin, olympia.amo.models.SaveUpdateMixin, models.Model),
            managers=[
                ('unfiltered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DeniedGuid',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(max_length=255, unique=True)),
                ('comments', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'denied_guids',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeniedSlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'addons_denied_slug',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReplacementAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(max_length=255, null=True, unique=True)),
                ('path', models.CharField(help_text='Add-on and collection paths need to end with "/"', max_length=255, null=True)),
            ],
            options={
                'db_table': 'replacement_addons',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AddonApprovalsCounter',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('addon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='addons.addon')),
                ('counter', models.PositiveIntegerField(default=0)),
                ('last_human_review', models.DateTimeField(null=True)),
                ('last_content_review', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AddonRegionalRestrictions',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('addon', models.OneToOneField(help_text='Add-on id this item will point to.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='regional_restrictions', serialize=False, to='addons.addon')),
                ('excluded_regions', models.JSONField(default=list, help_text='JSON style list of ISO 3166-1 alpha-2 country (region) codes. Codes will be uppercased. E.g. `["CN"]`')),
            ],
            options={
                'verbose_name_plural': 'Addon Regional Restrictions',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AddonReviewerFlags',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('addon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reviewerflags', serialize=False, to='addons.addon')),
                ('needs_admin_code_review', models.BooleanField(default=False, null=True)),
                ('needs_admin_content_review', models.BooleanField(default=False, null=True)),
                ('needs_admin_theme_review', models.BooleanField(default=False)),
                ('auto_approval_disabled', models.BooleanField(default=False)),
                ('auto_approval_disabled_unlisted', models.BooleanField(default=None, null=True)),
                ('auto_approval_disabled_until_next_approval', models.BooleanField(default=None, null=True)),
                ('auto_approval_disabled_until_next_approval_unlisted', models.BooleanField(default=None, null=True)),
                ('auto_approval_delayed_until', models.DateTimeField(blank=True, default=None, null=True)),
                ('auto_approval_delayed_until_unlisted', models.DateTimeField(blank=True, default=None, null=True)),
                ('notified_about_expiring_delayed_rejections', models.BooleanField(default=None, null=True)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DisabledAddonContent',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('addon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='content_deleted_on_force_disable', serialize=False, to='addons.addon')),
                ('icon_backup_name', models.CharField(blank=True, default=None, max_length=75, null=True)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=0)),
                ('sizes', models.JSONField(default=dict)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='addons.addon')),
                ('caption', olympia.translations.fields.TranslatedField(blank=True, db_column='caption', max_length=280, null=True, on_delete=django.db.models.deletion.SET_NULL, require_locale=True, short=True, to='translations.Translation', to_field='id', unique=True)),
            ],
            options={
                'db_table': 'previews',
                'ordering': ('position', 'created'),
            },
            bases=(olympia.amo.models.BasePreview, olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MigratedLWT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lightweight_theme_id', models.PositiveIntegerField()),
                ('getpersonas_id', models.PositiveIntegerField()),
                ('static_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrated_from_lwt', to='addons.addon', unique=True)),
            ],
            options={
                'db_table': 'migrated_personas',
            },
            bases=(olympia.amo.models.OnChangeMixin, olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FrozenAddon',
            fields=[
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons.addon')),
            ],
            options={
                'db_table': 'frozen_addons',
            },
        ),
        migrations.CreateModel(
            name='DeletedPreviewFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('backup_name', models.CharField(blank=True, default=None, max_length=75, null=True)),
                ('preview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons.preview')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AddonUserPendingConfirmation',
            fields=[
                ('id', olympia.amo.fields.PositiveAutoField(primary_key=True, serialize=False)),
                ('role', models.SmallIntegerField(choices=[(5, 'Owner'), (4, 'Developer')], default=5)),
                ('listed', models.BooleanField(default=True, verbose_name='Listed')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons.addon')),
            ],
            options={
                'db_table': 'addons_users_pending_confirmation',
            },
            bases=(olympia.amo.models.OnChangeMixin, olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
