# Generated by Django 2.2.12 on 2020-05-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0005_auto_20200527_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonguid',
            name='guid',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
