# Generated by Django 2.2.13 on 2020-06-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0010_auto_20200604_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='view_source',
            field=models.BooleanField(db_column='viewsource', default=True, null=True),
        ),
    ]
