# Generated by Django 2.2.12 on 2020-06-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0010_auto_20200604_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='public_stats',
        ),
    ]
