# Generated by Django 2.2.13 on 2020-06-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0012_remove_addon_public_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonreviewerflags',
            name='addon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reviewerflags', serialize=False, to='addons.Addon'),
        ),
    ]
