# Generated by Django 2.2.14 on 2020-07-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0013_auto_20200625_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='view_source',
        ),
    ]
