# Generated by Django 2.2.14 on 2020-07-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0014_remove_addon_view_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonreviewerflags',
            name='auto_approval_disabled_until_next_approval',
            field=models.NullBooleanField(default=None),
        ),
    ]
