# Generated by Django 2.2.14 on 2020-07-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0016_addonreviewerflags_auto_approval_disabled_until_next_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonreviewerflags',
            name='notified_about_expiring_delayed_rejections',
            field=models.NullBooleanField(default=None),
        ),
    ]
