# Generated by Django 2.2.15 on 2020-09-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0018_auto_20200803_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonapprovalscounter',
            name='last_content_review',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
