# Generated by Django 2.2.15 on 2020-08-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0019_auto_20200901_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonguid',
            name='hashed_guid',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
