# Generated by Django 2.2.16 on 2020-09-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addons", "0021_auto_20200909_1302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addonguid",
            name="hashed_guid",
            field=models.CharField(max_length=64),
        ),
    ]
