# Generated by Django 2.2.16 on 2020-09-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("addons", "0022_auto_20200916_0802"),
    ]

    operations = [
        migrations.RemoveField(model_name="addon", name="total_downloads",),
    ]
