# Generated by Django 2.2.16 on 2020-10-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0024_auto_20200923_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addonreviewerflags',
            name='notified_about_expiring_info_request',
        ),
        migrations.RemoveField(
            model_name='addonreviewerflags',
            name='pending_info_request',
        ),
    ]
