# Generated by Django 2.2.17 on 2020-11-06 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jsonfield_backport.models
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0025_auto_20201028_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonRegionalRestrictions',
            fields=[
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('addon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='regional_restrictions', serialize=False, to='addons.Addon')),
                ('excluded_regions', django_jsonfield_backport.models.JSONField(default=list)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SearchMixin, olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
