# Generated by Django 2.2.17 on 2021-01-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0027_auto_20201119_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonregionalrestrictions',
            name='addon',
            field=models.OneToOneField(help_text='Add-on id this item will point to.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='regional_restrictions', serialize=False, to='addons.Addon'),
        ),
    ]
