# Generated by Django 2.2.17 on 2021-01-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0028_auto_20210114_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppSupport',
        ),
    ]
