# Generated by Django 2.2.17 on 2021-01-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0028_auto_20210114_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='addons',
        ),
        # migrations.RemoveConstraint(
        #     model_name='addoncategory',
        #     name='addon_id',
        # ),
        # migrations.RemoveIndex(
        #     model_name='addoncategory',
        #     name='category_addon_idx',
        # ),
        migrations.RemoveField(
            model_name='addon',
            name='categories',
        ),
        migrations.AlterField(
            model_name='addoncategory',
            name='category',
            field=models.SmallIntegerField(),
        ),
        migrations.RenameField(
            model_name='addoncategory',
            old_name='category',
            new_name='category_id',
        ),
        migrations.AddIndex(
            model_name='addoncategory',
            index=models.Index(fields=['category_id', 'addon'], name='category_id_addon_idx'),
        ),
        migrations.AddConstraint(
            model_name='addoncategory',
            constraint=models.UniqueConstraint(fields=('addon', 'category_id'), name='category_id_addon_id'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
