# Generated by Django 2.2.17 on 2021-01-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0029_delete_appsupport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='addons',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='categories',
        ),
        migrations.RunSQL(
            "ALTER TABLE `addons_categories` DROP FOREIGN KEY `addons_categories_category_id_f4f5c093_fk_categories_id`;",
            state_operations=[
                migrations.AlterField(
                    model_name='addoncategory',
                    name='category',
                    field=models.PositiveIntegerField(),
                ),
                migrations.RenameField(
                    model_name='addoncategory',
                    old_name='category',
                    new_name='category_id',
                ),
                migrations.RemoveConstraint(
                    model_name='addoncategory',
                    name='addon_id',
                ),
                migrations.RemoveIndex(
                    model_name='addoncategory',
                    name='category_addon_idx',
                ),
                migrations.AddIndex(
                    model_name='addoncategory',
                    index=models.Index(fields=['category_id', 'addon'], name='category_addon_idx'),
                ),
                migrations.AddConstraint(
                    model_name='addoncategory',
                    constraint=models.UniqueConstraint(fields=('addon', 'category_id'), name='addon_id'),
                ),
            ],
        ),
    ]
