# Generated by Django 2.2.17 on 2021-01-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0029_auto_20210118_1527'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='addoncategory',
            name='addon_id',
        ),
        migrations.RemoveIndex(
            model_name='addoncategory',
            name='category_addon_idx',
        ),
    ]
