# Generated by Django 2.2.18 on 2021-02-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0030_auto_20210118_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
