# Generated by Django 2.2.17 on 2021-03-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0031_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonreviewerflags',
            name='auto_approval_disabled_unlisted',
            field=models.NullBooleanField(default=None),
        ),
    ]
