# Generated by Django 2.2.21 on 2021-05-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0032_addonreviewerflags_auto_approval_disabled_unlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonreviewerflags',
            name='auto_approval_disabled_unlisted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='addonreviewerflags',
            name='auto_approval_disabled_until_next_approval',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='addonreviewerflags',
            name='notified_about_auto_approval_delay',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='addonreviewerflags',
            name='notified_about_expiring_delayed_rejections',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
