# Generated by Django 2.2.23 on 2021-06-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0033_auto_20210511_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonreviewerflags',
            name='auto_approval_disabled_until_next_approval_unlisted',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
