# Generated by Django 3.2.6 on 2021-08-12 17:26

from django.db import migrations, models

import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0034_addonreviewerflags_auto_approval_disabled_until_next_approval_unlisted'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='addoncategory',
            constraint=models.UniqueConstraint(fields=('addon', 'category_id'), name='addons_categories_addon_category_id'),
        ),
        migrations.AddIndex(
            model_name='addon',
            index=models.Index(fields=['created'], name='addons_created_idx'),
        ),
        migrations.AddIndex(
            model_name='addon',
            index=models.Index(fields=['status'], name='addons_status_idx'),
        ),
        migrations.AddIndex(
            model_name='addonuser',
            index=models.Index(fields=['listed'], name='addons_users_listed_idx'),
        ),
        migrations.AddIndex(
            model_name='addonuser',
            index=olympia.amo.models.LongNameIndex(fields=['addon', 'user', 'listed'], name='addons_users_addon_user_listed_idx'),
        ),
        migrations.AddIndex(
            model_name='addonuser',
            index=models.Index(fields=['addon', 'listed'], name='addons_users_addon_listed_idx'),
        ),
        migrations.AddIndex(
            model_name='preview',
            index=models.Index(fields=['addon'], name='previews_addon_idx'),
        ),
        migrations.AddConstraint(
            model_name='addonuser',
            constraint=models.UniqueConstraint(fields=('addon', 'user'), name='addons_users_addon_user'),
        ),
        migrations.RemoveConstraint(
            model_name='addoncategory',
            name='addon_id',
        ),
        migrations.RemoveConstraint(
            model_name='addonuser',
            name='addon_id',
        ),
        migrations.RemoveIndex(
            model_name='addon',
            name='created_idx',
        ),
        migrations.RemoveIndex(
            model_name='addon',
            name='status',
        ),
        migrations.RemoveIndex(
            model_name='addonuser',
            name='listed',
        ),
        migrations.RemoveIndex(
            model_name='addonuser',
            name='addon_user_listed_idx',
        ),
        migrations.RemoveIndex(
            model_name='addonuser',
            name='addon_listed_idx',
        ),
        migrations.RemoveIndex(
            model_name='preview',
            name='addon_id',
        ),
    ]
