# Generated by Django 3.2.12 on 2022-02-15 12:00

from django.db import migrations


def create_waffle_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.create(
        name='allow-deleted-guid-reuse',
        active=False,
        note='Allow deleted add-on guid reuse by original author(s)',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0035_auto_20210812_1726'),
    ]

    operations = [migrations.RunPython(create_waffle_switch)]
