# Generated by Django 3.2.12 on 2022-03-21 15:45

from django.db import migrations
from django.db.models import Q

from olympia.addons.tasks import index_addons

from . import fix_contributions_url


def contributions_url_to_from_www(apps, schema_editor):
    Addon = apps.get_model('addons', 'Addon')
    to_index = []

    for addon in Addon.unfiltered.filter(contributions__isnull=False, ~Q(contributions='')):
        try:
            new_url = fix_contributions_url(addon.contributions)
            if new_url != addon.contributions:
                addon.contributions = new_url
                addon.save()
                to_index.append(addon.id)
        except ValueError:
            pass
    if to_index:
        index_addons.delay(to_index)


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0036_add_allow_deleted_guid_reuse_switch'),
    ]

    operations = [migrations.RunPython(contributions_url_to_from_www)]
