# Generated by Django 3.2.13 on 2022-05-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0037_auto_20220321_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Extension'), (2, 'Deprecated Complete Theme'), (3, 'Dictionary'), (4, 'Search Engine'), (5, 'Language Pack (Application)'), (6, 'Language Pack (Add-on)'), (7, 'Plugin'), (9, 'Deprecated LWT'), (10, 'Theme (Static)'), (12, 'Site Permission')], db_column='addontype_id', default=1),
        ),
        migrations.AlterField(
            model_name='replacementaddon',
            name='path',
            field=models.CharField(help_text='Add-on and collection paths need to end with "/"', max_length=255, null=True),
        ),
    ]
