# Generated by Django 3.2.13 on 2022-05-31 09:53

from django.db import migrations

sql_query = """SELECT DISTINCT `a`.`guid`
FROM
    `addons` `a`
    JOIN `blocklist_block` `b` ON `b`.`guid` = `a`.`guid` COLLATE utf8mb4_unicode_ci
    LEFT JOIN `denied_guids` `d` on `d`.`guid` = `a`.`guid`
WHERE
    `min_version` = "0" AND `max_version` = "*" AND `a`.`status` = 11
AND
    `d`.`guid` IS NULL;"""


def fix_missing_denied_guids_for_blocked_addons(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(sql_query)
        rows = cursor.fetchall()
    missing_denied_guids = [row[0] for row in rows]
    DeniedGuid = apps.get_model('addons', 'DeniedGuid')
    DeniedGuid.objects.bulk_create(
        [DeniedGuid(guid=guid) for guid in missing_denied_guids]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0038_auto_20220530_1639'),
    ]

    operations = [
        migrations.RunPython(fix_missing_denied_guids_for_blocked_addons),
    ]
