# Generated by Django 3.2.16 on 2022-10-11 11:04

from django.db import migrations
from olympia.constants.base import _ADDON_SITE_PERMISSION


def delete_site_permissions(apps, schema_editor):
    Addon = apps.get_model('addons', 'Addon')

    # Hard delete the now obsolete site permission add-ons.
    Addon.unfiltered.filter(type=_ADDON_SITE_PERMISSION).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0039_auto_20220531_0953'),
    ]

    operations = [migrations.RunPython(delete_site_permissions)]
