# Generated by Django 3.2.16 on 2022-11-22 13:13

from django.db import migrations, models
import django.db.models.deletion
import olympia.translations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('addons', '0040_auto_20221011_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='description',
            field=olympia.translations.fields.PurifiedField(blank=True, db_column='description', max_length=15000, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Addon_description_set+', require_locale=True, short=False, to='translations.PurifiedTranslation', to_field='id', unique=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='developer_comments',
            field=olympia.translations.fields.PurifiedField(blank=True, db_column='developercomments', max_length=3000, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Addon_developer_comments_set+', require_locale=True, short=True, to='translations.PurifiedTranslation', to_field='id', unique=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='eula',
            field=olympia.translations.fields.PurifiedField(blank=True, db_column='eula', max_length=350000, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Addon_eula_set+', require_locale=True, short=True, to='translations.PurifiedTranslation', to_field='id', unique=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='homepage',
            field=olympia.translations.fields.TranslatedField(blank=True, db_column='homepage', max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Addon_homepage_set+', require_locale=True, short=True, to='translations.Translation', to_field='id', unique=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='privacy_policy',
            field=olympia.translations.fields.PurifiedField(blank=True, db_column='privacypolicy', max_length=150000, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Addon_privacy_policy_set+', require_locale=True, short=True, to='translations.PurifiedTranslation', to_field='id', unique=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='support_email',
            field=olympia.translations.fields.TranslatedField(blank=True, db_column='supportemail', max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Addon_support_email_set+', require_locale=True, short=True, to='translations.Translation', to_field='id', unique=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='support_url',
            field=olympia.translations.fields.TranslatedField(blank=True, db_column='supporturl', max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Addon_support_url_set+', require_locale=True, short=True, to='translations.Translation', to_field='id', unique=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Extension'), (2, 'Deprecated Complete Theme'), (3, 'Dictionary'), (4, 'Deprecated Search Engine'), (5, 'Language Pack (Application)'), (6, 'Deprecated Language Pack (Add-on)'), (7, 'Deprecated Plugin'), (9, 'Deprecated LWT'), (10, 'Theme (Static)'), (12, 'Site Permission')], db_column='addontype_id', default=1),
        ),
        migrations.AlterField(
            model_name='preview',
            name='caption',
            field=olympia.translations.fields.TranslatedField(blank=True, db_column='caption', max_length=280, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Preview_caption_set+', require_locale=True, short=True, to='translations.Translation', to_field='id', unique=True),
        ),
    ]
