# Generated by Django 3.2.16 on 2022-12-05 13:28

from django.db import migrations
import django.db.models.deletion
import olympia.translations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('addons', '0041_auto_20221122_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=olympia.translations.fields.TranslatedField(blank=True, db_column='name', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Addon_name_set+', require_locale=True, short=True, to='translations.Translation', to_field='id', unique=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='summary',
            field=olympia.translations.fields.LinkifiedField(blank=True, db_column='summary', max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Addon_summary_set+', require_locale=True, short=True, to='translations.LinkifiedTranslation', to_field='id', unique=True),
        ),
    ]
