# Generated by Django 3.2.16 on 2023-01-30 12:10

from django.db import migrations, models


def create_initial_auto_approval_delayed_until_unlisted(apps, schema_editor):
    AddonReviewerFlags = apps.get_model('addons', 'AddonReviewerFlags')
    AddonReviewerFlags.objects.filter(auto_approval_delayed_until__isnull=False).update(
        auto_approval_delayed_until_unlisted=models.F('auto_approval_delayed_until')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0042_auto_20221205_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonreviewerflags',
            name='auto_approval_delayed_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='addonreviewerflags',
            name='auto_approval_delayed_until_unlisted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(create_initial_auto_approval_delayed_until_unlisted),
    ]
