# Generated by Django 4.2.1 on 2023-05-24 08:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):
    dependencies = [
        (
            'addons',
            '0044_remove_addonreviewerflags_notified_about_auto_approval_delay_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonBrowserMapping',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ('modified', models.DateTimeField(auto_now=True)),
                ('browser', models.PositiveSmallIntegerField(choices=[(1, 'chrome')])),
                ('extension_id', models.CharField(db_index=True, max_length=255)),
                (
                    'addon',
                    models.ForeignKey(
                        help_text='Add-on id this item will point to. If you do not know the id, paste the slug instead and it will be transformed automatically for you. You can also use the magnifying glass to see all the available add-ons if you have access to the add-on admin page.',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='addons.addon',
                    ),
                ),
            ],
            options={
                'unique_together': {('browser', 'extension_id')},
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
