# Generated by Django 4.2.3 on 2023-09-06 12:20

from django.db import migrations


ANDROID_STATICTHEME_CAT_IDS = {
    'abstract': 400,
    'causes': 420,
    'fashion': 424,
    'film-and-tv': 426,
    'firefox': 408,
    'foxkeh': 410,
    'holiday': 428,
    'music': 422,
    'nature': 402,
    'other': 414,
    'scenery': 406,
    'seasonal': 412,
    'solid': 418,
    'sports': 404,
    'websites': 416,
}.values()


def delete_android_static_theme_addon_category(apps, schema_editor):
    AddonCategory = apps.get_model('addons', 'AddonCategory')
    AddonCategory.objects.filter(category_id__in=ANDROID_STATICTHEME_CAT_IDS).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('addons', '0046_auto_20230612_1057'),
    ]

    operations = [
        migrations.RunPython(delete_android_static_theme_addon_category),
    ]
