# Generated by Django 4.2.7 on 2023-11-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addons", "0047_addonuser_original_role_alter_addon_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="preview",
            name="image_hash",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="addon",
            name="icon_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="addonuser",
            name="original_role",
            field=models.SmallIntegerField(
                choices=[(5, "Owner"), (4, "Developer")],
                default=4,
                editable=False,
                help_text="Role to assign if user is unbanned",
            ),
        ),
    ]
