# Generated by Django 4.2.7 on 2023-11-29 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):
    dependencies = [
        ("addons", "0047_addonuser_original_role_alter_addon_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedPreviewFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "backup_name",
                    models.CharField(
                        blank=True, default=None, max_length=75, null=True
                    ),
                ),
            ],
            options={
                "get_latest_by": "created",
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="addonuser",
            name="original_role",
            field=models.SmallIntegerField(
                choices=[(5, "Owner"), (4, "Developer")],
                default=4,
                editable=False,
                help_text="Role to assign if user is unbanned",
            ),
        ),
        migrations.CreateModel(
            name="DisabledAddonContent",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "addon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="content_deleted_on_force_disable",
                        serialize=False,
                        to="addons.addon",
                    ),
                ),
                (
                    "icon_backup_name",
                    models.CharField(
                        blank=True, default=None, max_length=75, null=True
                    ),
                ),
            ],
            options={
                "get_latest_by": "created",
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.AddField(
            model_name="deletedpreviewfile",
            name="disabled_addon_content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="addons.disabledaddoncontent",
            ),
        ),
        migrations.AddField(
            model_name="deletedpreviewfile",
            name="preview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="addons.preview"
            ),
        ),
    ]
