# Generated by Django 4.2.7 on 2023-12-06 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('addons', '0048_deletedpreviewfile_alter_addonuser_original_role_and_more'),
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            'UPDATE `translations` '
            'JOIN `addons` ON `translations`.`id` = `addons`.`homepage` '
            'SET `localized_string`="" '
            'WHERE `translations`.`localized_string` != "" '
            'AND NOT `translations`.`localized_string` LIKE "http://%" '
            'AND NOT `translations`.`localized_string` LIKE "https://%" ',
            reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(
            'UPDATE `translations` '
            'JOIN `addons` ON `translations`.`id` = `addons`.`supporturl` '
            'SET `localized_string`="" '
            'WHERE `translations`.`localized_string` != "" '
            'AND NOT `translations`.`localized_string` LIKE "http://%" '
            'AND NOT `translations`.`localized_string` LIKE "https://%" ',
            reverse_sql=migrations.RunSQL.noop),
    ]
