# Generated by Django 4.2.16 on 2024-10-21 13:48

from django.db import migrations, models
import django.db.models.deletion
import olympia.translations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        ('addons', '0052_auto_20240927_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='summary',
            field=olympia.translations.fields.NoURLsField(blank=True, db_column='summary', max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, require_locale=True, short=True, to='translations.NoURLsTranslation', to_field='id', unique=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Extension'), (2, 'Deprecated Complete Theme'), (3, 'Dictionary'), (4, 'Deprecated Search Engine'), (5, 'Language Pack'), (6, 'Deprecated Language Pack (Add-on)'), (7, 'Deprecated Plugin'), (9, 'Deprecated LWT'), (10, 'Theme'), (12, 'Deprecated Site Permission')], db_column='addontype_id', default=1),
        ),
    ]
