# Generated by Django 4.2.17 on 2025-01-21 11:41

from django.db import migrations

def forwards_func(apps, schema_editor):
    Addon = apps.get_model('addons', 'Addon')
    Addon.unfiltered.filter(default_locale='es').update(default_locale='es-es')


def backwards_func(apps, schema_editor):
    Addon = apps.get_model('addons', 'Addon')
    Addon.unfiltered.filter(default_locale='es-es').update(default_locale='es')


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0053_alter_addon_summary_alter_addon_type'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func)
    ]
