# Generated by Django 4.2.23 on 2025-08-29 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models
import olympia.translations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_update_all_es_translations_to_es-es'),
        ('addons', '0054_update_default_locale_es_to_es-es'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonListingInfo',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ('modified', models.DateTimeField(auto_now=True)),
                (
                    'noindex_until',
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    'addon',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='addons.addon'
                    ),
                ),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
