# Generated by Django 4.2.19 on 2025-02-26 16:00

from django.db import migrations
from django.db.models import F
from olympia.constants.base import STATUS_APPROVED

def update_summaries(apps, schema_editor):
    """Migration to copy localized_string (which should be plain text) into
    localized_string_clean for translations of summaries that had HTML links
    in them.

    Essentially transforming
    Foo <a href="https://outgoing/foo.com">https://foo.com</a>
    into
    Foo https://foo.com
    """
    Translation = apps.get_model('translations', 'Translation')
    Addon = apps.get_model('addons', 'Addon')
    qs = Translation.objects.filter(
        id__in=Addon.unfiltered.filter(
            status=STATUS_APPROVED,
            summary__isnull=False).values_list('summary', flat=True),
        localized_string_clean__contains='href=')
    qs.update(localized_string_clean=F('localized_string'))


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0054_update_default_locale_es_to_es-es'),
    ]

    operations = [
        migrations.RunPython(update_summaries, lambda a, s: None)
    ]
