# Generated by Django 4.2.27 on 2026-01-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0057_alter_addon_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonapprovalscounter',
            name='last_content_review_pass',
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Incomplete'), (3, 'Awaiting Review'), (4, 'Approved'), (15, 'Listing Content Rejected'), (5, 'Disabled by Mozilla'), (11, 'Deleted')], default=0),
        ),
    ]
