# Generated by Django 4.2.28 on 2026-02-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0058_addonapprovalscounter_last_content_review_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonapprovalscounter',
            name='content_review_status',
            field=models.SmallIntegerField(choices=[(0, 'Unreviewed'), (1, 'Pending, accepted content changed'), (2, 'Pass'), (3, 'Fail'), (4, 'Pending, New review requested')], db_index=True, null=True),
        ),
    ]
