# Generated by Django 4.2.28 on 2026-02-05 11:42

from django.db import models, migrations


def backfill_content_review_status(apps, schema_editor):
    AddonApprovalsCounter = apps.get_model('addons', 'AddonApprovalsCounter')
    for counter in AddonApprovalsCounter.objects.filter(content_review_status__isnull=True):
        # if we have a last_content_review date then we know it passed, and hasn't changed since
        if counter.last_content_review is not None:
            counter.content_review_status = 2  # CONTENT_REVIEW_STATUSES.PASS
        # If last_content_review_pass is False we know it failed.
        elif counter.last_content_review_pass is False:
            counter.content_review_status = 3  # CONTENT_REVIEW_STATUSES.FAIL
        # Otherwise we don't know for sure
        # - might never have been reviewed (e.g. no listed versions).
        # - might have been reviewed and failed.
        # - might have been reviewed but then the content changed.
        else:
            counter.content_review_status = 0  # CONTENT_REVIEW_STATUSES.UNREVIEWED
        counter.save(update_fields=['content_review_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0059_add_addonapprovalscounter_content_review_status'),
    ]

    operations = [
        migrations.RunPython(backfill_content_review_status, reverse_code=migrations.RunPython.noop),
    ]
