# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('reporter_email', models.CharField(default=None, help_text='The provided email of the reporter, if not authenticated.', max_length=255, null=True)),
                ('reporter_name', models.CharField(default=None, help_text='The provided name of the reporter, if not authenticated.', max_length=255, null=True)),
                ('country_code', models.CharField(default=None, max_length=2, null=True)),
                ('guid', models.CharField(max_length=255, null=True)),
                ('message', models.TextField(blank=True, help_text='The body/content of the abuse report.')),
                ('client_id', models.CharField(blank=True, default=None, help_text="The client's hashed telemetry ID.", max_length=64, null=True)),
                ('addon_name', models.CharField(blank=True, default=None, help_text='The add-on name in the locale used by the client.', max_length=255, null=True)),
                ('addon_summary', models.CharField(blank=True, default=None, help_text='The add-on summary in the locale used by the client.', max_length=255, null=True)),
                ('addon_version', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('addon_signature', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'None'), (1, 'Curated and partner'), (2, 'Curated'), (3, 'Partner'), (4, 'Non-curated'), (5, 'Unsigned'), (6, 'Broken'), (7, 'Unknown'), (8, 'Missing'), (9, 'Preliminary'), (10, 'Signed'), (11, 'System'), (12, 'Privileged')], default=None, null=True)),
                ('application', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Firefox'), (61, 'Firefox for Android')], default=1, null=True)),
                ('application_version', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('application_locale', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('operating_system', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('operating_system_version', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('install_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('reason', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'None'), (1, 'Damages computer and/or data'), (2, 'Creates spam or advertising'), (3, 'Changes search / homepage / new tab page without informing user'), (5, 'Doesn’t work, breaks websites, or slows Firefox down'), (6, 'Hateful, violent, or illegal content'), (7, 'Pretends to be something it’s not'), (9, "Wasn't wanted / impossible to get rid of"), (11, 'DSA: It contains hateful, violent, deceptive, or other inappropriate content'), (12, 'DSA: It violates the law or contains content that violates the law'), (13, "DSA: It violates Mozilla's Add-on Policies"), (14, 'DSA: Something else'), (20, 'Feedback: It does not work, breaks websites, or slows down Firefox'), (21, "Feedback: It's spam"), (127, 'Other')], default=None, null=True)),
                ('addon_install_origin', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('addon_install_method', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'None'), (1, 'Add-on Manager Web API'), (2, 'Direct link'), (3, 'Install Trigger'), (4, 'From File'), (5, 'Webext management API'), (6, 'Drag & Drop'), (7, 'Sideload'), (8, 'File URL'), (9, 'Enterprise Policy'), (10, 'Included in build'), (11, 'System Add-on'), (12, 'Temporary Add-on'), (13, 'Sync'), (14, 'URL'), (127, 'Other')], default=None, help_text='For addon_install_method and addon_install_source specifically,if an unsupported value is sent, it will be silently changed to otherinstead of raising a 400 error.', null=True)),
                ('addon_install_source', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'None'), (1, 'Add-ons Manager'), (2, 'Add-ons Debugging'), (3, 'Preferences'), (4, 'AMO'), (5, 'App Profile'), (6, 'Disco Pane'), (7, 'Included in build'), (8, 'Extension'), (9, 'Enterprise Policy'), (10, 'File URL'), (11, 'GMP Plugin'), (12, 'Internal'), (13, 'Plugin'), (14, 'Return to AMO'), (15, 'Sync'), (16, 'System Add-on'), (17, 'Temporary Add-on'), (18, 'Unknown'), (19, 'Windows Registry (User)'), (20, 'Windows Registry (Global)'), (21, 'System Add-on (Profile)'), (22, 'System Add-on (Update)'), (23, 'System Add-on (Bundled)'), (24, 'Built-in Add-on'), (25, 'System-wide Add-on (User)'), (26, 'Application Add-on'), (27, 'System-wide Add-on (OS Share)'), (28, 'System-wide Add-on (OS Local)'), (127, 'Other')], default=None, help_text='For addon_install_method and addon_install_source specifically,if an unsupported value is sent, it will be silently changed to otherinstead of raising a 400 error.', null=True)),
                ('addon_install_source_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('report_entry_point', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'None'), (1, 'Uninstall'), (2, 'Menu'), (3, 'Toolbar context menu'), (4, 'AMO'), (5, 'Unified extensions context menu')], default=None, null=True)),
                ('location', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'None'), (1, 'Add-on page on AMO'), (2, 'Inside Add-on'), (3, 'Both on AMO and inside Add-on')], default=None, help_text='Where the content being reported is located - on AMO or inside the add-on.', null=True)),
                ('reporter_appeal_date', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'abuse_reports',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CinderDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'User ban'), (2, 'Add-on disable'), (3, 'Escalate add-on to reviewers'), (5, 'Rating delete'), (6, 'Collection delete'), (7, 'Approved (no action)'), (8, 'Add-on version reject'), (9, 'Add-on version delayed reject warning'), (10, 'Approved (new version approval)'), (11, 'Invalid report, so ignored')])),
                ('cinder_id', models.CharField(default=None, max_length=36, null=True, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, max_length=1000)),
            ],
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CinderPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('expose_in_reviewer_tools', models.BooleanField(default=False)),
                ('default_cinder_action', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'User ban'), (2, 'Add-on disable'), (3, 'Escalate add-on to reviewers'), (5, 'Rating delete'), (6, 'Collection delete'), (7, 'Approved (no action)'), (8, 'Add-on version reject'), (9, 'Add-on version delayed reject warning'), (10, 'Approved (new version approval)'), (11, 'Invalid report, so ignored')], null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='abuse.cinderpolicy')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CinderJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('job_id', models.CharField(max_length=36, unique=True)),
                ('resolvable_in_reviewer_tools', models.BooleanField(default=None, null=True)),
                ('decision', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinder_job', to='abuse.cinderdecision')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
