# Generated by Django 2.2.6 on 2019-10-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abusereport',
            name='report_entry_point',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'None'), (1, 'Uninstall'), (
                2, 'Menu'), (3, 'Toolbar context menu'), (4, 'AMO')], default=None, null=True),
        ),
    ]
