# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addons', '0001_initial'),
        ('abuse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinderjob',
            name='target_addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addons.addon'),
        ),
        migrations.AddField(
            model_name='cinderdecision',
            name='addon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addons.addon'),
        ),
        migrations.AddField(
            model_name='cinderdecision',
            name='appeal_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appealed_decisions', to='abuse.cinderjob'),
        ),
    ]
