# Generated by Django 2.2.9 on 2020-02-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0002_add_amo_entrypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='abusereport',
            name='addon_install_source_url',
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True),
        ),
    ]
