# Generated by Django 4.2.13 on 2024-06-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bandwagon', '0001_initial'),
        ('abuse', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinderdecision',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bandwagon.collection'),
        ),
        migrations.AddField(
            model_name='cinderdecision',
            name='policies',
            field=models.ManyToManyField(to='abuse.cinderpolicy'),
        ),
    ]
