# Generated by Django 2.2.20 on 2021-05-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0003_abusereport_addon_install_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abusereport',
            name='addon_install_source',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'None'), (1, 'Add-ons Manager'), (2, 'Add-ons Debugging'), (3, 'Preferences'), (4, 'AMO'), (5, 'App Profile'), (6, 'Disco Pane'), (7, 'Included in build'), (8, 'Extension'), (9, 'Enterprise Policy'), (10, 'File URL'), (11, 'GMP Plugin'), (12, 'Internal'), (13, 'Plugin'), (14, 'Return to AMO'), (15, 'Sync'), (16, 'System Add-on'), (17, 'Temporary Add-on'), (18, 'Unknown'), (19, 'Windows Registry (User)'), (20, 'Windows Registry (Global)'), (21, 'System Add-on (Profile)'), (22, 'System Add-on (Update)'), (23, 'System Add-on (Bundled)'), (24, 'System Add-on (Builtin)'), (25, 'System Add-on (User)'), (26, 'Application Add-on'), (27, 'System Add-on (OS Share)'), (28, 'System Add-on (OS Local)'), (127, 'Other')], default=None, null=True),
        ),
    ]
