# Generated by Django 3.2.6 on 2021-08-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0005_auto_20210729_1339'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='abusereport',
            index=models.Index(fields=['created'], name='abuse_reports_created_idx'),
        ),
        migrations.RemoveIndex(
            model_name='abusereport',
            name='created_idx',
        ),
    ]
