# Generated by Django 3.2.15 on 2022-12-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0007_auto_20220803_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abusereport',
            name='report_entry_point',
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (None, 'None'),
                    (1, 'Uninstall'),
                    (2, 'Menu'),
                    (3, 'Toolbar context menu'),
                    (4, 'AMO'),
                    (5, 'Unified extensions context menu'),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
