# Generated by Django 4.2.5 on 2023-10-06 10:35

from django.db import migrations


def create_waffle_switch_if_it_doesnt_already_exist(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.get_or_create(
        name='enable-cinder-reporting',
        defaults={
            'active': False,
            'note': 'Enable reporting content violations via abuse api to cinder',
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ('abuse', '0010_cinderreport'),
        ('waffle', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_waffle_switch_if_it_doesnt_already_exist)
    ]
