# Generated by Django 4.2.5 on 2023-10-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abuse', '0011_auto_20231006_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinderreport',
            name='appeal_id',
            field=models.CharField(default=None, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='cinderreport',
            name='decision_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cinderreport',
            name='decision_action',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'No decision'),
                    (1, 'User ban'),
                    (2, 'Add-on disable'),
                    (3, 'Escalate add-on to reviewers'),
                    (4, 'Escalate user to reviewers'),
                    (5, 'Rating delete'),
                    (6, 'Collection delete'),
                    (7, 'Approved (no action)'),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name='cinderreport',
            name='decision_id',
            field=models.CharField(default=None, max_length=36, null=True, unique=True),
        ),
    ]
