# Generated by Django 4.2.6 on 2023-10-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abuse', '0012_cinderreport_appeal_id_cinderreport_decision_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abusereport',
            name='reason',
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (None, 'None'),
                    (1, 'Damages computer and/or data'),
                    (2, 'Creates spam or advertising'),
                    (
                        3,
                        'Changes search / homepage / new tab page without informing user',
                    ),
                    (5, 'Doesn’t work, breaks websites, or slows Firefox down'),
                    (6, 'Hateful, violent, or illegal content'),
                    (7, 'Pretends to be something it’s not'),
                    (9, "Wasn't wanted / impossible to get rid of"),
                    (
                        11,
                        'DSA: It contains hateful, violent, deceptive, or other inappropriate content',
                    ),
                    (
                        12,
                        'DSA: It violates the law or contains content that violates the law',
                    ),
                    (13, 'DSA: It violates Add-on Policies'),
                    (
                        20,
                        'Feedback: It does not work, breaks websites, or slows down Firefox',
                    ),
                    (21, "Feedback: It's spam. Wasn't wanted or can't be uninstalled"),
                    (127, 'Other'),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
