# Generated by Django 4.2.6 on 2023-10-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ratings', '0009_alter_deniedratingword_word'),
        ('abuse', '0014_abusereport_location'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='abusereport',
            name='just_one_of_guid_and_user_must_be_set',
        ),
        migrations.AddField(
            model_name='abusereport',
            name='rating',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='abuse_reports',
                to='ratings.rating',
            ),
        ),
        migrations.AddConstraint(
            model_name='abusereport',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(('guid', ''), _negated=True),
                        ('guid__isnull', False),
                        ('rating__isnull', True),
                        ('user__isnull', True),
                    ),
                    models.Q(
                        ('guid__isnull', True),
                        ('rating__isnull', True),
                        ('user__isnull', False),
                    ),
                    models.Q(
                        ('guid__isnull', True),
                        ('rating__isnull', False),
                        ('user__isnull', True),
                    ),
                    _connector='OR',
                ),
                name='just_one_of_guid_user_rating_must_be_set',
            ),
        ),
    ]
