# Generated by Django 4.2.6 on 2023-11-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "bandwagon",
            "0007_alter_collection_description_alter_collection_name_and_more",
        ),
        (
            "abuse",
            "0015_remove_abusereport_just_one_of_guid_and_user_must_be_set_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="abusereport",
            name="just_one_of_guid_user_rating_must_be_set",
        ),
        migrations.AddField(
            model_name="abusereport",
            name="collection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="abuse_reports",
                to="bandwagon.collection",
            ),
        ),
        migrations.AlterField(
            model_name="cinderreport",
            name="decision_action",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No decision"),
                    (1, "User ban"),
                    (2, "Add-on disable"),
                    (3, "Escalate add-on to reviewers"),
                    (5, "Rating delete"),
                    (6, "Collection delete"),
                    (7, "Approved (no action)"),
                ],
                default=0,
            ),
        ),
        migrations.AddConstraint(
            model_name="abusereport",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(("guid", ""), _negated=True),
                        ("collection__isnull", True),
                        ("guid__isnull", False),
                        ("rating__isnull", True),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("collection__isnull", True),
                        ("guid__isnull", True),
                        ("rating__isnull", True),
                        ("user__isnull", False),
                    ),
                    models.Q(
                        ("collection__isnull", True),
                        ("guid__isnull", True),
                        ("rating__isnull", False),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("collection__isnull", False),
                        ("guid__isnull", True),
                        ("rating__isnull", True),
                        ("user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="just_one_of_guid_user_rating_collection_must_be_set",
            ),
        ),
    ]
