# Generated by Django 4.2.7 on 2023-11-23 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0016_remove_abusereport_just_one_of_guid_user_rating_must_be_set_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinderJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('job_id', models.CharField(max_length=36, unique=True)),
                ('decision_action', models.PositiveSmallIntegerField(choices=[(0, 'No decision'), (1, 'User ban'), (2, 'Add-on disable'), (3, 'Escalate add-on to reviewers'), (5, 'Rating delete'), (6, 'Collection delete'), (7, 'Approved (no action)')], default=0)),
                ('decision_id', models.CharField(default=None, max_length=36, null=True, unique=True)),
                ('decision_date', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CinderJobAppeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('appeal_id', models.CharField(default=None, max_length=36, null=True)),
                ('abuse_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='abuse.abusereport')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='CinderReport',
        ),
        migrations.AddField(
            model_name='abusereport',
            name='cinder_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abuse.cinderjob'),
        ),
    ]
