# Generated by Django 4.2.7 on 2023-11-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0016_remove_abusereport_just_one_of_guid_user_rating_must_be_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinderreport',
            name='decision_id',
            field=models.CharField(default=None, max_length=36, null=True),
        ),
    ]
