# Generated by Django 4.2.7 on 2023-11-27 12:20

from django.db import migrations, models
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0017_cinderjob_cinderjobappeal_delete_cinderreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinderPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.AddField(
            model_name='cinderjob',
            name='policies',
            field=models.ManyToManyField(to='abuse.cinderpolicy'),
        ),
    ]
