# Generated by Django 4.2.8 on 2023-12-12 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abuse', '0019_alter_abusereport_drop_state_options_alter_abusereport_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abusereport',
            name='addon_install_method',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'None'), (1, 'Add-on Manager Web API'), (2, 'Direct link'), (3, 'Install Trigger'), (4, 'From File'), (5, 'Webext management API'), (6, 'Drag & Drop'), (7, 'Sideload'), (8, 'File URL'), (9, 'Enterprise Policy'), (10, 'Included in build'), (11, 'System Add-on'), (12, 'Temporary Add-on'), (13, 'Sync'), (14, 'URL'), (127, 'Other')], default=None, help_text='For addon_install_method and addon_install_source specifically,if an unsupported value is sent, it will be silently changed to otherinstead of raising a 400 error.', null=True),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='addon_install_source',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'None'), (1, 'Add-ons Manager'), (2, 'Add-ons Debugging'), (3, 'Preferences'), (4, 'AMO'), (5, 'App Profile'), (6, 'Disco Pane'), (7, 'Included in build'), (8, 'Extension'), (9, 'Enterprise Policy'), (10, 'File URL'), (11, 'GMP Plugin'), (12, 'Internal'), (13, 'Plugin'), (14, 'Return to AMO'), (15, 'Sync'), (16, 'System Add-on'), (17, 'Temporary Add-on'), (18, 'Unknown'), (19, 'Windows Registry (User)'), (20, 'Windows Registry (Global)'), (21, 'System Add-on (Profile)'), (22, 'System Add-on (Update)'), (23, 'System Add-on (Bundled)'), (24, 'Built-in Add-on'), (25, 'System-wide Add-on (User)'), (26, 'Application Add-on'), (27, 'System-wide Add-on (OS Share)'), (28, 'System-wide Add-on (OS Local)'), (127, 'Other')], default=None, help_text='For addon_install_method and addon_install_source specifically,if an unsupported value is sent, it will be silently changed to otherinstead of raising a 400 error.', null=True),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='addon_name',
            field=models.CharField(blank=True, default=None, help_text='The add-on name in the locale used by the client.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='addon_summary',
            field=models.CharField(blank=True, default=None, help_text='The add-on summary in the locale used by the client.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='client_id',
            field=models.CharField(blank=True, default=None, help_text="The client's hashed telemetry ID.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='location',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'None'), (1, 'Add-on page on AMO'), (2, 'Inside Add-on'), (3, 'Both on AMO and inside Add-on')], default=None, help_text='Where the content being reported is located - on AMO or inside the add-on.', null=True),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='message',
            field=models.TextField(blank=True, help_text='The body/content of the abuse report.'),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='reporter',
            field=models.ForeignKey(blank=True, help_text='The user who submitted the report, if authenticated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='reporter_email',
            field=models.CharField(default=None, help_text='The provided email of the reporter, if not authenticated.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='reporter_name',
            field=models.CharField(default=None, help_text='The provided name of the reporter, if not authenticated.', max_length=255, null=True),
        ),
    ]
