# Generated by Django 4.2.8 on 2024-01-22 15:34

from django.db import migrations


def fill_appealed_by(apps, schema_editor):
    CinderJob = apps.get_model('abuse', 'CinderJob')
    for cinder_job in CinderJob.objects.filter(appeal_job__isnull=False):
        cinder_job.appealed_by.add(cinder_job.appeal_job)

class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0022_rename_appeal_date_abusereport_reporter_appeal_date_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_appealed_by)
    ]
