# Generated by Django 4.2.8 on 2024-01-25 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0022_rename_appeal_date_abusereport_reporter_appeal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinderjob',
            name='decision_notes',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
