# Generated by Django 4.2.9 on 2024-02-01 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0023_cinderjob_decision_notes_alter_cinderjob_appeal_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinderpolicy',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='abuse.cinderpolicy'),
        ),
        migrations.AlterField(
            model_name='cinderpolicy',
            name='uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
