# Generated by Django 4.2.8 on 2024-01-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0023_fill_cinderjob_appealed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinderjob',
            name='appeal_job',
        ),
    ]
