# Generated by Django 4.2.9 on 2024-02-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("addons", "0049_clear_bad_url_data"),
        ("abuse", "0024_cinderpolicy_parent_alter_cinderpolicy_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinderjob",
            name="resolvable_in_reviewer_tools",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="cinderjob",
            name="target_addon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="addons.addon",
            ),
        ),
    ]
