# Generated by Django 4.2.10 on 2024-03-12 09:55

from django.db import migrations, models


def copy_decision_id_to_decision_cinder_id(apps, schema_editor):
    CinderJob = apps.get_model('abuse', 'CinderJob')
    CinderJob.objects.update(decision_cinder_id=models.F('decision_id'))


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0025_cinderjob_resolvable_in_reviewer_tools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinderjob',
            name='decision_cinder_id',
            field=models.CharField(default=None, max_length=36, null=True, unique=True),
        ),
        migrations.RunPython(copy_decision_id_to_decision_cinder_id)
    ]
