# Generated by Django 4.2.11 on 2024-03-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0028_cinderdecision_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinderpolicy',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
