# Generated by Django 4.2.10 on 2024-03-12 09:55

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch, DeleteWaffleSwitch


def rename_waffle_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.update_or_create(
        name='enable-cinder-reporting',
        defaults={'name': 'dsa-job-technical-processing'}
    )

def create_enabled_waffle_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.update_or_create(name='dsa-appeals-review', defaults={'active': True})


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0029_alter_cinderpolicy_name_length'),
    ]

    operations = [
        migrations.RunPython(rename_waffle_switch),
        CreateWaffleSwitch('dsa-abuse-reports-review'),
        migrations.RunPython(create_enabled_waffle_switch),
        CreateWaffleSwitch('dsa-cinder-escalations-review'),
        DeleteWaffleSwitch('enable-cinder-reviewer-tools-integration'),
    ]
