# Generated by Django 4.2.13 on 2024-05-17 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0030_rename_cinder_waffle_switch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinderjob',
            name='appeal_job',
        ),
        migrations.RemoveField(
            model_name='cinderjob',
            name='decision_action',
        ),
        migrations.RemoveField(
            model_name='cinderjob',
            name='decision_cinder_id',
        ),
        migrations.RemoveField(
            model_name='cinderjob',
            name='decision_date',
        ),
        migrations.RemoveField(
            model_name='cinderjob',
            name='decision_notes',
        ),
        migrations.RemoveField(
            model_name='cinderjob',
            name='policies',
        ),
        migrations.AlterField(
            model_name='cinderdecision',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User ban'), (2, 'Add-on disable'), (3, 'Escalate add-on to reviewers'), (5, 'Rating delete'), (6, 'Collection delete'), (7, 'Approved (no action)'), (8, 'Add-on version reject'), (9, 'Add-on version delayed reject warning'), (10, 'Approved (new version approval)'), (11, 'Invalid report, so ignored')]),
        ),
        migrations.AlterField(
            model_name='cinderjob',
            name='decision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinder_job', to='abuse.cinderdecision'),
        ),
    ]
