# Generated by Django 4.2.13 on 2024-05-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0031_remove_cinderjob_appeal_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinderpolicy',
            name='default_cinder_action',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'User ban'), (2, 'Add-on disable'), (3, 'Escalate add-on to reviewers'), (5, 'Rating delete'), (6, 'Collection delete'), (7, 'Approved (no action)'), (8, 'Add-on version reject'), (9, 'Add-on version delayed reject warning'), (10, 'Approved (new version approval)'), (11, 'Invalid report, so ignored')], null=True),
        ),
        migrations.AddField(
            model_name='cinderpolicy',
            name='expose_in_reviewer_tools',
            field=models.BooleanField(default=False),
        ),
    ]
