# Generated by Django 4.2.13 on 2024-06-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0032_cinderpolicy_default_cinder_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abusereport',
            name='illegal_category',
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (None, 'None'),
                    (1, 'Animal welfare'),
                    (2, 'Consumer information infringements'),
                    (3, 'Data protection and privacy violations'),
                    (4, 'Illegal or harmful speech'),
                    (5, 'Intellectual property infringements'),
                    (6, 'Negative effects on civic discourse or elections'),
                    (7, 'Non-consensual behavior'),
                    (8, 'Pornography or sexualized content'),
                    (9, 'Protection of minors'),
                    (10, 'Risk for public security'),
                    (11, 'Scams or fraud'),
                    (12, 'Self-harm'),
                    (13, 'Unsafe, non-compliant, or prohibited products'),
                    (14, 'Violence'),
                    (15, 'Other'),
                ],
                default=None,
                help_text='Type of illegal content',
                null=True,
            ),
        ),
    ]
