# Generated by Django 4.2.13 on 2024-07-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0034_abusereport_illegal_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abusereport',
            name='addon_signature',
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (None, 'None'),
                    (1, 'Curated and partner'),
                    (2, 'Curated'),
                    (3, 'Partner'),
                    (4, 'Non-curated'),
                    (5, 'Unsigned'),
                    (6, 'Broken'),
                    (7, 'Unknown'),
                    (8, 'Missing'),
                    (9, 'Preliminary'),
                    (10, 'Signed'),
                    (11, 'System'),
                    (12, 'Privileged'),
                    (13, 'Not required'),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
