# Generated by Django 4.2.13 on 2024-07-01 23:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0035_alter_abusereport_addon_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abusereport',
            name='appellant_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter_appellants', to='abuse.cinderjob'),
        ),
        migrations.CreateModel(
            name='CinderAppeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(help_text='The content of the appeal.')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abuse.cinderdecision', related_name='appeals')),
                ('reporter_report', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='abuse.abusereport')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
