# Generated by Django 4.2.15 on 2024-08-23 12:36

from django.db import migrations

from olympia.core.db.migrations import RenameWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0036_alter_abusereport_appellant_job_cinderappealtext'),
    ]

    operations = [
        RenameWaffleSwitch('dsa-cinder-escalations-review', 'dsa-cinder-forwarded-review'),
    ]
