# Generated by Django 4.2.15 on 2024-08-19 13:43

from django.db import migrations, models

from olympia.constants.abuse import DECISION_ACTIONS


def migrate_escalate_action_to_is_forwarded(apps, schema_editor):
    CinderDecision = apps.get_model('abuse', 'CinderDecision')
    CinderJob = apps.get_model('abuse', 'CinderJob')

    CinderJob.objects.filter(
        decision__action=DECISION_ACTIONS.AMO_ESCALATE_ADDON
    ).update(
        is_forwarded=True,
        notes=models.functions.Left(
            models.Subquery(
                CinderDecision.objects.filter(pk=models.OuterRef('decision')).values('notes')[:1]
            ),
            255,
        ),
    )
    CinderDecision.objects.filter(action=DECISION_ACTIONS.AMO_ESCALATE_ADDON).delete()


def recreate_escalate_decisions(apps, schema_editor):
    CinderDecision = apps.get_model('abuse', 'CinderDecision')
    CinderJob = apps.get_model('abuse', 'CinderJob')

    CinderDecision.objects.bulk_create(
        CinderDecision(
            cinder_job=job,
            action=DECISION_ACTIONS.AMO_ESCALATE_ADDON,
            notes=job.notes,
            addon=job.target_addon
        )
        for job in CinderJob.objects.filter(is_forwarded=True)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0037_cinderjob_is_forwarded_cinderjob_notes_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_escalate_action_to_is_forwarded, recreate_escalate_decisions)
    ]
