# Generated by Django 4.2.15 on 2024-08-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0038_auto_20240819_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinderdecision',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(12, 'Content already removed (no action)'), (7, 'Approved (no action)'), (2, 'Add-on disable'), (9, 'Add-on version delayed reject warning'), (8, 'Add-on version reject'), (11, 'Invalid report, so ignored'), (5, 'Rating delete'), (10, 'Approved (new version approval)'), (1, 'User ban'), (6, 'Collection delete')]),
        ),
        migrations.AlterField(
            model_name='cinderpolicy',
            name='default_cinder_action',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(12, 'Content already removed (no action)'), (7, 'Approved (no action)'), (2, 'Add-on disable'), (9, 'Add-on version delayed reject warning'), (8, 'Add-on version reject'), (11, 'Invalid report, so ignored'), (5, 'Rating delete'), (10, 'Approved (new version approval)'), (1, 'User ban'), (6, 'Collection delete')], null=True),
        ),
    ]
