# Generated by Django 4.2.16 on 2024-10-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0039_auto_20240829_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinderpolicy',
            options={'verbose_name_plural': 'Cinder Policies'},
        ),
        migrations.RemoveField(
            model_name='abusereport',
            name='appellant_job',
        ),
        migrations.RemoveField(
            model_name='abusereport',
            name='reporter_appeal_date',
        ),
    ]
