# Generated by Django 4.2.16 on 2024-10-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0039_auto_20240829_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinderdecision',
            name='date',
            field=models.DateTimeField(db_column='date', null=True),
        ),
        migrations.RenameField(model_name='cinderdecision', old_name='date', new_name='action_date'),
    ]
