# Generated by Django 4.2.16 on 2024-10-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0041_alter_decision_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cinderdecision',
            table='abuse_cinderdecision',
        ),
    ]
