# Generated by Django 4.2.16 on 2024-10-21 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0052_auto_20240927_1810'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bandwagon', '0008_alter_collection_options_alter_collection_managers_and_more'),
        ('ratings', '0011_remove_rating_one_review_per_user_and_more'),
        ('abuse', '0042_alter_cinderdecision_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CinderDecision',
            new_name='ContentDecision',
        ),
    ]
