# Generated by Django 4.2.16 on 2024-10-28 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0043_rename_cinderdecision_contentdecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinderQueueMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('to_queue', models.CharField(max_length=128)),
                ('cinder_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_moves', to='abuse.cinderjob')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
    ]
