# Generated by Django 4.2.16 on 2024-11-20 15:03

from datetime import datetime

from django.db import migrations

from olympia.constants.abuse import DECISION_ACTIONS


def add_action_date(apps, schema_editor):
    ContentDecision = apps.get_model('abuse', 'ContentDecision')
    ContentDecision.objects.filter(
        action=DECISION_ACTIONS.AMO_CLOSED_NO_ACTION, action_date=None
    ).update(action_date=datetime.now())

class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0044_cinderqueuemove'),
    ]

    operations = [
        migrations.RunPython(add_action_date, reverse_code=migrations.RunPython.noop)
    ]
