# Generated by Django 4.2.17 on 2025-01-20 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandwagon', '0008_alter_collection_options_alter_collection_managers_and_more'),
        ('ratings', '0011_remove_rating_one_review_per_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0028_alter_activitylog_action'),
        ('addons', '0053_alter_addon_summary_alter_addon_type'),
        ('abuse', '0047_cinderpolicy_present_in_cinder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdecision',
            name='activities',
            field=models.ManyToManyField(through='activity.ContentDecisionLog', to='activity.activitylog'),
        ),
        migrations.AddField(
            model_name='contentdecision',
            name='reviewer_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_made_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contentdecision',
            name='addon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_on', to='addons.addon'),
        ),
        migrations.AlterField(
            model_name='contentdecision',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_on', to='bandwagon.collection'),
        ),
        migrations.AlterField(
            model_name='contentdecision',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_on', to='ratings.rating'),
        ),
        migrations.AlterField(
            model_name='contentdecision',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_on', to=settings.AUTH_USER_MODEL),
        ),
    ]
