# Generated by Django 4.2.17 on 2025-01-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0047_auto_20241031_1750'),
        ('abuse', '0048_contentdecision_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdecision',
            name='target_versions',
            field=models.ManyToManyField(to='versions.version'),
        ),
    ]
