# Generated by Django 4.2.17 on 2025-01-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0049_contentdecision_target_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdecision',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
