# Generated by Django 4.2.19 on 2025-03-12 11:36

from django.db import migrations



def fill_enforcement_actions(apps, schema_editor):
    ACTIONS = {7: 'amo-approve', 11: 'amo-ignore'}
    CinderPolicy = apps.get_model('abuse', 'CinderPolicy')
    for policy in CinderPolicy.objects.filter(default_cinder_action__isnull=False):
        if api_value := ACTIONS.get(policy.default_cinder_action):
            policy.update(enforcement_actions=[api_value])


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0051_add_cinderpolicy_enforcement_actions'),
    ]

    operations = [
        migrations.RunPython(fill_enforcement_actions, migrations.RunPython.noop)
    ]
