# Generated by Django 4.2.20 on 2025-04-03 13:02

from django.db import migrations

from olympia.abuse.actions import ContentActionRejectVersion


def create_stakeholder_group(apps, schema_editor):
    Group = apps.get_model('access', 'Group')
    Group.objects.update_or_create(name=ContentActionRejectVersion.stakeholder_acl_group_name, defaults={'rules': 'None:None'})


def delete_stakeholder_group(apps, schema_editor):
    Group = apps.get_model('access', 'Group')
    Group.objects.filter(name=ContentActionRejectVersion.stakeholder_acl_group_name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0052_auto_fill_cinderpolicy_enforcement_actions'),
    ]

    operations = [
        migrations.RunPython(create_stakeholder_group, delete_stakeholder_group)
    ]
