# Generated by Django 4.2.20 on 2025-04-02 15:33

from django.db import migrations

from olympia.core.db.migrations import DeleteWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0052_auto_fill_cinderpolicy_enforcement_actions'),
    ]

    operations = [
        DeleteWaffleSwitch('dsa-appeals-review')
    ]
