# Generated by Django 4.2.20 on 2025-04-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0053_auto_20250403_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinderpolicy',
            name='default_cinder_action',
        ),
        migrations.AddField(
            model_name='contentdecision',
            name='cinder_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='abuse.cinderjob'),
        ),
        migrations.AlterField(
            model_name='cinderjob',
            name='decision',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_cinder_job', to='abuse.contentdecision'),
        ),
        migrations.AlterField(
            model_name='contentdecision',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User ban'), (2, 'Add-on disable'), (3, 'Forward add-on to reviewers'), (5, 'Rating delete'), (6, 'Collection delete'), (7, 'Approved (no action)'), (8, 'Add-on version reject'), (9, 'Add-on version delayed reject warning'), (10, 'Approved (new version approval)'), (11, 'Invalid report, so ignored'), (12, 'Content already removed (no action)'), (13, 'Forward add-on to legal'), (14, 'Pending rejection date changed'), (15, 'No action - internal requeue')]),
        ),
    ]
