# Generated by Django 4.2.20 on 2025-04-10 21:45

from django.db import migrations, models
import django.db.models.deletion


def set_cinder_job_on_decisions(apps, schema_editor):
    ContentDecision = apps.get_model('abuse', 'ContentDecision')
    decisions_with_jobs = []

    # Because there can be a chain of overrides we may need to recurse down the overrides, setting cinder_job on all of them
    def set_cinder_job(decision, job):
        decision.cinder_job = job
        decisions_with_jobs.append(decision)
        if hasattr(decision, 'overridden_by'):
            set_cinder_job(decision.overridden_by, job)

    for first_decision in ContentDecision.objects.filter(_cinder_job__isnull=False).using('default'):
        set_cinder_job(first_decision, first_decision._cinder_job)

    ContentDecision.objects.bulk_update(decisions_with_jobs, fields=('cinder_job',))


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0054_add_decision_cinderjob_fk'),
    ]

    operations = [
        migrations.RunPython(set_cinder_job_on_decisions, migrations.RunPython.noop),
    ]
