# Generated by Django 4.2.20 on 2025-04-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0055_fill_cinderjob_fk_on_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinderjob',
            name='job_id',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
