# Generated by Django 4.2.20 on 2025-04-30 16:16

import django.core.validators
from django.db import migrations, models

def empty_string_to_null(apps, schema_editor):
    CinderJob = apps.get_model('abuse', 'CinderJob')
    CinderJob.objects.filter(job_id='').update(job_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0056_alter_cinderjob_job_id'),
    ]

    operations = [
        migrations.RunPython(empty_string_to_null, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='cinderjob',
            options={},
        ),
        migrations.AddConstraint(
            model_name='cinderjob',
            constraint=models.CheckConstraint(check=models.Q(('job_id', ''), _negated=True), name='no_empty_job_id'),
        ),
        migrations.RemoveField(
            model_name='cinderjob',
            name='decision',
        ),
    ]
