# Generated by Django 4.2.20 on 2025-05-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0057_remove_cinderjob_decision_alter_cinderjob_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentdecision',
            old_name='notes',
            new_name='reasoning',
        ),
        migrations.AddField(
            model_name='contentdecision',
            name='private_notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
