# Generated by Django 4.2.21 on 2025-05-26 14:36

from django.db import migrations

from olympia.core.db.migrations import DeleteWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0058_rename_notes_contentdecision_reasoning_and_more'),
    ]

    operations = [
        DeleteWaffleSwitch('dsa-appeals-review')
    ]
