# Generated by Django 4.2.21 on 2025-05-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0058_rename_notes_contentdecision_reasoning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinderjob',
            name='forwarded_to_job',
        ),
        migrations.AlterField(
            model_name='contentdecision',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User ban'), (2, 'Add-on disable'), (3, '(Obsolete) Forward add-on to reviewers'), (5, 'Rating delete'), (6, 'Collection delete'), (7, 'Approved (no action)'), (8, 'Add-on version reject'), (9, 'Add-on version delayed reject warning'), (10, 'Approved (new version approval)'), (11, 'Invalid report, so ignored'), (12, 'Content already removed (no action)'), (13, 'Forward add-on to legal'), (14, 'Pending rejection date changed'), (15, 'No action - internal requeue')]),
        ),
    ]
