# Generated by Django 4.2.23 on 2025-07-10 09:58

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0059_auto_20250526_1436'),
    ]

    operations = [
        CreateWaffleSwitch(name='version-rollback')
    ]
