# Generated by Django 4.2.24 on 2025-09-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0060_auto_20250710_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinderjob',
            name='forwarded_to_job',
        ),
        migrations.AddField(
            model_name='contentdecision',
            name='from_job_queue',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='contentdecision',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User ban'), (2, 'Add-on disable'), (3, '(Obsolete) Forward add-on to reviewers'), (5, 'Rating delete'), (6, 'Collection delete'), (7, 'Approved (no action)'), (8, 'Add-on version reject'), (9, 'Add-on version delayed reject warning'), (10, 'Approved (new version approval)'), (11, 'Invalid report, so ignored'), (12, 'Content already moderated (no action)'), (13, 'Forward add-on to legal'), (14, 'Pending rejection date changed'), (15, 'No action - internal requeue'), (16, 'Add-on disable and block')]),
        ),
    ]
