# Generated by Django 4.2.24 on 2025-10-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0061_add_from_job_queue'),
    ]

    operations = [
        # django isn't catching we renamed the index in 0006_auto_20210813_0941.py with
        # our own migration class, so fake the RenameIndex.
        migrations.SeparateDatabaseAndState(
            [],
            [
                migrations.RenameIndex(
                    model_name='abusereport',
                    new_name='abuse_reports_created_idx',
                    old_name='created_idx',
                ),
            ]
        )

    ]
