# Generated by Django 5.2.12 on 2026-03-27 10:56

from django.db import migrations

from olympia.core.db.migrations import CreateWaffleSwitch


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0062_rename_created_idx_abuse_reports_created_idx'),
    ]

    operations = [
        CreateWaffleSwitch('content-review-in-cinder'),
    ]
