# Generated by Django 5.2.12 on 2026-04-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0063_create_content_review_in_cinder_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinderjob',
            name='content_review',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='contentdecision',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User ban'), (2, 'Add-on disable'), (3, '(Obsolete) Forward add-on to reviewers'), (5, 'Rating delete'), (6, 'Collection delete'), (7, 'Approved (no action)'), (8, 'Add-on version reject'), (9, 'Add-on version delayed reject warning'), (10, 'Approved (new version approval)'), (11, 'Invalid report, so ignored'), (12, 'Content already moderated (no action)'), (13, 'Forward add-on to legal'), (14, 'Pending rejection date changed'), (15, 'No action - internal requeue'), (16, 'Add-on disable and block'), (17, 'Add-on listing content rejection')]),
        ),
    ]
