# Generated by Django 5.2.12 on 2026-04-08 11:49

import django.db.models.deletion
import django.utils.timezone
import olympia.amo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0064_cinderjob_content_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDecisionEnforcementAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('enforcement', models.PositiveSmallIntegerField(choices=[(1, 'User ban'), (2, 'Add-on disable'), (3, '(Obsolete) Forward add-on to reviewers'), (5, 'Rating delete'), (6, 'Collection delete'), (7, 'Approved (no action)'), (8, 'Add-on version reject'), (9, 'Add-on version delayed reject warning'), (10, 'Approved (new version approval)'), (11, 'Invalid report, so ignored'), (12, 'Content already moderated (no action)'), (13, 'Forward add-on to legal'), (14, 'Pending rejection date changed'), (15, 'No action - internal requeue'), (16, 'Add-on disable and block'), (17, 'Add-on listing content rejection')])),
                ('enforcement_date', models.DateTimeField(db_column='date', null=True)),
                ('next', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='abuse.contentdecisionenforcementaction')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=(olympia.amo.models.SaveUpdateMixin, models.Model),
        ),
        migrations.AddField(
            model_name='contentdecision',
            name='first_action',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='decision', to='abuse.contentdecisionenforcementaction'),
        ),
        migrations.AlterField(
            model_name='contentdecision',
            name='action',
            field=models.PositiveSmallIntegerField(null=True, choices=[(1, 'User ban'), (2, 'Add-on disable'), (3, '(Obsolete) Forward add-on to reviewers'), (5, 'Rating delete'), (6, 'Collection delete'), (7, 'Approved (no action)'), (8, 'Add-on version reject'), (9, 'Add-on version delayed reject warning'), (10, 'Approved (new version approval)'), (11, 'Invalid report, so ignored'), (12, 'Content already moderated (no action)'), (13, 'Forward add-on to legal'), (14, 'Pending rejection date changed'), (15, 'No action - internal requeue'), (16, 'Add-on disable and block'), (17, 'Add-on listing content rejection')])
        )
    ]
