# Generated by Django 5.2.12 on 2026-04-08 11:50

from django.db import migrations


def create_first_action_for_existing_decisions(apps, schema_editor):
    ContentDecision = apps.get_model('abuse', 'ContentDecision')
    ContentDecisionEnforcementAction = apps.get_model(
        'abuse', 'ContentDecisionEnforcementAction'
    )

    for decision in ContentDecision.objects.filter(first_action__isnull=True):
        action = ContentDecisionEnforcementAction.objects.create(
            enforcement=decision.action,
            enforcement_date=decision.action_date,
        )
        decision.first_action = action
        decision.save(update_fields=['first_action'])


def fill_action_date_for_existing_decisions(apps, schema_editor):
    ContentDecision = apps.get_model('abuse', 'ContentDecision')

    for decision in ContentDecision.objects.filter(action__isnull=True, first_action__isnull=False):
        decision.action = decision.first_action.enforcement
        decision.action_date = decision.first_action.enforcement_date
        decision.save(update_fields=['action', 'action_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0065_remove_contentdecision_action_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_first_action_for_existing_decisions, reverse_code=fill_action_date_for_existing_decisions
        ),
    ]
