# Generated by Django 5.2.13 on 2026-05-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0065_alter_contentdecision_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinderpolicy',
            name='present_in_cinder',
        ),
        migrations.AddField(
            model_name='cinderpolicy',
            name='status_in_cinder',
            field=models.SmallIntegerField(choices=[(1, 'Published'), (2, 'Archived'), (3, 'Draft'), (4, 'Deleted')], null=True),
        ),
    ]
