# Generated by Django 5.2.13 on 2026-05-06 16:29

from django.db import migrations, models


def set_enforcement_actions_to_empty_list(apps, schema_editor):
    CinderPolicy = apps.get_model('abuse', 'CinderPolicy')
    for policy in CinderPolicy.objects.filter(enforcement_actions__isnull=True):
        policy.enforcement_actions = []
        policy.save(update_fields=['enforcement_actions'])


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0066_remove_cinderpolicy_present_in_cinder_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=set_enforcement_actions_to_empty_list,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='cinderpolicy',
            name='enforcement_actions',
            field=models.JSONField(default=list),
        ),
    ]
