# Generated by Django 5.2.12 on 2026-04-08 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0066_first_action_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentdecision',
            name='first_action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='decision', to='abuse.contentdecisionenforcementaction'),
        ),
    ]
