# Generated by Django 5.2.14 on 2026-06-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0067_make_cinderpolicy_enforcement_actions_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinderpolicy',
            name='status_in_cinder',
            field=models.SmallIntegerField(choices=[(1, 'Published'), (2, 'Archived'), (3, 'Draft'), (4, 'Deleted, is in use'), (5, 'Deleted, previously exposed in reviewer tools')], null=True),
        ),
    ]
