# Generated by Django 5.2.15 on 2026-06-25 16:00

from django.db import migrations

from olympia.abuse.actions import ContentActionLegalTakedownDisableAddon


def create_legal_takedown_group(apps, schema_editor):
    Group = apps.get_model('access', 'Group')
    Group.objects.update_or_create(name=ContentActionLegalTakedownDisableAddon.legal_takedown_group_name, defaults={'rules': 'None:None'})


def delete_legal_takedown_group(apps, schema_editor):
    Group = apps.get_model('access', 'Group')
    Group.objects.filter(name=ContentActionLegalTakedownDisableAddon.legal_takedown_group_name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0068_alter_cinderpolicy_status_in_cinder'),
    ]

    operations = [
        migrations.RunPython(create_legal_takedown_group, delete_legal_takedown_group)
    ]
