# Generated by Django 5.2.16 on 2026-07-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0069_auto_20260625_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinderpolicy',
            name='expose_in_reviewer_tools',
            field=models.SmallIntegerField(choices=[(0, 'Not exposed'), (1, 'All add-ons'), (2, 'Extensions'), (3, 'Themes')], default=0),
        ),
        migrations.AlterField(
            model_name='contentdecision',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User ban'), (2, 'Add-on disable'), (3, '(Obsolete) Forward add-on to reviewers'), (5, 'Rating delete'), (6, 'Collection delete'), (7, 'Approved'), (8, 'Add-on version reject'), (9, 'Add-on version delayed reject warning'), (10, 'Approved (new version approval)'), (11, 'Invalid report, so ignored'), (12, 'Content already moderated (no action)'), (13, 'Forward add-on to legal'), (14, 'Pending rejection date changed'), (15, 'No action - internal requeue'), (16, 'Add-on disable and block'), (17, 'Add-on listing content rejection'), (18, '[Follow-up] Short-delayed soft block'), (19, '[Follow-up] Mid-delayed soft block'), (20, '[Follow-up] Long-delayed soft block'), (21, '[Follow-up] Short-delayed hard block'), (22, '[Follow-up] Mid-delayed hard block'), (23, '[Follow-up] Long-delayed hard block'), (24, 'Add-on disable, due to legal takedown')]),
        ),
        migrations.AlterField(
            model_name='contentdecisionfollowupaction',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User ban'), (2, 'Add-on disable'), (3, '(Obsolete) Forward add-on to reviewers'), (5, 'Rating delete'), (6, 'Collection delete'), (7, 'Approved'), (8, 'Add-on version reject'), (9, 'Add-on version delayed reject warning'), (10, 'Approved (new version approval)'), (11, 'Invalid report, so ignored'), (12, 'Content already moderated (no action)'), (13, 'Forward add-on to legal'), (14, 'Pending rejection date changed'), (15, 'No action - internal requeue'), (16, 'Add-on disable and block'), (17, 'Add-on listing content rejection'), (18, '[Follow-up] Short-delayed soft block'), (19, '[Follow-up] Mid-delayed soft block'), (20, '[Follow-up] Long-delayed soft block'), (21, '[Follow-up] Short-delayed hard block'), (22, '[Follow-up] Mid-delayed hard block'), (23, '[Follow-up] Long-delayed hard block'), (24, 'Add-on disable, due to legal takedown')]),
        ),
    ]
