# Generated by Django 5.2.17 on 2026-08-24 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abuse', '0070_alter_cinderpolicy_expose_in_reviewer_tools_and_more'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdecision',
            name='action_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activity.activitylog'),
        ),
    ]
