// Named key codes. That's the key idea here.
z.keys = {
    'SHIFT': 16,
    'CONTROL': 17,
    'ALT': 18,
    'PAUSE': 19,
    'CAPS_LOCK': 20,
    'ESCAPE': 27,
    'ENTER': 13,
    'PAGE_UP': 33,
    'PAGE_DOWN': 34,
    'LEFT': 37,
    'UP': 38,
    'RIGHT': 39,
    'DOWN': 40,
    'HOME': 36,
    'END': 35,
    'COMMAND': 91,
    'WINDOWS_RIGHT': 92,
    'COMMAND_RIGHT': 93,
    'WINDOWS_LEFT_OPERA': 219,
    'WINDOWS_RIGHT_OPERA': 220,
    'APPLE': 24,
};
