name: Build Docker image

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        required: false
        description: The artifact name to use for the upload.
        type: string
        default: ''
      push:
        required: true
        description: Push the image to dockerhub?
        type: boolean
        default: false
      target:
        required: true
        description: The docker stage to target
        type: choice
        options:
          - development
          - production

concurrency:
  group: ${{ github.workflow }}-${{ inputs.target }}-${{ inputs.push }}
  cancel-in-progress: true

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build container
        id: build_container
        uses: ./.github/actions/build-docker
        with:
          artifact_name: ${{ inputs.artifact_name }}
          registry: docker.io
          image: ${{ github.repository }}
          version: build-${{ github.ref_name }}
          target: ${{ inputs.target }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          push: ${{ inputs.push }}
