name: Release

on:
  release:
  workflow_dispatch:

jobs:
  context:
    runs-on: ubuntu-latest

    steps:
      - name: Log (github)
        shell: bash
        run: |
          cat <<EOF
          ${{toJson(github)}}
          EOF
